namespace PresentationLayer
{
    partial class FormAdminHome
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormAdminHome));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges31 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges32 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges33 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges34 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges35 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges36 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            this.bunifuCircleProgress1 = new Bunifu.UI.WinForms.BunifuCircleProgress();
            this.panelLeft = new System.Windows.Forms.FlowLayoutPanel();
            this.btnProject = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProjectMemeber = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProjectPriority = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProjectStatus = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTask = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTaskPriority = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTaskStatus = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnUsers = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnUserRole = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDepartment = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRequest = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel3 = new System.Windows.Forms.Panel();
            this.lbUsername = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.lbUserRole = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.btnAvatar = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.panel2 = new System.Windows.Forms.Panel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.panelCenterContent = new System.Windows.Forms.Panel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.panelLeft.SuspendLayout();
            this.panel3.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuCircleProgress1
            // 
            this.bunifuCircleProgress1.Animated = false;
            this.bunifuCircleProgress1.AnimationInterval = 1;
            this.bunifuCircleProgress1.AnimationSpeed = 1;
            this.bunifuCircleProgress1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuCircleProgress1.CircleMargin = 10;
            this.bunifuCircleProgress1.Font = new System.Drawing.Font("Microsoft Sans Serif", 40F, System.Drawing.FontStyle.Bold);
            this.bunifuCircleProgress1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuCircleProgress1.IsPercentage = false;
            this.bunifuCircleProgress1.LineProgressThickness = 10;
            this.bunifuCircleProgress1.LineThickness = 10;
            this.bunifuCircleProgress1.Location = new System.Drawing.Point(0, 0);
            this.bunifuCircleProgress1.Name = "bunifuCircleProgress1";
            this.bunifuCircleProgress1.ProgressAnimationSpeed = 200;
            this.bunifuCircleProgress1.ProgressBackColor = System.Drawing.Color.Gainsboro;
            this.bunifuCircleProgress1.ProgressColor = System.Drawing.Color.DodgerBlue;
            this.bunifuCircleProgress1.ProgressColor2 = System.Drawing.Color.DodgerBlue;
            this.bunifuCircleProgress1.ProgressEndCap = Bunifu.UI.WinForms.BunifuCircleProgress.CapStyles.Round;
            this.bunifuCircleProgress1.ProgressFillStyle = Bunifu.UI.WinForms.BunifuCircleProgress.FillStyles.Solid;
            this.bunifuCircleProgress1.ProgressStartCap = Bunifu.UI.WinForms.BunifuCircleProgress.CapStyles.Round;
            this.bunifuCircleProgress1.SecondaryFont = new System.Drawing.Font("Microsoft Sans Serif", 16F);
            this.bunifuCircleProgress1.Size = new System.Drawing.Size(8, 8);
            this.bunifuCircleProgress1.SubScriptColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(166)))), ((int)(((byte)(166)))));
            this.bunifuCircleProgress1.SubScriptMargin = new System.Windows.Forms.Padding(5, -20, 0, 0);
            this.bunifuCircleProgress1.SubScriptText = ".00";
            this.bunifuCircleProgress1.SuperScriptColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(166)))), ((int)(((byte)(166)))));
            this.bunifuCircleProgress1.SuperScriptMargin = new System.Windows.Forms.Padding(5, 20, 0, 0);
            this.bunifuCircleProgress1.SuperScriptText = "°C";
            this.bunifuCircleProgress1.TabIndex = 26;
            this.bunifuCircleProgress1.Text = "30";
            this.bunifuCircleProgress1.TextMargin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.bunifuCircleProgress1.Value = 30;
            this.bunifuCircleProgress1.ValueByTransition = 30;
            this.bunifuCircleProgress1.ValueMargin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            // 
            // panelLeft
            // 
            this.panelLeft.Controls.Add(this.btnProject);
            this.panelLeft.Controls.Add(this.btnProjectMemeber);
            this.panelLeft.Controls.Add(this.btnProjectPriority);
            this.panelLeft.Controls.Add(this.btnProjectStatus);
            this.panelLeft.Controls.Add(this.btnTask);
            this.panelLeft.Controls.Add(this.btnTaskPriority);
            this.panelLeft.Controls.Add(this.btnTaskStatus);
            this.panelLeft.Controls.Add(this.btnUsers);
            this.panelLeft.Controls.Add(this.btnUserRole);
            this.panelLeft.Controls.Add(this.btnDepartment);
            this.panelLeft.Controls.Add(this.btnRequest);
            this.panelLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelLeft.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.panelLeft.Location = new System.Drawing.Point(0, 72);
            this.panelLeft.Name = "panelLeft";
            this.panelLeft.Size = new System.Drawing.Size(186, 615);
            this.panelLeft.TabIndex = 0;
            this.panelLeft.Paint += new System.Windows.Forms.PaintEventHandler(this.panelLeft_Paint);
            // 
            // btnProject
            // 
            this.btnProject.AllowAnimations = true;
            this.btnProject.AllowMouseEffects = true;
            this.btnProject.AllowToggling = false;
            this.btnProject.AnimationSpeed = 200;
            this.btnProject.AutoGenerateColors = false;
            this.btnProject.AutoRoundBorders = false;
            this.btnProject.AutoSizeLeftIcon = true;
            this.btnProject.AutoSizeRightIcon = true;
            this.btnProject.BackColor = System.Drawing.Color.Transparent;
            this.btnProject.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProject.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProject.BackgroundImage")));
            this.btnProject.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProject.ButtonText = "Projects";
            this.btnProject.ButtonTextMarginLeft = 0;
            this.btnProject.ColorContrastOnClick = 45;
            this.btnProject.ColorContrastOnHover = 45;
            this.btnProject.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges25.BottomLeft = false;
            borderEdges25.BottomRight = true;
            borderEdges25.TopLeft = false;
            borderEdges25.TopRight = true;
            this.btnProject.CustomizableEdges = borderEdges25;
            this.btnProject.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProject.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProject.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProject.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProject.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnProject.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProject.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProject.IconLeft = null;
            this.btnProject.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProject.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProject.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProject.IconMarginLeft = 11;
            this.btnProject.IconPadding = 6;
            this.btnProject.IconRight = null;
            this.btnProject.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProject.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProject.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProject.IconSize = 25;
            this.btnProject.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProject.IdleBorderRadius = 0;
            this.btnProject.IdleBorderThickness = 0;
            this.btnProject.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProject.IdleIconLeftImage = null;
            this.btnProject.IdleIconRightImage = null;
            this.btnProject.IndicateFocus = false;
            this.btnProject.Location = new System.Drawing.Point(3, 3);
            this.btnProject.Name = "btnProject";
            this.btnProject.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnProject.OnDisabledState.BorderRadius = 45;
            this.btnProject.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProject.OnDisabledState.BorderThickness = 1;
            this.btnProject.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnProject.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProject.OnDisabledState.IconLeftImage = null;
            this.btnProject.OnDisabledState.IconRightImage = null;
            this.btnProject.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnProject.onHoverState.BorderRadius = 45;
            this.btnProject.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProject.onHoverState.BorderThickness = 1;
            this.btnProject.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProject.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnProject.onHoverState.IconLeftImage = null;
            this.btnProject.onHoverState.IconRightImage = null;
            this.btnProject.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnProject.OnIdleState.BorderRadius = 45;
            this.btnProject.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProject.OnIdleState.BorderThickness = 1;
            this.btnProject.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnProject.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProject.OnIdleState.IconLeftImage = null;
            this.btnProject.OnIdleState.IconRightImage = null;
            this.btnProject.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnProject.OnPressedState.BorderRadius = 45;
            this.btnProject.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProject.OnPressedState.BorderThickness = 1;
            this.btnProject.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProject.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProject.OnPressedState.IconLeftImage = null;
            this.btnProject.OnPressedState.IconRightImage = null;
            this.btnProject.Size = new System.Drawing.Size(160, 45);
            this.btnProject.TabIndex = 21;
            this.btnProject.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProject.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProject.TextMarginLeft = 0;
            this.btnProject.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProject.UseDefaultRadiusAndThickness = true;
            this.btnProject.Click += new System.EventHandler(this.btnProject_Click);
            // 
            // btnProjectMemeber
            // 
            this.btnProjectMemeber.AllowAnimations = true;
            this.btnProjectMemeber.AllowMouseEffects = true;
            this.btnProjectMemeber.AllowToggling = false;
            this.btnProjectMemeber.AnimationSpeed = 200;
            this.btnProjectMemeber.AutoGenerateColors = false;
            this.btnProjectMemeber.AutoRoundBorders = false;
            this.btnProjectMemeber.AutoSizeLeftIcon = true;
            this.btnProjectMemeber.AutoSizeRightIcon = true;
            this.btnProjectMemeber.BackColor = System.Drawing.Color.Transparent;
            this.btnProjectMemeber.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProjectMemeber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProjectMemeber.BackgroundImage")));
            this.btnProjectMemeber.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectMemeber.ButtonText = "Project Member";
            this.btnProjectMemeber.ButtonTextMarginLeft = 0;
            this.btnProjectMemeber.ColorContrastOnClick = 45;
            this.btnProjectMemeber.ColorContrastOnHover = 45;
            this.btnProjectMemeber.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges26.BottomLeft = false;
            borderEdges26.BottomRight = true;
            borderEdges26.TopLeft = false;
            borderEdges26.TopRight = true;
            this.btnProjectMemeber.CustomizableEdges = borderEdges26;
            this.btnProjectMemeber.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProjectMemeber.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProjectMemeber.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProjectMemeber.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProjectMemeber.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnProjectMemeber.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProjectMemeber.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectMemeber.IconLeft = null;
            this.btnProjectMemeber.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProjectMemeber.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProjectMemeber.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProjectMemeber.IconMarginLeft = 11;
            this.btnProjectMemeber.IconPadding = 6;
            this.btnProjectMemeber.IconRight = null;
            this.btnProjectMemeber.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProjectMemeber.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProjectMemeber.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProjectMemeber.IconSize = 25;
            this.btnProjectMemeber.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProjectMemeber.IdleBorderRadius = 0;
            this.btnProjectMemeber.IdleBorderThickness = 0;
            this.btnProjectMemeber.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProjectMemeber.IdleIconLeftImage = null;
            this.btnProjectMemeber.IdleIconRightImage = null;
            this.btnProjectMemeber.IndicateFocus = false;
            this.btnProjectMemeber.Location = new System.Drawing.Point(3, 54);
            this.btnProjectMemeber.Name = "btnProjectMemeber";
            this.btnProjectMemeber.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnProjectMemeber.OnDisabledState.BorderRadius = 45;
            this.btnProjectMemeber.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectMemeber.OnDisabledState.BorderThickness = 1;
            this.btnProjectMemeber.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnProjectMemeber.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectMemeber.OnDisabledState.IconLeftImage = null;
            this.btnProjectMemeber.OnDisabledState.IconRightImage = null;
            this.btnProjectMemeber.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnProjectMemeber.onHoverState.BorderRadius = 45;
            this.btnProjectMemeber.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectMemeber.onHoverState.BorderThickness = 1;
            this.btnProjectMemeber.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProjectMemeber.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnProjectMemeber.onHoverState.IconLeftImage = null;
            this.btnProjectMemeber.onHoverState.IconRightImage = null;
            this.btnProjectMemeber.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnProjectMemeber.OnIdleState.BorderRadius = 45;
            this.btnProjectMemeber.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectMemeber.OnIdleState.BorderThickness = 1;
            this.btnProjectMemeber.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnProjectMemeber.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectMemeber.OnIdleState.IconLeftImage = null;
            this.btnProjectMemeber.OnIdleState.IconRightImage = null;
            this.btnProjectMemeber.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnProjectMemeber.OnPressedState.BorderRadius = 45;
            this.btnProjectMemeber.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectMemeber.OnPressedState.BorderThickness = 1;
            this.btnProjectMemeber.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProjectMemeber.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectMemeber.OnPressedState.IconLeftImage = null;
            this.btnProjectMemeber.OnPressedState.IconRightImage = null;
            this.btnProjectMemeber.Size = new System.Drawing.Size(160, 45);
            this.btnProjectMemeber.TabIndex = 22;
            this.btnProjectMemeber.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProjectMemeber.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProjectMemeber.TextMarginLeft = 0;
            this.btnProjectMemeber.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProjectMemeber.UseDefaultRadiusAndThickness = true;
            this.btnProjectMemeber.Click += new System.EventHandler(this.btnProjectMemeber_Click);
            // 
            // btnProjectPriority
            // 
            this.btnProjectPriority.AllowAnimations = true;
            this.btnProjectPriority.AllowMouseEffects = true;
            this.btnProjectPriority.AllowToggling = false;
            this.btnProjectPriority.AnimationSpeed = 200;
            this.btnProjectPriority.AutoGenerateColors = false;
            this.btnProjectPriority.AutoRoundBorders = false;
            this.btnProjectPriority.AutoSizeLeftIcon = true;
            this.btnProjectPriority.AutoSizeRightIcon = true;
            this.btnProjectPriority.BackColor = System.Drawing.Color.Transparent;
            this.btnProjectPriority.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProjectPriority.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProjectPriority.BackgroundImage")));
            this.btnProjectPriority.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectPriority.ButtonText = "Project  Priority";
            this.btnProjectPriority.ButtonTextMarginLeft = 0;
            this.btnProjectPriority.ColorContrastOnClick = 45;
            this.btnProjectPriority.ColorContrastOnHover = 45;
            this.btnProjectPriority.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges27.BottomLeft = true;
            borderEdges27.BottomRight = true;
            borderEdges27.TopLeft = true;
            borderEdges27.TopRight = true;
            this.btnProjectPriority.CustomizableEdges = borderEdges27;
            this.btnProjectPriority.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProjectPriority.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProjectPriority.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProjectPriority.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProjectPriority.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnProjectPriority.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProjectPriority.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectPriority.IconLeft = null;
            this.btnProjectPriority.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProjectPriority.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProjectPriority.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProjectPriority.IconMarginLeft = 11;
            this.btnProjectPriority.IconPadding = 6;
            this.btnProjectPriority.IconRight = null;
            this.btnProjectPriority.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProjectPriority.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProjectPriority.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProjectPriority.IconSize = 25;
            this.btnProjectPriority.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProjectPriority.IdleBorderRadius = 0;
            this.btnProjectPriority.IdleBorderThickness = 0;
            this.btnProjectPriority.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProjectPriority.IdleIconLeftImage = null;
            this.btnProjectPriority.IdleIconRightImage = null;
            this.btnProjectPriority.IndicateFocus = false;
            this.btnProjectPriority.Location = new System.Drawing.Point(3, 105);
            this.btnProjectPriority.Name = "btnProjectPriority";
            this.btnProjectPriority.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnProjectPriority.OnDisabledState.BorderRadius = 1;
            this.btnProjectPriority.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectPriority.OnDisabledState.BorderThickness = 1;
            this.btnProjectPriority.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnProjectPriority.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectPriority.OnDisabledState.IconLeftImage = null;
            this.btnProjectPriority.OnDisabledState.IconRightImage = null;
            this.btnProjectPriority.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnProjectPriority.onHoverState.BorderRadius = 1;
            this.btnProjectPriority.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectPriority.onHoverState.BorderThickness = 1;
            this.btnProjectPriority.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProjectPriority.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnProjectPriority.onHoverState.IconLeftImage = null;
            this.btnProjectPriority.onHoverState.IconRightImage = null;
            this.btnProjectPriority.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnProjectPriority.OnIdleState.BorderRadius = 1;
            this.btnProjectPriority.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectPriority.OnIdleState.BorderThickness = 1;
            this.btnProjectPriority.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnProjectPriority.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectPriority.OnIdleState.IconLeftImage = null;
            this.btnProjectPriority.OnIdleState.IconRightImage = null;
            this.btnProjectPriority.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnProjectPriority.OnPressedState.BorderRadius = 1;
            this.btnProjectPriority.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectPriority.OnPressedState.BorderThickness = 1;
            this.btnProjectPriority.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProjectPriority.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectPriority.OnPressedState.IconLeftImage = null;
            this.btnProjectPriority.OnPressedState.IconRightImage = null;
            this.btnProjectPriority.Size = new System.Drawing.Size(160, 45);
            this.btnProjectPriority.TabIndex = 21;
            this.btnProjectPriority.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProjectPriority.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProjectPriority.TextMarginLeft = 0;
            this.btnProjectPriority.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProjectPriority.UseDefaultRadiusAndThickness = true;
            this.btnProjectPriority.Click += new System.EventHandler(this.btnProjectPriorityAdmin_Click);
            // 
            // btnProjectStatus
            // 
            this.btnProjectStatus.AllowAnimations = true;
            this.btnProjectStatus.AllowMouseEffects = true;
            this.btnProjectStatus.AllowToggling = false;
            this.btnProjectStatus.AnimationSpeed = 200;
            this.btnProjectStatus.AutoGenerateColors = false;
            this.btnProjectStatus.AutoRoundBorders = false;
            this.btnProjectStatus.AutoSizeLeftIcon = true;
            this.btnProjectStatus.AutoSizeRightIcon = true;
            this.btnProjectStatus.BackColor = System.Drawing.Color.Transparent;
            this.btnProjectStatus.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProjectStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProjectStatus.BackgroundImage")));
            this.btnProjectStatus.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectStatus.ButtonText = "Project Status";
            this.btnProjectStatus.ButtonTextMarginLeft = 0;
            this.btnProjectStatus.ColorContrastOnClick = 45;
            this.btnProjectStatus.ColorContrastOnHover = 45;
            this.btnProjectStatus.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges28.BottomLeft = true;
            borderEdges28.BottomRight = true;
            borderEdges28.TopLeft = true;
            borderEdges28.TopRight = true;
            this.btnProjectStatus.CustomizableEdges = borderEdges28;
            this.btnProjectStatus.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProjectStatus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProjectStatus.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProjectStatus.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProjectStatus.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnProjectStatus.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProjectStatus.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectStatus.IconLeft = null;
            this.btnProjectStatus.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProjectStatus.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProjectStatus.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProjectStatus.IconMarginLeft = 11;
            this.btnProjectStatus.IconPadding = 6;
            this.btnProjectStatus.IconRight = null;
            this.btnProjectStatus.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProjectStatus.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProjectStatus.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProjectStatus.IconSize = 25;
            this.btnProjectStatus.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProjectStatus.IdleBorderRadius = 0;
            this.btnProjectStatus.IdleBorderThickness = 0;
            this.btnProjectStatus.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProjectStatus.IdleIconLeftImage = null;
            this.btnProjectStatus.IdleIconRightImage = null;
            this.btnProjectStatus.IndicateFocus = false;
            this.btnProjectStatus.Location = new System.Drawing.Point(3, 156);
            this.btnProjectStatus.Name = "btnProjectStatus";
            this.btnProjectStatus.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnProjectStatus.OnDisabledState.BorderRadius = 1;
            this.btnProjectStatus.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectStatus.OnDisabledState.BorderThickness = 1;
            this.btnProjectStatus.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnProjectStatus.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectStatus.OnDisabledState.IconLeftImage = null;
            this.btnProjectStatus.OnDisabledState.IconRightImage = null;
            this.btnProjectStatus.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnProjectStatus.onHoverState.BorderRadius = 1;
            this.btnProjectStatus.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectStatus.onHoverState.BorderThickness = 1;
            this.btnProjectStatus.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProjectStatus.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnProjectStatus.onHoverState.IconLeftImage = null;
            this.btnProjectStatus.onHoverState.IconRightImage = null;
            this.btnProjectStatus.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnProjectStatus.OnIdleState.BorderRadius = 1;
            this.btnProjectStatus.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectStatus.OnIdleState.BorderThickness = 1;
            this.btnProjectStatus.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnProjectStatus.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectStatus.OnIdleState.IconLeftImage = null;
            this.btnProjectStatus.OnIdleState.IconRightImage = null;
            this.btnProjectStatus.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnProjectStatus.OnPressedState.BorderRadius = 1;
            this.btnProjectStatus.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProjectStatus.OnPressedState.BorderThickness = 1;
            this.btnProjectStatus.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnProjectStatus.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnProjectStatus.OnPressedState.IconLeftImage = null;
            this.btnProjectStatus.OnPressedState.IconRightImage = null;
            this.btnProjectStatus.Size = new System.Drawing.Size(160, 45);
            this.btnProjectStatus.TabIndex = 21;
            this.btnProjectStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProjectStatus.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProjectStatus.TextMarginLeft = 0;
            this.btnProjectStatus.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProjectStatus.UseDefaultRadiusAndThickness = true;
            this.btnProjectStatus.Click += new System.EventHandler(this.btnProjectStatusAdmin_Click);
            // 
            // btnTask
            // 
            this.btnTask.AllowAnimations = true;
            this.btnTask.AllowMouseEffects = true;
            this.btnTask.AllowToggling = false;
            this.btnTask.AnimationSpeed = 200;
            this.btnTask.AutoGenerateColors = false;
            this.btnTask.AutoRoundBorders = false;
            this.btnTask.AutoSizeLeftIcon = true;
            this.btnTask.AutoSizeRightIcon = true;
            this.btnTask.BackColor = System.Drawing.Color.Transparent;
            this.btnTask.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnTask.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTask.BackgroundImage")));
            this.btnTask.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.ButtonText = "Tasks";
            this.btnTask.ButtonTextMarginLeft = 0;
            this.btnTask.ColorContrastOnClick = 45;
            this.btnTask.ColorContrastOnHover = 45;
            this.btnTask.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges29.BottomLeft = true;
            borderEdges29.BottomRight = true;
            borderEdges29.TopLeft = true;
            borderEdges29.TopRight = true;
            this.btnTask.CustomizableEdges = borderEdges29;
            this.btnTask.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTask.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTask.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnTask.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnTask.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnTask.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTask.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTask.IconLeft = null;
            this.btnTask.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTask.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTask.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTask.IconMarginLeft = 11;
            this.btnTask.IconPadding = 6;
            this.btnTask.IconRight = null;
            this.btnTask.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTask.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTask.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTask.IconSize = 25;
            this.btnTask.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnTask.IdleBorderRadius = 0;
            this.btnTask.IdleBorderThickness = 0;
            this.btnTask.IdleFillColor = System.Drawing.Color.Empty;
            this.btnTask.IdleIconLeftImage = null;
            this.btnTask.IdleIconRightImage = null;
            this.btnTask.IndicateFocus = false;
            this.btnTask.Location = new System.Drawing.Point(3, 207);
            this.btnTask.Name = "btnTask";
            this.btnTask.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnTask.OnDisabledState.BorderRadius = 1;
            this.btnTask.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.OnDisabledState.BorderThickness = 1;
            this.btnTask.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnTask.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTask.OnDisabledState.IconLeftImage = null;
            this.btnTask.OnDisabledState.IconRightImage = null;
            this.btnTask.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnTask.onHoverState.BorderRadius = 1;
            this.btnTask.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.onHoverState.BorderThickness = 1;
            this.btnTask.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnTask.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnTask.onHoverState.IconLeftImage = null;
            this.btnTask.onHoverState.IconRightImage = null;
            this.btnTask.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnTask.OnIdleState.BorderRadius = 1;
            this.btnTask.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.OnIdleState.BorderThickness = 1;
            this.btnTask.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnTask.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTask.OnIdleState.IconLeftImage = null;
            this.btnTask.OnIdleState.IconRightImage = null;
            this.btnTask.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnTask.OnPressedState.BorderRadius = 1;
            this.btnTask.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.OnPressedState.BorderThickness = 1;
            this.btnTask.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnTask.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTask.OnPressedState.IconLeftImage = null;
            this.btnTask.OnPressedState.IconRightImage = null;
            this.btnTask.Size = new System.Drawing.Size(160, 45);
            this.btnTask.TabIndex = 21;
            this.btnTask.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTask.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTask.TextMarginLeft = 0;
            this.btnTask.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTask.UseDefaultRadiusAndThickness = true;
            this.btnTask.Click += new System.EventHandler(this.btnTask_Click);
            // 
            // btnTaskPriority
            // 
            this.btnTaskPriority.AllowAnimations = true;
            this.btnTaskPriority.AllowMouseEffects = true;
            this.btnTaskPriority.AllowToggling = false;
            this.btnTaskPriority.AnimationSpeed = 200;
            this.btnTaskPriority.AutoGenerateColors = false;
            this.btnTaskPriority.AutoRoundBorders = false;
            this.btnTaskPriority.AutoSizeLeftIcon = true;
            this.btnTaskPriority.AutoSizeRightIcon = true;
            this.btnTaskPriority.BackColor = System.Drawing.Color.Transparent;
            this.btnTaskPriority.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnTaskPriority.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTaskPriority.BackgroundImage")));
            this.btnTaskPriority.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskPriority.ButtonText = "Task Prority";
            this.btnTaskPriority.ButtonTextMarginLeft = 0;
            this.btnTaskPriority.ColorContrastOnClick = 45;
            this.btnTaskPriority.ColorContrastOnHover = 45;
            this.btnTaskPriority.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges30.BottomLeft = true;
            borderEdges30.BottomRight = true;
            borderEdges30.TopLeft = true;
            borderEdges30.TopRight = true;
            this.btnTaskPriority.CustomizableEdges = borderEdges30;
            this.btnTaskPriority.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTaskPriority.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTaskPriority.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnTaskPriority.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnTaskPriority.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnTaskPriority.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTaskPriority.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTaskPriority.IconLeft = null;
            this.btnTaskPriority.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTaskPriority.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTaskPriority.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTaskPriority.IconMarginLeft = 11;
            this.btnTaskPriority.IconPadding = 6;
            this.btnTaskPriority.IconRight = null;
            this.btnTaskPriority.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTaskPriority.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTaskPriority.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTaskPriority.IconSize = 25;
            this.btnTaskPriority.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnTaskPriority.IdleBorderRadius = 0;
            this.btnTaskPriority.IdleBorderThickness = 0;
            this.btnTaskPriority.IdleFillColor = System.Drawing.Color.Empty;
            this.btnTaskPriority.IdleIconLeftImage = null;
            this.btnTaskPriority.IdleIconRightImage = null;
            this.btnTaskPriority.IndicateFocus = false;
            this.btnTaskPriority.Location = new System.Drawing.Point(3, 258);
            this.btnTaskPriority.Name = "btnTaskPriority";
            this.btnTaskPriority.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnTaskPriority.OnDisabledState.BorderRadius = 1;
            this.btnTaskPriority.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskPriority.OnDisabledState.BorderThickness = 1;
            this.btnTaskPriority.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnTaskPriority.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTaskPriority.OnDisabledState.IconLeftImage = null;
            this.btnTaskPriority.OnDisabledState.IconRightImage = null;
            this.btnTaskPriority.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnTaskPriority.onHoverState.BorderRadius = 1;
            this.btnTaskPriority.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskPriority.onHoverState.BorderThickness = 1;
            this.btnTaskPriority.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnTaskPriority.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnTaskPriority.onHoverState.IconLeftImage = null;
            this.btnTaskPriority.onHoverState.IconRightImage = null;
            this.btnTaskPriority.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnTaskPriority.OnIdleState.BorderRadius = 1;
            this.btnTaskPriority.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskPriority.OnIdleState.BorderThickness = 1;
            this.btnTaskPriority.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnTaskPriority.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTaskPriority.OnIdleState.IconLeftImage = null;
            this.btnTaskPriority.OnIdleState.IconRightImage = null;
            this.btnTaskPriority.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnTaskPriority.OnPressedState.BorderRadius = 1;
            this.btnTaskPriority.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskPriority.OnPressedState.BorderThickness = 1;
            this.btnTaskPriority.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnTaskPriority.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTaskPriority.OnPressedState.IconLeftImage = null;
            this.btnTaskPriority.OnPressedState.IconRightImage = null;
            this.btnTaskPriority.Size = new System.Drawing.Size(160, 45);
            this.btnTaskPriority.TabIndex = 21;
            this.btnTaskPriority.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTaskPriority.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTaskPriority.TextMarginLeft = 0;
            this.btnTaskPriority.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTaskPriority.UseDefaultRadiusAndThickness = true;
            this.btnTaskPriority.Click += new System.EventHandler(this.btnTaskPriorityAdmin_Click);
            // 
            // btnTaskStatus
            // 
            this.btnTaskStatus.AllowAnimations = true;
            this.btnTaskStatus.AllowMouseEffects = true;
            this.btnTaskStatus.AllowToggling = false;
            this.btnTaskStatus.AnimationSpeed = 200;
            this.btnTaskStatus.AutoGenerateColors = false;
            this.btnTaskStatus.AutoRoundBorders = false;
            this.btnTaskStatus.AutoSizeLeftIcon = true;
            this.btnTaskStatus.AutoSizeRightIcon = true;
            this.btnTaskStatus.BackColor = System.Drawing.Color.Transparent;
            this.btnTaskStatus.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnTaskStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTaskStatus.BackgroundImage")));
            this.btnTaskStatus.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskStatus.ButtonText = "Task Status";
            this.btnTaskStatus.ButtonTextMarginLeft = 0;
            this.btnTaskStatus.ColorContrastOnClick = 45;
            this.btnTaskStatus.ColorContrastOnHover = 45;
            this.btnTaskStatus.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges31.BottomLeft = true;
            borderEdges31.BottomRight = true;
            borderEdges31.TopLeft = true;
            borderEdges31.TopRight = true;
            this.btnTaskStatus.CustomizableEdges = borderEdges31;
            this.btnTaskStatus.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTaskStatus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTaskStatus.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnTaskStatus.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnTaskStatus.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnTaskStatus.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTaskStatus.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTaskStatus.IconLeft = null;
            this.btnTaskStatus.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTaskStatus.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTaskStatus.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTaskStatus.IconMarginLeft = 11;
            this.btnTaskStatus.IconPadding = 6;
            this.btnTaskStatus.IconRight = null;
            this.btnTaskStatus.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTaskStatus.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTaskStatus.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTaskStatus.IconSize = 25;
            this.btnTaskStatus.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnTaskStatus.IdleBorderRadius = 0;
            this.btnTaskStatus.IdleBorderThickness = 0;
            this.btnTaskStatus.IdleFillColor = System.Drawing.Color.Empty;
            this.btnTaskStatus.IdleIconLeftImage = null;
            this.btnTaskStatus.IdleIconRightImage = null;
            this.btnTaskStatus.IndicateFocus = false;
            this.btnTaskStatus.Location = new System.Drawing.Point(3, 309);
            this.btnTaskStatus.Name = "btnTaskStatus";
            this.btnTaskStatus.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnTaskStatus.OnDisabledState.BorderRadius = 1;
            this.btnTaskStatus.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskStatus.OnDisabledState.BorderThickness = 1;
            this.btnTaskStatus.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnTaskStatus.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTaskStatus.OnDisabledState.IconLeftImage = null;
            this.btnTaskStatus.OnDisabledState.IconRightImage = null;
            this.btnTaskStatus.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnTaskStatus.onHoverState.BorderRadius = 1;
            this.btnTaskStatus.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskStatus.onHoverState.BorderThickness = 1;
            this.btnTaskStatus.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnTaskStatus.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnTaskStatus.onHoverState.IconLeftImage = null;
            this.btnTaskStatus.onHoverState.IconRightImage = null;
            this.btnTaskStatus.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnTaskStatus.OnIdleState.BorderRadius = 1;
            this.btnTaskStatus.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskStatus.OnIdleState.BorderThickness = 1;
            this.btnTaskStatus.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnTaskStatus.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTaskStatus.OnIdleState.IconLeftImage = null;
            this.btnTaskStatus.OnIdleState.IconRightImage = null;
            this.btnTaskStatus.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnTaskStatus.OnPressedState.BorderRadius = 1;
            this.btnTaskStatus.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaskStatus.OnPressedState.BorderThickness = 1;
            this.btnTaskStatus.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnTaskStatus.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTaskStatus.OnPressedState.IconLeftImage = null;
            this.btnTaskStatus.OnPressedState.IconRightImage = null;
            this.btnTaskStatus.Size = new System.Drawing.Size(160, 45);
            this.btnTaskStatus.TabIndex = 21;
            this.btnTaskStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTaskStatus.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTaskStatus.TextMarginLeft = 0;
            this.btnTaskStatus.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTaskStatus.UseDefaultRadiusAndThickness = true;
            this.btnTaskStatus.Click += new System.EventHandler(this.btnTaskStatusAdmin_Click);
            // 
            // btnUsers
            // 
            this.btnUsers.AllowAnimations = true;
            this.btnUsers.AllowMouseEffects = true;
            this.btnUsers.AllowToggling = false;
            this.btnUsers.AnimationSpeed = 200;
            this.btnUsers.AutoGenerateColors = false;
            this.btnUsers.AutoRoundBorders = false;
            this.btnUsers.AutoSizeLeftIcon = true;
            this.btnUsers.AutoSizeRightIcon = true;
            this.btnUsers.BackColor = System.Drawing.Color.Transparent;
            this.btnUsers.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnUsers.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUsers.BackgroundImage")));
            this.btnUsers.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.ButtonText = "Users";
            this.btnUsers.ButtonTextMarginLeft = 0;
            this.btnUsers.ColorContrastOnClick = 45;
            this.btnUsers.ColorContrastOnHover = 45;
            this.btnUsers.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges32.BottomLeft = true;
            borderEdges32.BottomRight = true;
            borderEdges32.TopLeft = true;
            borderEdges32.TopRight = true;
            this.btnUsers.CustomizableEdges = borderEdges32;
            this.btnUsers.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUsers.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsers.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnUsers.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnUsers.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnUsers.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUsers.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnUsers.IconLeft = null;
            this.btnUsers.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsers.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUsers.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUsers.IconMarginLeft = 11;
            this.btnUsers.IconPadding = 6;
            this.btnUsers.IconRight = null;
            this.btnUsers.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUsers.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUsers.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUsers.IconSize = 25;
            this.btnUsers.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnUsers.IdleBorderRadius = 0;
            this.btnUsers.IdleBorderThickness = 0;
            this.btnUsers.IdleFillColor = System.Drawing.Color.Empty;
            this.btnUsers.IdleIconLeftImage = null;
            this.btnUsers.IdleIconRightImage = null;
            this.btnUsers.IndicateFocus = false;
            this.btnUsers.Location = new System.Drawing.Point(3, 360);
            this.btnUsers.Name = "btnUsers";
            this.btnUsers.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnUsers.OnDisabledState.BorderRadius = 1;
            this.btnUsers.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.OnDisabledState.BorderThickness = 1;
            this.btnUsers.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnUsers.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnUsers.OnDisabledState.IconLeftImage = null;
            this.btnUsers.OnDisabledState.IconRightImage = null;
            this.btnUsers.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnUsers.onHoverState.BorderRadius = 1;
            this.btnUsers.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.onHoverState.BorderThickness = 1;
            this.btnUsers.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnUsers.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnUsers.onHoverState.IconLeftImage = null;
            this.btnUsers.onHoverState.IconRightImage = null;
            this.btnUsers.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnUsers.OnIdleState.BorderRadius = 1;
            this.btnUsers.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.OnIdleState.BorderThickness = 1;
            this.btnUsers.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnUsers.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnUsers.OnIdleState.IconLeftImage = null;
            this.btnUsers.OnIdleState.IconRightImage = null;
            this.btnUsers.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnUsers.OnPressedState.BorderRadius = 1;
            this.btnUsers.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsers.OnPressedState.BorderThickness = 1;
            this.btnUsers.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnUsers.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnUsers.OnPressedState.IconLeftImage = null;
            this.btnUsers.OnPressedState.IconRightImage = null;
            this.btnUsers.Size = new System.Drawing.Size(160, 45);
            this.btnUsers.TabIndex = 21;
            this.btnUsers.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsers.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUsers.TextMarginLeft = 0;
            this.btnUsers.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUsers.UseDefaultRadiusAndThickness = true;
            this.btnUsers.Click += new System.EventHandler(this.btnUsers_Click);
            // 
            // btnUserRole
            // 
            this.btnUserRole.AllowAnimations = true;
            this.btnUserRole.AllowMouseEffects = true;
            this.btnUserRole.AllowToggling = false;
            this.btnUserRole.AnimationSpeed = 200;
            this.btnUserRole.AutoGenerateColors = false;
            this.btnUserRole.AutoRoundBorders = false;
            this.btnUserRole.AutoSizeLeftIcon = true;
            this.btnUserRole.AutoSizeRightIcon = true;
            this.btnUserRole.BackColor = System.Drawing.Color.Transparent;
            this.btnUserRole.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnUserRole.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUserRole.BackgroundImage")));
            this.btnUserRole.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserRole.ButtonText = "User Role";
            this.btnUserRole.ButtonTextMarginLeft = 0;
            this.btnUserRole.ColorContrastOnClick = 45;
            this.btnUserRole.ColorContrastOnHover = 45;
            this.btnUserRole.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges33.BottomLeft = true;
            borderEdges33.BottomRight = true;
            borderEdges33.TopLeft = true;
            borderEdges33.TopRight = true;
            this.btnUserRole.CustomizableEdges = borderEdges33;
            this.btnUserRole.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUserRole.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUserRole.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnUserRole.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnUserRole.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnUserRole.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUserRole.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnUserRole.IconLeft = null;
            this.btnUserRole.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUserRole.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUserRole.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUserRole.IconMarginLeft = 11;
            this.btnUserRole.IconPadding = 6;
            this.btnUserRole.IconRight = null;
            this.btnUserRole.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUserRole.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUserRole.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUserRole.IconSize = 25;
            this.btnUserRole.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnUserRole.IdleBorderRadius = 0;
            this.btnUserRole.IdleBorderThickness = 0;
            this.btnUserRole.IdleFillColor = System.Drawing.Color.Empty;
            this.btnUserRole.IdleIconLeftImage = null;
            this.btnUserRole.IdleIconRightImage = null;
            this.btnUserRole.IndicateFocus = false;
            this.btnUserRole.Location = new System.Drawing.Point(3, 411);
            this.btnUserRole.Name = "btnUserRole";
            this.btnUserRole.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnUserRole.OnDisabledState.BorderRadius = 1;
            this.btnUserRole.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserRole.OnDisabledState.BorderThickness = 1;
            this.btnUserRole.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnUserRole.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnUserRole.OnDisabledState.IconLeftImage = null;
            this.btnUserRole.OnDisabledState.IconRightImage = null;
            this.btnUserRole.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnUserRole.onHoverState.BorderRadius = 1;
            this.btnUserRole.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserRole.onHoverState.BorderThickness = 1;
            this.btnUserRole.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnUserRole.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnUserRole.onHoverState.IconLeftImage = null;
            this.btnUserRole.onHoverState.IconRightImage = null;
            this.btnUserRole.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnUserRole.OnIdleState.BorderRadius = 1;
            this.btnUserRole.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserRole.OnIdleState.BorderThickness = 1;
            this.btnUserRole.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnUserRole.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnUserRole.OnIdleState.IconLeftImage = null;
            this.btnUserRole.OnIdleState.IconRightImage = null;
            this.btnUserRole.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnUserRole.OnPressedState.BorderRadius = 1;
            this.btnUserRole.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserRole.OnPressedState.BorderThickness = 1;
            this.btnUserRole.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnUserRole.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnUserRole.OnPressedState.IconLeftImage = null;
            this.btnUserRole.OnPressedState.IconRightImage = null;
            this.btnUserRole.Size = new System.Drawing.Size(160, 45);
            this.btnUserRole.TabIndex = 21;
            this.btnUserRole.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUserRole.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUserRole.TextMarginLeft = 0;
            this.btnUserRole.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUserRole.UseDefaultRadiusAndThickness = true;
            this.btnUserRole.Click += new System.EventHandler(this.btnUserRoleAdmin_Click);
            // 
            // btnDepartment
            // 
            this.btnDepartment.AllowAnimations = true;
            this.btnDepartment.AllowMouseEffects = true;
            this.btnDepartment.AllowToggling = false;
            this.btnDepartment.AnimationSpeed = 200;
            this.btnDepartment.AutoGenerateColors = false;
            this.btnDepartment.AutoRoundBorders = false;
            this.btnDepartment.AutoSizeLeftIcon = true;
            this.btnDepartment.AutoSizeRightIcon = true;
            this.btnDepartment.BackColor = System.Drawing.Color.Transparent;
            this.btnDepartment.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnDepartment.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDepartment.BackgroundImage")));
            this.btnDepartment.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDepartment.ButtonText = "Department";
            this.btnDepartment.ButtonTextMarginLeft = 0;
            this.btnDepartment.ColorContrastOnClick = 45;
            this.btnDepartment.ColorContrastOnHover = 45;
            this.btnDepartment.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges34.BottomLeft = true;
            borderEdges34.BottomRight = true;
            borderEdges34.TopLeft = true;
            borderEdges34.TopRight = true;
            this.btnDepartment.CustomizableEdges = borderEdges34;
            this.btnDepartment.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDepartment.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDepartment.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnDepartment.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnDepartment.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnDepartment.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDepartment.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnDepartment.IconLeft = null;
            this.btnDepartment.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDepartment.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDepartment.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDepartment.IconMarginLeft = 11;
            this.btnDepartment.IconPadding = 6;
            this.btnDepartment.IconRight = null;
            this.btnDepartment.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDepartment.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDepartment.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDepartment.IconSize = 25;
            this.btnDepartment.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnDepartment.IdleBorderRadius = 0;
            this.btnDepartment.IdleBorderThickness = 0;
            this.btnDepartment.IdleFillColor = System.Drawing.Color.Empty;
            this.btnDepartment.IdleIconLeftImage = null;
            this.btnDepartment.IdleIconRightImage = null;
            this.btnDepartment.IndicateFocus = false;
            this.btnDepartment.Location = new System.Drawing.Point(3, 462);
            this.btnDepartment.Name = "btnDepartment";
            this.btnDepartment.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnDepartment.OnDisabledState.BorderRadius = 1;
            this.btnDepartment.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDepartment.OnDisabledState.BorderThickness = 1;
            this.btnDepartment.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnDepartment.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnDepartment.OnDisabledState.IconLeftImage = null;
            this.btnDepartment.OnDisabledState.IconRightImage = null;
            this.btnDepartment.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnDepartment.onHoverState.BorderRadius = 1;
            this.btnDepartment.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDepartment.onHoverState.BorderThickness = 1;
            this.btnDepartment.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnDepartment.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnDepartment.onHoverState.IconLeftImage = null;
            this.btnDepartment.onHoverState.IconRightImage = null;
            this.btnDepartment.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnDepartment.OnIdleState.BorderRadius = 1;
            this.btnDepartment.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDepartment.OnIdleState.BorderThickness = 1;
            this.btnDepartment.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnDepartment.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnDepartment.OnIdleState.IconLeftImage = null;
            this.btnDepartment.OnIdleState.IconRightImage = null;
            this.btnDepartment.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnDepartment.OnPressedState.BorderRadius = 1;
            this.btnDepartment.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDepartment.OnPressedState.BorderThickness = 1;
            this.btnDepartment.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnDepartment.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnDepartment.OnPressedState.IconLeftImage = null;
            this.btnDepartment.OnPressedState.IconRightImage = null;
            this.btnDepartment.Size = new System.Drawing.Size(160, 45);
            this.btnDepartment.TabIndex = 21;
            this.btnDepartment.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDepartment.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDepartment.TextMarginLeft = 0;
            this.btnDepartment.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDepartment.UseDefaultRadiusAndThickness = true;
            this.btnDepartment.Click += new System.EventHandler(this.btnDepartmentAdmin_Click);
            // 
            // btnRequest
            // 
            this.btnRequest.AllowAnimations = true;
            this.btnRequest.AllowMouseEffects = true;
            this.btnRequest.AllowToggling = false;
            this.btnRequest.AnimationSpeed = 200;
            this.btnRequest.AutoGenerateColors = false;
            this.btnRequest.AutoRoundBorders = false;
            this.btnRequest.AutoSizeLeftIcon = true;
            this.btnRequest.AutoSizeRightIcon = true;
            this.btnRequest.BackColor = System.Drawing.Color.Transparent;
            this.btnRequest.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnRequest.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRequest.BackgroundImage")));
            this.btnRequest.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.ButtonText = "Requests";
            this.btnRequest.ButtonTextMarginLeft = 0;
            this.btnRequest.ColorContrastOnClick = 45;
            this.btnRequest.ColorContrastOnHover = 45;
            this.btnRequest.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges35.BottomLeft = true;
            borderEdges35.BottomRight = true;
            borderEdges35.TopLeft = true;
            borderEdges35.TopRight = true;
            this.btnRequest.CustomizableEdges = borderEdges35;
            this.btnRequest.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRequest.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRequest.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnRequest.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnRequest.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnRequest.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRequest.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnRequest.IconLeft = null;
            this.btnRequest.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRequest.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRequest.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRequest.IconMarginLeft = 11;
            this.btnRequest.IconPadding = 6;
            this.btnRequest.IconRight = null;
            this.btnRequest.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRequest.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRequest.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRequest.IconSize = 25;
            this.btnRequest.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnRequest.IdleBorderRadius = 0;
            this.btnRequest.IdleBorderThickness = 0;
            this.btnRequest.IdleFillColor = System.Drawing.Color.Empty;
            this.btnRequest.IdleIconLeftImage = null;
            this.btnRequest.IdleIconRightImage = null;
            this.btnRequest.IndicateFocus = false;
            this.btnRequest.Location = new System.Drawing.Point(3, 513);
            this.btnRequest.Name = "btnRequest";
            this.btnRequest.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnRequest.OnDisabledState.BorderRadius = 1;
            this.btnRequest.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.OnDisabledState.BorderThickness = 1;
            this.btnRequest.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnRequest.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnRequest.OnDisabledState.IconLeftImage = null;
            this.btnRequest.OnDisabledState.IconRightImage = null;
            this.btnRequest.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnRequest.onHoverState.BorderRadius = 1;
            this.btnRequest.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.onHoverState.BorderThickness = 1;
            this.btnRequest.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnRequest.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnRequest.onHoverState.IconLeftImage = null;
            this.btnRequest.onHoverState.IconRightImage = null;
            this.btnRequest.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnRequest.OnIdleState.BorderRadius = 1;
            this.btnRequest.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.OnIdleState.BorderThickness = 1;
            this.btnRequest.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnRequest.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnRequest.OnIdleState.IconLeftImage = null;
            this.btnRequest.OnIdleState.IconRightImage = null;
            this.btnRequest.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnRequest.OnPressedState.BorderRadius = 1;
            this.btnRequest.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.OnPressedState.BorderThickness = 1;
            this.btnRequest.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnRequest.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnRequest.OnPressedState.IconLeftImage = null;
            this.btnRequest.OnPressedState.IconRightImage = null;
            this.btnRequest.Size = new System.Drawing.Size(160, 45);
            this.btnRequest.TabIndex = 21;
            this.btnRequest.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRequest.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRequest.TextMarginLeft = 0;
            this.btnRequest.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRequest.UseDefaultRadiusAndThickness = true;
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.lbUsername);
            this.panel3.Controls.Add(this.lbUserRole);
            this.panel3.Controls.Add(this.btnAvatar);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel3.Location = new System.Drawing.Point(1012, 0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(262, 62);
            this.panel3.TabIndex = 26;
            // 
            // lbUsername
            // 
            this.lbUsername.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbUsername.Location = new System.Drawing.Point(11, 9);
            this.lbUsername.Name = "lbUsername";
            this.lbUsername.Size = new System.Drawing.Size(130, 24);
            this.lbUsername.TabIndex = 27;
            this.lbUsername.Text = "User Name";
            this.lbUsername.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lbUserRole
            // 
            this.lbUserRole.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbUserRole.Location = new System.Drawing.Point(15, 33);
            this.lbUserRole.Name = "lbUserRole";
            this.lbUserRole.Size = new System.Drawing.Size(126, 18);
            this.lbUserRole.TabIndex = 27;
            this.lbUserRole.Text = "User Role";
            this.lbUserRole.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // btnAvatar
            // 
            this.btnAvatar.AllowAnimations = true;
            this.btnAvatar.AllowBorderColorChanges = true;
            this.btnAvatar.AllowMouseEffects = true;
            this.btnAvatar.AnimationSpeed = 200;
            this.btnAvatar.BackColor = System.Drawing.Color.Transparent;
            this.btnAvatar.BackgroundColor = System.Drawing.Color.DodgerBlue;
            this.btnAvatar.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAvatar.BorderRadius = 1;
            this.btnAvatar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.btnAvatar.BorderThickness = 1;
            this.btnAvatar.ColorContrastOnClick = 30;
            this.btnAvatar.ColorContrastOnHover = 30;
            this.btnAvatar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges36.BottomLeft = true;
            borderEdges36.BottomRight = true;
            borderEdges36.TopLeft = true;
            borderEdges36.TopRight = true;
            this.btnAvatar.CustomizableEdges = borderEdges36;
            this.btnAvatar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAvatar.Image = ((System.Drawing.Image)(resources.GetObject("btnAvatar.Image")));
            this.btnAvatar.ImageMargin = new System.Windows.Forms.Padding(0);
            this.btnAvatar.Location = new System.Drawing.Point(147, 11);
            this.btnAvatar.Name = "btnAvatar";
            this.btnAvatar.RoundBorders = true;
            this.btnAvatar.ShowBorders = true;
            this.btnAvatar.Size = new System.Drawing.Size(40, 40);
            this.btnAvatar.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.btnAvatar.TabIndex = 25;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.bunifuLabel2);
            this.panel2.Controls.Add(this.bunifuPictureBox2);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(186, 62);
            this.panel2.TabIndex = 25;
            this.panel2.Paint += new System.Windows.Forms.PaintEventHandler(this.panel2_Paint);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Sylfaen", 20.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(91, 14);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(56, 35);
            this.bunifuLabel2.TabIndex = 0;
            this.bunifuLabel2.Text = "PMS";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = false;
            this.bunifuPictureBox2.BorderRadius = 0;
            this.bunifuPictureBox2.Image = global::PresentationLayer.Properties.Resources.logo_100x115;
            this.bunifuPictureBox2.IsCircle = false;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(20, 7);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(68, 49);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 1;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // panelCenterContent
            // 
            this.panelCenterContent.AutoScroll = true;
            this.panelCenterContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelCenterContent.Location = new System.Drawing.Point(186, 72);
            this.panelCenterContent.Name = "panelCenterContent";
            this.panelCenterContent.Padding = new System.Windows.Forms.Padding(0, 10, 10, 10);
            this.panelCenterContent.Size = new System.Drawing.Size(1088, 615);
            this.panelCenterContent.TabIndex = 29;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.panel3);
            this.panel1.Controls.Add(this.panel2);
            this.panel1.Controls.Add(this.bunifuSeparator2);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1274, 72);
            this.panel1.TabIndex = 27;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(0, 62);
            this.bunifuSeparator2.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(1274, 10);
            this.bunifuSeparator2.TabIndex = 19;
            // 
            // FormAdminHome
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1274, 687);
            this.Controls.Add(this.panelCenterContent);
            this.Controls.Add(this.panelLeft);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.bunifuCircleProgress1);
            this.DoubleBuffered = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "FormAdminHome";
            this.Text = "Manager Dashboard";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.FormAdminHome_FormClosed);
            this.panelLeft.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuCircleProgress bunifuCircleProgress1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCreateTask;
        private System.Windows.Forms.FlowLayoutPanel panelLeft;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProject;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDepartment;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProjectPriority;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProjectStatus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUsers;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTask;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTaskPriority;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTaskStatus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUserRole;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRequest;
        private System.Windows.Forms.Panel panel3;
        private Bunifu.Framework.UI.BunifuCustomLabel lbUsername;
        private Bunifu.Framework.UI.BunifuCustomLabel lbUserRole;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnAvatar;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private System.Windows.Forms.Panel panelCenterContent;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProjectMemeber;
    }
}