namespace PresentationLayer.CustomControls
{
    partial class ctrlCreateUser
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ctrlCreateUser));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tbFirstname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbLastname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pbAvatar = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btCreate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cbDepartment = new System.Windows.Forms.ComboBox();
            this.cbIsActive = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.bunifuLabel12 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cbRole = new System.Windows.Forms.ComboBox();
            this.bunifuLabel13 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel14 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel15 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.pbAvatar)).BeginInit();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tbFirstname
            // 
            this.tbFirstname.AcceptsReturn = false;
            this.tbFirstname.AcceptsTab = false;
            this.tbFirstname.AnimationSpeed = 200;
            this.tbFirstname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbFirstname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbFirstname.AutoSizeHeight = true;
            this.tbFirstname.BackColor = System.Drawing.Color.Transparent;
            this.tbFirstname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbFirstname.BackgroundImage")));
            this.tbFirstname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbFirstname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbFirstname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbFirstname.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbFirstname.BorderRadius = 35;
            this.tbFirstname.BorderThickness = 1;
            this.tbFirstname.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbFirstname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbFirstname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbFirstname.DefaultText = "";
            this.tbFirstname.FillColor = System.Drawing.Color.White;
            this.tbFirstname.HideSelection = true;
            this.tbFirstname.IconLeft = null;
            this.tbFirstname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.IconPadding = 10;
            this.tbFirstname.IconRight = null;
            this.tbFirstname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.Lines = new string[0];
            this.tbFirstname.Location = new System.Drawing.Point(6, 146);
            this.tbFirstname.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbFirstname.MaxLength = 32767;
            this.tbFirstname.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbFirstname.Modified = false;
            this.tbFirstname.Multiline = false;
            this.tbFirstname.Name = "tbFirstname";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbFirstname.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnIdleState = stateProperties32;
            this.tbFirstname.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbFirstname.PasswordChar = '\0';
            this.tbFirstname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbFirstname.PlaceholderText = "Enter first nane";
            this.tbFirstname.ReadOnly = false;
            this.tbFirstname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbFirstname.SelectedText = "";
            this.tbFirstname.SelectionLength = 0;
            this.tbFirstname.SelectionStart = 0;
            this.tbFirstname.ShortcutsEnabled = true;
            this.tbFirstname.Size = new System.Drawing.Size(284, 42);
            this.tbFirstname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbFirstname.TabIndex = 0;
            this.tbFirstname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbFirstname.TextMarginBottom = 0;
            this.tbFirstname.TextMarginLeft = 3;
            this.tbFirstname.TextMarginTop = 1;
            this.tbFirstname.TextPlaceholder = "Enter first nane";
            this.tbFirstname.UseSystemPasswordChar = false;
            this.tbFirstname.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.AutoSizeHeightOnly = true;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(6, 100);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(160, 38);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "First Name";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.AutoSize = false;
            this.bunifuLabel3.AutoSizeHeightOnly = true;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(302, 100);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(158, 38);
            this.bunifuLabel3.TabIndex = 1;
            this.bunifuLabel3.Text = "Last Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbLastname
            // 
            this.tbLastname.AcceptsReturn = false;
            this.tbLastname.AcceptsTab = false;
            this.tbLastname.AnimationSpeed = 200;
            this.tbLastname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbLastname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbLastname.AutoSizeHeight = true;
            this.tbLastname.BackColor = System.Drawing.Color.Transparent;
            this.tbLastname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbLastname.BackgroundImage")));
            this.tbLastname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbLastname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbLastname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbLastname.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbLastname.BorderRadius = 35;
            this.tbLastname.BorderThickness = 1;
            this.tbLastname.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbLastname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbLastname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbLastname.DefaultText = "";
            this.tbLastname.FillColor = System.Drawing.Color.White;
            this.tbLastname.HideSelection = true;
            this.tbLastname.IconLeft = null;
            this.tbLastname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.IconPadding = 10;
            this.tbLastname.IconRight = null;
            this.tbLastname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.Lines = new string[0];
            this.tbLastname.Location = new System.Drawing.Point(302, 146);
            this.tbLastname.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbLastname.MaxLength = 32767;
            this.tbLastname.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbLastname.Modified = false;
            this.tbLastname.Multiline = false;
            this.tbLastname.Name = "tbLastname";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbLastname.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnIdleState = stateProperties36;
            this.tbLastname.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbLastname.PasswordChar = '\0';
            this.tbLastname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbLastname.PlaceholderText = "Enter last nane";
            this.tbLastname.ReadOnly = false;
            this.tbLastname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbLastname.SelectedText = "";
            this.tbLastname.SelectionLength = 0;
            this.tbLastname.SelectionStart = 0;
            this.tbLastname.ShortcutsEnabled = true;
            this.tbLastname.Size = new System.Drawing.Size(284, 42);
            this.tbLastname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbLastname.TabIndex = 0;
            this.tbLastname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbLastname.TextMarginBottom = 0;
            this.tbLastname.TextMarginLeft = 3;
            this.tbLastname.TextMarginTop = 1;
            this.tbLastname.TextPlaceholder = "Enter last nane";
            this.tbLastname.UseSystemPasswordChar = false;
            this.tbLastname.WordWrap = true;
            // 
            // tbPhone
            // 
            this.tbPhone.AcceptsReturn = false;
            this.tbPhone.AcceptsTab = false;
            this.tbPhone.AnimationSpeed = 200;
            this.tbPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPhone.AutoSizeHeight = true;
            this.tbPhone.BackColor = System.Drawing.Color.Transparent;
            this.tbPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPhone.BackgroundImage")));
            this.tbPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPhone.BorderRadius = 35;
            this.tbPhone.BorderThickness = 1;
            this.tbPhone.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbPhone.DefaultText = "";
            this.tbPhone.FillColor = System.Drawing.Color.White;
            this.tbPhone.HideSelection = true;
            this.tbPhone.IconLeft = null;
            this.tbPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.IconPadding = 10;
            this.tbPhone.IconRight = null;
            this.tbPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.Lines = new string[0];
            this.tbPhone.Location = new System.Drawing.Point(598, 146);
            this.tbPhone.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbPhone.MaxLength = 32767;
            this.tbPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPhone.Modified = false;
            this.tbPhone.Multiline = false;
            this.tbPhone.Name = "tbPhone";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbPhone.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnIdleState = stateProperties40;
            this.tbPhone.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbPhone.PasswordChar = '\0';
            this.tbPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPhone.PlaceholderText = "Enter first nane";
            this.tbPhone.ReadOnly = false;
            this.tbPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPhone.SelectedText = "";
            this.tbPhone.SelectionLength = 0;
            this.tbPhone.SelectionStart = 0;
            this.tbPhone.ShortcutsEnabled = true;
            this.tbPhone.Size = new System.Drawing.Size(284, 42);
            this.tbPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbPhone.TabIndex = 0;
            this.tbPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPhone.TextMarginBottom = 0;
            this.tbPhone.TextMarginLeft = 3;
            this.tbPhone.TextMarginTop = 1;
            this.tbPhone.TextPlaceholder = "Enter first nane";
            this.tbPhone.UseSystemPasswordChar = false;
            this.tbPhone.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.AutoSize = false;
            this.bunifuLabel2.AutoSizeHeightOnly = true;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(598, 558);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(176, 38);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "Create Date";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.AutoSize = false;
            this.bunifuLabel5.AutoSizeHeightOnly = true;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(6, 496);
            this.bunifuLabel5.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(146, 38);
            this.bunifuLabel5.TabIndex = 1;
            this.bunifuLabel5.Text = "Create By";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pbAvatar
            // 
            this.pbAvatar.AllowFocused = false;
            this.pbAvatar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbAvatar.AutoSizeHeight = false;
            this.pbAvatar.BorderRadius = 75;
            this.pbAvatar.Image = ((System.Drawing.Image)(resources.GetObject("pbAvatar.Image")));
            this.pbAvatar.IsCircle = true;
            this.pbAvatar.Location = new System.Drawing.Point(668, 338);
            this.pbAvatar.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.pbAvatar.Name = "pbAvatar";
            this.pbAvatar.Size = new System.Drawing.Size(150, 150);
            this.pbAvatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbAvatar.TabIndex = 4;
            this.pbAvatar.TabStop = false;
            this.pbAvatar.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // btCancel
            // 
            this.btCancel.AllowAnimations = true;
            this.btCancel.AllowMouseEffects = true;
            this.btCancel.AllowToggling = false;
            this.btCancel.AnimationSpeed = 200;
            this.btCancel.AutoGenerateColors = false;
            this.btCancel.AutoRoundBorders = false;
            this.btCancel.AutoSizeLeftIcon = true;
            this.btCancel.AutoSizeRightIcon = true;
            this.btCancel.BackColor = System.Drawing.Color.Transparent;
            this.btCancel.BackColor1 = System.Drawing.Color.Gainsboro;
            this.btCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btCancel.BackgroundImage")));
            this.btCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.ButtonText = "Cancel";
            this.btCancel.ButtonTextMarginLeft = 0;
            this.btCancel.ColorContrastOnClick = 45;
            this.btCancel.ColorContrastOnHover = 45;
            this.btCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btCancel.CustomizableEdges = borderEdges3;
            this.btCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btCancel.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btCancel.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btCancel.IconMarginLeft = 11;
            this.btCancel.IconPadding = 10;
            this.btCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btCancel.IconSize = 25;
            this.btCancel.IdleBorderColor = System.Drawing.Color.Gainsboro;
            this.btCancel.IdleBorderRadius = 40;
            this.btCancel.IdleBorderThickness = 1;
            this.btCancel.IdleFillColor = System.Drawing.Color.Gainsboro;
            this.btCancel.IdleIconLeftImage = null;
            this.btCancel.IdleIconRightImage = null;
            this.btCancel.IndicateFocus = false;
            this.btCancel.Location = new System.Drawing.Point(302, 496);
            this.btCancel.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.btCancel.Name = "btCancel";
            this.btCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCancel.OnDisabledState.BorderRadius = 40;
            this.btCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.OnDisabledState.BorderThickness = 1;
            this.btCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btCancel.OnDisabledState.IconLeftImage = null;
            this.btCancel.OnDisabledState.IconRightImage = null;
            this.btCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btCancel.onHoverState.BorderRadius = 40;
            this.btCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.onHoverState.BorderThickness = 1;
            this.btCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btCancel.onHoverState.IconLeftImage = null;
            this.btCancel.onHoverState.IconRightImage = null;
            this.btCancel.OnIdleState.BorderColor = System.Drawing.Color.Gainsboro;
            this.btCancel.OnIdleState.BorderRadius = 40;
            this.btCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.OnIdleState.BorderThickness = 1;
            this.btCancel.OnIdleState.FillColor = System.Drawing.Color.Gainsboro;
            this.btCancel.OnIdleState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btCancel.OnIdleState.IconLeftImage = null;
            this.btCancel.OnIdleState.IconRightImage = null;
            this.btCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btCancel.OnPressedState.BorderRadius = 40;
            this.btCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.OnPressedState.BorderThickness = 1;
            this.btCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btCancel.OnPressedState.IconLeftImage = null;
            this.btCancel.OnPressedState.IconRightImage = null;
            this.btCancel.Size = new System.Drawing.Size(225, 54);
            this.btCancel.TabIndex = 11;
            this.btCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btCancel.TextMarginLeft = 0;
            this.btCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btCancel.UseDefaultRadiusAndThickness = true;
            // 
            // btCreate
            // 
            this.btCreate.AllowAnimations = true;
            this.btCreate.AllowMouseEffects = true;
            this.btCreate.AllowToggling = false;
            this.btCreate.AnimationSpeed = 200;
            this.btCreate.AutoGenerateColors = false;
            this.btCreate.AutoRoundBorders = false;
            this.btCreate.AutoSizeLeftIcon = true;
            this.btCreate.AutoSizeRightIcon = true;
            this.btCreate.BackColor = System.Drawing.Color.Transparent;
            this.btCreate.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btCreate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btCreate.BackgroundImage")));
            this.btCreate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.ButtonText = "Create";
            this.btCreate.ButtonTextMarginLeft = 0;
            this.btCreate.ColorContrastOnClick = 45;
            this.btCreate.ColorContrastOnHover = 45;
            this.btCreate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btCreate.CustomizableEdges = borderEdges4;
            this.btCreate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btCreate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCreate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btCreate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btCreate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btCreate.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btCreate.ForeColor = System.Drawing.Color.White;
            this.btCreate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btCreate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btCreate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btCreate.IconMarginLeft = 11;
            this.btCreate.IconPadding = 10;
            this.btCreate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btCreate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btCreate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btCreate.IconSize = 25;
            this.btCreate.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btCreate.IdleBorderRadius = 40;
            this.btCreate.IdleBorderThickness = 1;
            this.btCreate.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btCreate.IdleIconLeftImage = null;
            this.btCreate.IdleIconRightImage = null;
            this.btCreate.IndicateFocus = false;
            this.btCreate.Location = new System.Drawing.Point(598, 496);
            this.btCreate.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.btCreate.Name = "btCreate";
            this.btCreate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCreate.OnDisabledState.BorderRadius = 40;
            this.btCreate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.OnDisabledState.BorderThickness = 1;
            this.btCreate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btCreate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btCreate.OnDisabledState.IconLeftImage = null;
            this.btCreate.OnDisabledState.IconRightImage = null;
            this.btCreate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btCreate.onHoverState.BorderRadius = 40;
            this.btCreate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.onHoverState.BorderThickness = 1;
            this.btCreate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btCreate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btCreate.onHoverState.IconLeftImage = null;
            this.btCreate.onHoverState.IconRightImage = null;
            this.btCreate.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btCreate.OnIdleState.BorderRadius = 40;
            this.btCreate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.OnIdleState.BorderThickness = 1;
            this.btCreate.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btCreate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btCreate.OnIdleState.IconLeftImage = null;
            this.btCreate.OnIdleState.IconRightImage = null;
            this.btCreate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btCreate.OnPressedState.BorderRadius = 40;
            this.btCreate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.OnPressedState.BorderThickness = 1;
            this.btCreate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btCreate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btCreate.OnPressedState.IconLeftImage = null;
            this.btCreate.OnPressedState.IconRightImage = null;
            this.btCreate.Size = new System.Drawing.Size(225, 54);
            this.btCreate.TabIndex = 12;
            this.btCreate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btCreate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btCreate.TextMarginLeft = 0;
            this.btCreate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btCreate.UseDefaultRadiusAndThickness = true;
            this.btCreate.Click += new System.EventHandler(this.btCreate_Click);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.AutoSize = false;
            this.bunifuLabel6.AutoSizeHeightOnly = true;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(598, 4);
            this.bunifuLabel6.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(81, 38);
            this.bunifuLabel6.TabIndex = 1;
            this.bunifuLabel6.Text = "Email";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btEmail
            // 
            this.btEmail.AcceptsReturn = false;
            this.btEmail.AcceptsTab = false;
            this.btEmail.AnimationSpeed = 200;
            this.btEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.btEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.btEmail.AutoSizeHeight = true;
            this.btEmail.BackColor = System.Drawing.Color.Transparent;
            this.btEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btEmail.BackgroundImage")));
            this.btEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.btEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.btEmail.BorderRadius = 35;
            this.btEmail.BorderThickness = 1;
            this.btEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.btEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.btEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.btEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.btEmail.DefaultText = "";
            this.btEmail.FillColor = System.Drawing.Color.White;
            this.btEmail.HideSelection = true;
            this.btEmail.IconLeft = null;
            this.btEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.btEmail.IconPadding = 10;
            this.btEmail.IconRight = null;
            this.btEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.btEmail.Lines = new string[0];
            this.btEmail.Location = new System.Drawing.Point(598, 50);
            this.btEmail.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.btEmail.MaxLength = 32767;
            this.btEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.btEmail.Modified = false;
            this.btEmail.Multiline = false;
            this.btEmail.Name = "btEmail";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btEmail.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.btEmail.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btEmail.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btEmail.OnIdleState = stateProperties44;
            this.btEmail.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.btEmail.PasswordChar = '\0';
            this.btEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.btEmail.PlaceholderText = "Enter email";
            this.btEmail.ReadOnly = false;
            this.btEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.btEmail.SelectedText = "";
            this.btEmail.SelectionLength = 0;
            this.btEmail.SelectionStart = 0;
            this.btEmail.ShortcutsEnabled = true;
            this.btEmail.Size = new System.Drawing.Size(284, 42);
            this.btEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.btEmail.TabIndex = 0;
            this.btEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btEmail.TextMarginBottom = 0;
            this.btEmail.TextMarginLeft = 3;
            this.btEmail.TextMarginTop = 1;
            this.btEmail.TextPlaceholder = "Enter email";
            this.btEmail.UseSystemPasswordChar = false;
            this.btEmail.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.AutoSize = false;
            this.bunifuLabel7.AutoSizeHeightOnly = true;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(6, 196);
            this.bunifuLabel7.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(121, 38);
            this.bunifuLabel7.TabIndex = 1;
            this.bunifuLabel7.Text = "Address";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbAddress
            // 
            this.tbAddress.AcceptsReturn = false;
            this.tbAddress.AcceptsTab = false;
            this.tbAddress.AnimationSpeed = 200;
            this.tbAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAddress.AutoSizeHeight = true;
            this.tbAddress.BackColor = System.Drawing.Color.Transparent;
            this.tbAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAddress.BackgroundImage")));
            this.tbAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAddress.BorderRadius = 35;
            this.tbAddress.BorderThickness = 1;
            this.tbAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbAddress.DefaultText = "";
            this.tbAddress.FillColor = System.Drawing.Color.White;
            this.tbAddress.HideSelection = true;
            this.tbAddress.IconLeft = null;
            this.tbAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.IconPadding = 10;
            this.tbAddress.IconRight = null;
            this.tbAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.Lines = new string[0];
            this.tbAddress.Location = new System.Drawing.Point(6, 242);
            this.tbAddress.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbAddress.MaxLength = 32767;
            this.tbAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAddress.Modified = false;
            this.tbAddress.Multiline = false;
            this.tbAddress.Name = "tbAddress";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAddress.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnIdleState = stateProperties48;
            this.tbAddress.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbAddress.PasswordChar = '\0';
            this.tbAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAddress.PlaceholderText = "Enter first nane";
            this.tbAddress.ReadOnly = false;
            this.tbAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAddress.SelectedText = "";
            this.tbAddress.SelectionLength = 0;
            this.tbAddress.SelectionStart = 0;
            this.tbAddress.ShortcutsEnabled = true;
            this.tbAddress.Size = new System.Drawing.Size(284, 42);
            this.tbAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAddress.TabIndex = 0;
            this.tbAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAddress.TextMarginBottom = 0;
            this.tbAddress.TextMarginLeft = 3;
            this.tbAddress.TextMarginTop = 1;
            this.tbAddress.TextPlaceholder = "Enter first nane";
            this.tbAddress.UseSystemPasswordChar = false;
            this.tbAddress.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.AutoSize = false;
            this.bunifuLabel8.AutoSizeHeightOnly = true;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.Location = new System.Drawing.Point(6, 4);
            this.bunifuLabel8.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(151, 38);
            this.bunifuLabel8.TabIndex = 1;
            this.bunifuLabel8.Text = "Username";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbUsername
            // 
            this.tbUsername.AcceptsReturn = false;
            this.tbUsername.AcceptsTab = false;
            this.tbUsername.AnimationSpeed = 200;
            this.tbUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbUsername.AutoSizeHeight = true;
            this.tbUsername.BackColor = System.Drawing.Color.Transparent;
            this.tbUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbUsername.BackgroundImage")));
            this.tbUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbUsername.BorderRadius = 35;
            this.tbUsername.BorderThickness = 1;
            this.tbUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbUsername.DefaultText = "";
            this.tbUsername.FillColor = System.Drawing.Color.White;
            this.tbUsername.HideSelection = true;
            this.tbUsername.IconLeft = null;
            this.tbUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.IconPadding = 10;
            this.tbUsername.IconRight = null;
            this.tbUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.Lines = new string[0];
            this.tbUsername.Location = new System.Drawing.Point(6, 50);
            this.tbUsername.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbUsername.MaxLength = 32767;
            this.tbUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbUsername.Modified = false;
            this.tbUsername.Multiline = false;
            this.tbUsername.Name = "tbUsername";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbUsername.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnIdleState = stateProperties52;
            this.tbUsername.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbUsername.PasswordChar = '\0';
            this.tbUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbUsername.PlaceholderText = "Enter last nane";
            this.tbUsername.ReadOnly = false;
            this.tbUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbUsername.SelectedText = "";
            this.tbUsername.SelectionLength = 0;
            this.tbUsername.SelectionStart = 0;
            this.tbUsername.ShortcutsEnabled = true;
            this.tbUsername.Size = new System.Drawing.Size(284, 42);
            this.tbUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbUsername.TabIndex = 0;
            this.tbUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbUsername.TextMarginBottom = 0;
            this.tbUsername.TextMarginLeft = 3;
            this.tbUsername.TextMarginTop = 1;
            this.tbUsername.TextPlaceholder = "Enter last nane";
            this.tbUsername.UseSystemPasswordChar = false;
            this.tbUsername.WordWrap = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.AutoSize = false;
            this.bunifuLabel9.AutoSizeHeightOnly = true;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel9.Location = new System.Drawing.Point(302, 4);
            this.bunifuLabel9.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(145, 38);
            this.bunifuLabel9.TabIndex = 1;
            this.bunifuLabel9.Text = "Password";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbPassword
            // 
            this.tbPassword.AcceptsReturn = false;
            this.tbPassword.AcceptsTab = false;
            this.tbPassword.AnimationSpeed = 200;
            this.tbPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPassword.AutoSizeHeight = true;
            this.tbPassword.BackColor = System.Drawing.Color.Transparent;
            this.tbPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPassword.BackgroundImage")));
            this.tbPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPassword.BorderRadius = 35;
            this.tbPassword.BorderThickness = 1;
            this.tbPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbPassword.DefaultText = "";
            this.tbPassword.FillColor = System.Drawing.Color.White;
            this.tbPassword.HideSelection = true;
            this.tbPassword.IconLeft = null;
            this.tbPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.IconPadding = 10;
            this.tbPassword.IconRight = null;
            this.tbPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.Lines = new string[0];
            this.tbPassword.Location = new System.Drawing.Point(302, 50);
            this.tbPassword.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbPassword.MaxLength = 32767;
            this.tbPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPassword.Modified = false;
            this.tbPassword.Multiline = false;
            this.tbPassword.Name = "tbPassword";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbPassword.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnIdleState = stateProperties56;
            this.tbPassword.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbPassword.PasswordChar = '\0';
            this.tbPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPassword.PlaceholderText = "Enter last nane";
            this.tbPassword.ReadOnly = false;
            this.tbPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPassword.SelectedText = "";
            this.tbPassword.SelectionLength = 0;
            this.tbPassword.SelectionStart = 0;
            this.tbPassword.ShortcutsEnabled = true;
            this.tbPassword.Size = new System.Drawing.Size(284, 42);
            this.tbPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbPassword.TabIndex = 0;
            this.tbPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPassword.TextMarginBottom = 0;
            this.tbPassword.TextMarginLeft = 3;
            this.tbPassword.TextMarginTop = 1;
            this.tbPassword.TextPlaceholder = "Enter last nane";
            this.tbPassword.UseSystemPasswordChar = false;
            this.tbPassword.WordWrap = true;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.AutoSize = false;
            this.bunifuLabel10.AutoSizeHeightOnly = true;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel10.Location = new System.Drawing.Point(598, 196);
            this.bunifuLabel10.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(146, 38);
            this.bunifuLabel10.TabIndex = 1;
            this.bunifuLabel10.Text = "User Role";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cbDepartment
            // 
            this.cbDepartment.FormattingEnabled = true;
            this.cbDepartment.Location = new System.Drawing.Point(302, 242);
            this.cbDepartment.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.cbDepartment.Name = "cbDepartment";
            this.cbDepartment.Size = new System.Drawing.Size(284, 26);
            this.cbDepartment.TabIndex = 14;
            // 
            // cbIsActive
            // 
            this.cbIsActive.AllowBindingControlAnimation = true;
            this.cbIsActive.AllowBindingControlColorChanges = false;
            this.cbIsActive.AllowBindingControlLocation = true;
            this.cbIsActive.AllowCheckBoxAnimation = false;
            this.cbIsActive.AllowCheckmarkAnimation = true;
            this.cbIsActive.AllowOnHoverStates = true;
            this.cbIsActive.AutoCheck = true;
            this.cbIsActive.BackColor = System.Drawing.Color.Transparent;
            this.cbIsActive.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cbIsActive.BackgroundImage")));
            this.cbIsActive.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.cbIsActive.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.cbIsActive.BorderRadius = 12;
            this.cbIsActive.Checked = true;
            this.cbIsActive.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
            this.cbIsActive.Cursor = System.Windows.Forms.Cursors.Default;
            this.cbIsActive.CustomCheckmarkImage = null;
            this.cbIsActive.Location = new System.Drawing.Point(302, 338);
            this.cbIsActive.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.cbIsActive.MinimumSize = new System.Drawing.Size(26, 24);
            this.cbIsActive.Name = "cbIsActive";
            this.cbIsActive.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.cbIsActive.OnCheck.BorderRadius = 12;
            this.cbIsActive.OnCheck.BorderThickness = 2;
            this.cbIsActive.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.cbIsActive.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.cbIsActive.OnCheck.CheckmarkThickness = 2;
            this.cbIsActive.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.cbIsActive.OnDisable.BorderRadius = 12;
            this.cbIsActive.OnDisable.BorderThickness = 2;
            this.cbIsActive.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.cbIsActive.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.cbIsActive.OnDisable.CheckmarkThickness = 2;
            this.cbIsActive.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cbIsActive.OnHoverChecked.BorderRadius = 12;
            this.cbIsActive.OnHoverChecked.BorderThickness = 2;
            this.cbIsActive.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cbIsActive.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.cbIsActive.OnHoverChecked.CheckmarkThickness = 2;
            this.cbIsActive.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cbIsActive.OnHoverUnchecked.BorderRadius = 12;
            this.cbIsActive.OnHoverUnchecked.BorderThickness = 1;
            this.cbIsActive.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.cbIsActive.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.cbIsActive.OnUncheck.BorderRadius = 12;
            this.cbIsActive.OnUncheck.BorderThickness = 1;
            this.cbIsActive.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.cbIsActive.Size = new System.Drawing.Size(30, 30);
            this.cbIsActive.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.cbIsActive.TabIndex = 15;
            this.cbIsActive.ThreeState = false;
            this.cbIsActive.ToolTipText = null;
            this.cbIsActive.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.cbIsActive_CheckedChanged);
            // 
            // bunifuLabel12
            // 
            this.bunifuLabel12.AllowParentOverrides = false;
            this.bunifuLabel12.AutoEllipsis = false;
            this.bunifuLabel12.AutoSize = false;
            this.bunifuLabel12.AutoSizeHeightOnly = true;
            this.bunifuLabel12.CursorType = null;
            this.bunifuLabel12.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel12.Location = new System.Drawing.Point(302, 196);
            this.bunifuLabel12.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel12.Name = "bunifuLabel12";
            this.bunifuLabel12.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel12.Size = new System.Drawing.Size(170, 38);
            this.bunifuLabel12.TabIndex = 1;
            this.bunifuLabel12.Text = "Department";
            this.bunifuLabel12.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel12.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cbRole
            // 
            this.cbRole.FormattingEnabled = true;
            this.cbRole.Location = new System.Drawing.Point(598, 242);
            this.cbRole.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.cbRole.Name = "cbRole";
            this.cbRole.Size = new System.Drawing.Size(284, 26);
            this.cbRole.TabIndex = 14;
            // 
            // bunifuLabel13
            // 
            this.bunifuLabel13.AllowParentOverrides = false;
            this.bunifuLabel13.AutoEllipsis = false;
            this.bunifuLabel13.AutoSize = false;
            this.bunifuLabel13.AutoSizeHeightOnly = true;
            this.bunifuLabel13.CursorType = null;
            this.bunifuLabel13.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel13.Location = new System.Drawing.Point(6, 558);
            this.bunifuLabel13.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel13.Name = "bunifuLabel13";
            this.bunifuLabel13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel13.Size = new System.Drawing.Size(145, 38);
            this.bunifuLabel13.TabIndex = 1;
            this.bunifuLabel13.Text = "Report To";
            this.bunifuLabel13.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel13.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel14
            // 
            this.bunifuLabel14.AllowParentOverrides = false;
            this.bunifuLabel14.AutoEllipsis = false;
            this.bunifuLabel14.AutoSize = false;
            this.bunifuLabel14.AutoSizeHeightOnly = true;
            this.bunifuLabel14.CursorType = null;
            this.bunifuLabel14.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel14.Location = new System.Drawing.Point(302, 558);
            this.bunifuLabel14.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel14.Name = "bunifuLabel14";
            this.bunifuLabel14.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel14.Size = new System.Drawing.Size(93, 38);
            this.bunifuLabel14.TabIndex = 1;
            this.bunifuLabel14.Text = "Salary";
            this.bunifuLabel14.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel14.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel15
            // 
            this.bunifuLabel15.AllowParentOverrides = false;
            this.bunifuLabel15.AutoEllipsis = false;
            this.bunifuLabel15.AutoSize = false;
            this.bunifuLabel15.AutoSizeHeightOnly = true;
            this.bunifuLabel15.CursorType = null;
            this.bunifuLabel15.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel15.Location = new System.Drawing.Point(302, 292);
            this.bunifuLabel15.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel15.Name = "bunifuLabel15";
            this.bunifuLabel15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel15.Size = new System.Drawing.Size(90, 38);
            this.bunifuLabel15.TabIndex = 1;
            this.bunifuLabel15.Text = "Active";
            this.bunifuLabel15.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel15.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel15.Click += new System.EventHandler(this.bunifuLabel15_Click);
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 3;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel3, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel8, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel2, 2, 9);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel5, 0, 8);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel14, 1, 9);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel12, 1, 4);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel13, 0, 9);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel9, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel7, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.tbUsername, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.tbPassword, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.btCancel, 1, 8);
            this.tableLayoutPanel1.Controls.Add(this.btCreate, 2, 8);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel6, 2, 0);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel4, 2, 2);
            this.tableLayoutPanel1.Controls.Add(this.btEmail, 2, 1);
            this.tableLayoutPanel1.Controls.Add(this.cbRole, 2, 5);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel1, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.tbPhone, 2, 3);
            this.tableLayoutPanel1.Controls.Add(this.cbDepartment, 1, 5);
            this.tableLayoutPanel1.Controls.Add(this.tbAddress, 0, 5);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel10, 2, 4);
            this.tableLayoutPanel1.Controls.Add(this.tbFirstname, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.tbLastname, 1, 3);
            this.tableLayoutPanel1.Controls.Add(this.pbAvatar, 2, 7);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel15, 1, 6);
            this.tableLayoutPanel1.Controls.Add(this.cbIsActive, 1, 7);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 10;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.Size = new System.Drawing.Size(895, 637);
            this.tableLayoutPanel1.TabIndex = 16;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.AutoSize = false;
            this.bunifuLabel4.AutoSizeHeightOnly = true;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(598, 100);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(154, 38);
            this.bunifuLabel4.TabIndex = 1;
            this.bunifuLabel4.Text = "Phone No.";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ctrlCreateUser
            // 
            this.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 18F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.tableLayoutPanel1);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Margin = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.Name = "ctrlCreateUser";
            this.Size = new System.Drawing.Size(895, 637);
            this.Load += new System.EventHandler(this.ctrlCreateUser_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pbAvatar)).EndInit();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox tbFirstname;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox tbLastname;
        private Bunifu.UI.WinForms.BunifuTextBox tbPhone;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuPictureBox pbAvatar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btCreate;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox btEmail;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox tbAddress;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox tbUsername;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox tbPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private System.Windows.Forms.ComboBox cbDepartment;
        private Bunifu.UI.WinForms.BunifuCheckBox cbIsActive;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel12;
        private System.Windows.Forms.ComboBox cbRole;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel13;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel14;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel15;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
    }
}
