namespace PresentationLayer
{
    partial class frmAdminHome
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmAdminHome));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuSeparator3 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuShadowPanel7 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnCreateTask = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCreateUser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOverview = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnGant = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTask = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuShadowPanel5 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuSeparator6 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.lbUserRole = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.bunifuSeparator7 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuIconButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.lbUsername = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuShadowPanel6 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.panelCenterContent = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuCircleProgress1 = new Bunifu.UI.WinForms.BunifuCircleProgress();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnListTask = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            this.bunifuShadowPanel7.SuspendLayout();
            this.bunifuShadowPanel5.SuspendLayout();
            this.bunifuShadowPanel6.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Sylfaen", 20.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(97, 5);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(68, 49);
            this.bunifuLabel2.TabIndex = 0;
            this.bunifuLabel2.Text = "PMS";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuSeparator3
            // 
            this.bunifuSeparator3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator3.BackgroundImage")));
            this.bunifuSeparator3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator3.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator3.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuSeparator3.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator3.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator3.LineThickness = 1;
            this.bunifuSeparator3.Location = new System.Drawing.Point(203, 0);
            this.bunifuSeparator3.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuSeparator3.Name = "bunifuSeparator3";
            this.bunifuSeparator3.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.bunifuSeparator3.Size = new System.Drawing.Size(10, 53);
            this.bunifuSeparator3.TabIndex = 20;
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = false;
            this.bunifuPictureBox2.BorderRadius = 0;
            this.bunifuPictureBox2.Image = global::PresentationLayer.Properties.Resources.logo_100x115;
            this.bunifuPictureBox2.IsCircle = false;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(37, 5);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(68, 49);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 1;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // bunifuShadowPanel7
            // 
            this.bunifuShadowPanel7.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel7.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel7.BorderRadius = 0;
            this.bunifuShadowPanel7.BorderThickness = 0;
            this.bunifuShadowPanel7.Controls.Add(this.btnListTask);
            this.bunifuShadowPanel7.Controls.Add(this.btnCreateTask);
            this.bunifuShadowPanel7.Controls.Add(this.btnHome);
            this.bunifuShadowPanel7.Controls.Add(this.btnCreateUser);
            this.bunifuShadowPanel7.Controls.Add(this.btnOverview);
            this.bunifuShadowPanel7.Controls.Add(this.bunifuButton2);
            this.bunifuShadowPanel7.Controls.Add(this.btnGant);
            this.bunifuShadowPanel7.Controls.Add(this.bunifuButton1);
            this.bunifuShadowPanel7.Controls.Add(this.btnTask);
            this.bunifuShadowPanel7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuShadowPanel7.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel7.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel7.Location = new System.Drawing.Point(0, 0);
            this.bunifuShadowPanel7.Name = "bunifuShadowPanel7";
            this.bunifuShadowPanel7.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel7.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel7.ShadowColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel7.ShadowDept = 2;
            this.bunifuShadowPanel7.ShadowDepth = 5;
            this.bunifuShadowPanel7.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel7.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel7.Size = new System.Drawing.Size(203, 755);
            this.bunifuShadowPanel7.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel7.TabIndex = 27;
            // 
            // btnCreateTask
            // 
            this.btnCreateTask.AllowAnimations = true;
            this.btnCreateTask.AllowMouseEffects = true;
            this.btnCreateTask.AllowToggling = false;
            this.btnCreateTask.AnimationSpeed = 200;
            this.btnCreateTask.AutoGenerateColors = false;
            this.btnCreateTask.AutoRoundBorders = false;
            this.btnCreateTask.AutoSizeLeftIcon = true;
            this.btnCreateTask.AutoSizeRightIcon = true;
            this.btnCreateTask.BackColor = System.Drawing.Color.Transparent;
            this.btnCreateTask.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCreateTask.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCreateTask.BackgroundImage")));
            this.btnCreateTask.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateTask.ButtonText = "Create Task";
            this.btnCreateTask.ButtonTextMarginLeft = 0;
            this.btnCreateTask.ColorContrastOnClick = 45;
            this.btnCreateTask.ColorContrastOnHover = 45;
            this.btnCreateTask.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCreateTask.CustomizableEdges = borderEdges2;
            this.btnCreateTask.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCreateTask.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCreateTask.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCreateTask.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCreateTask.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCreateTask.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCreateTask.ForeColor = System.Drawing.Color.White;
            this.btnCreateTask.IconLeft = null;
            this.btnCreateTask.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCreateTask.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCreateTask.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCreateTask.IconMarginLeft = 11;
            this.btnCreateTask.IconPadding = 10;
            this.btnCreateTask.IconRight = null;
            this.btnCreateTask.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCreateTask.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCreateTask.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCreateTask.IconSize = 25;
            this.btnCreateTask.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCreateTask.IdleBorderRadius = 0;
            this.btnCreateTask.IdleBorderThickness = 0;
            this.btnCreateTask.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCreateTask.IdleIconLeftImage = null;
            this.btnCreateTask.IdleIconRightImage = null;
            this.btnCreateTask.IndicateFocus = false;
            this.btnCreateTask.Location = new System.Drawing.Point(18, 490);
            this.btnCreateTask.Name = "btnCreateTask";
            this.btnCreateTask.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCreateTask.OnDisabledState.BorderRadius = 1;
            this.btnCreateTask.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateTask.OnDisabledState.BorderThickness = 1;
            this.btnCreateTask.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCreateTask.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCreateTask.OnDisabledState.IconLeftImage = null;
            this.btnCreateTask.OnDisabledState.IconRightImage = null;
            this.btnCreateTask.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCreateTask.onHoverState.BorderRadius = 1;
            this.btnCreateTask.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateTask.onHoverState.BorderThickness = 1;
            this.btnCreateTask.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCreateTask.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCreateTask.onHoverState.IconLeftImage = null;
            this.btnCreateTask.onHoverState.IconRightImage = null;
            this.btnCreateTask.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCreateTask.OnIdleState.BorderRadius = 1;
            this.btnCreateTask.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateTask.OnIdleState.BorderThickness = 1;
            this.btnCreateTask.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCreateTask.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCreateTask.OnIdleState.IconLeftImage = null;
            this.btnCreateTask.OnIdleState.IconRightImage = null;
            this.btnCreateTask.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCreateTask.OnPressedState.BorderRadius = 1;
            this.btnCreateTask.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateTask.OnPressedState.BorderThickness = 1;
            this.btnCreateTask.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCreateTask.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCreateTask.OnPressedState.IconLeftImage = null;
            this.btnCreateTask.OnPressedState.IconRightImage = null;
            this.btnCreateTask.Size = new System.Drawing.Size(150, 39);
            this.btnCreateTask.TabIndex = 0;
            this.btnCreateTask.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCreateTask.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCreateTask.TextMarginLeft = 0;
            this.btnCreateTask.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCreateTask.UseDefaultRadiusAndThickness = true;
            this.btnCreateTask.Click += new System.EventHandler(this.btnCreateTask_Click);
            // 
            // btnHome
            // 
            this.btnHome.AllowAnimations = true;
            this.btnHome.AllowMouseEffects = true;
            this.btnHome.AllowToggling = false;
            this.btnHome.AnimationSpeed = 200;
            this.btnHome.AutoGenerateColors = false;
            this.btnHome.AutoRoundBorders = false;
            this.btnHome.AutoSizeLeftIcon = true;
            this.btnHome.AutoSizeRightIcon = true;
            this.btnHome.BackColor = System.Drawing.Color.Transparent;
            this.btnHome.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHome.BackgroundImage")));
            this.btnHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.ButtonText = "Home";
            this.btnHome.ButtonTextMarginLeft = 0;
            this.btnHome.ColorContrastOnClick = 45;
            this.btnHome.ColorContrastOnHover = 45;
            this.btnHome.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnHome.CustomizableEdges = borderEdges3;
            this.btnHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHome.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnHome.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHome.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHome.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnHome.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnHome.IconLeft")));
            this.btnHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHome.IconMarginLeft = 11;
            this.btnHome.IconPadding = 6;
            this.btnHome.IconRight = null;
            this.btnHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHome.IconSize = 10;
            this.btnHome.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnHome.IdleBorderRadius = 0;
            this.btnHome.IdleBorderThickness = 0;
            this.btnHome.IdleFillColor = System.Drawing.Color.Empty;
            this.btnHome.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnHome.IdleIconLeftImage")));
            this.btnHome.IdleIconRightImage = null;
            this.btnHome.IndicateFocus = false;
            this.btnHome.Location = new System.Drawing.Point(0, 33);
            this.btnHome.Name = "btnHome";
            this.btnHome.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnHome.OnDisabledState.BorderRadius = 1;
            this.btnHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnDisabledState.BorderThickness = 1;
            this.btnHome.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnHome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnHome.OnDisabledState.IconLeftImage = null;
            this.btnHome.OnDisabledState.IconRightImage = null;
            this.btnHome.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnHome.onHoverState.BorderRadius = 1;
            this.btnHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.onHoverState.BorderThickness = 1;
            this.btnHome.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnHome.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnHome.onHoverState.IconLeftImage = null;
            this.btnHome.onHoverState.IconRightImage = null;
            this.btnHome.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnHome.OnIdleState.BorderRadius = 1;
            this.btnHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnIdleState.BorderThickness = 1;
            this.btnHome.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnHome.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnHome.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnHome.OnIdleState.IconLeftImage")));
            this.btnHome.OnIdleState.IconRightImage = null;
            this.btnHome.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnHome.OnPressedState.BorderRadius = 1;
            this.btnHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnPressedState.BorderThickness = 1;
            this.btnHome.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnHome.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnHome.OnPressedState.IconLeftImage = null;
            this.btnHome.OnPressedState.IconRightImage = null;
            this.btnHome.Size = new System.Drawing.Size(165, 45);
            this.btnHome.TabIndex = 21;
            this.btnHome.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHome.TextMarginLeft = 0;
            this.btnHome.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHome.UseDefaultRadiusAndThickness = true;
            // 
            // btnCreateUser
            // 
            this.btnCreateUser.AllowAnimations = true;
            this.btnCreateUser.AllowMouseEffects = true;
            this.btnCreateUser.AllowToggling = false;
            this.btnCreateUser.AnimationSpeed = 200;
            this.btnCreateUser.AutoGenerateColors = false;
            this.btnCreateUser.AutoRoundBorders = false;
            this.btnCreateUser.AutoSizeLeftIcon = true;
            this.btnCreateUser.AutoSizeRightIcon = true;
            this.btnCreateUser.BackColor = System.Drawing.Color.Transparent;
            this.btnCreateUser.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCreateUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCreateUser.BackgroundImage")));
            this.btnCreateUser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateUser.ButtonText = "Create User";
            this.btnCreateUser.ButtonTextMarginLeft = 0;
            this.btnCreateUser.ColorContrastOnClick = 45;
            this.btnCreateUser.ColorContrastOnHover = 45;
            this.btnCreateUser.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnCreateUser.CustomizableEdges = borderEdges4;
            this.btnCreateUser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCreateUser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCreateUser.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCreateUser.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCreateUser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCreateUser.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCreateUser.ForeColor = System.Drawing.Color.White;
            this.btnCreateUser.IconLeft = null;
            this.btnCreateUser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCreateUser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCreateUser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCreateUser.IconMarginLeft = 11;
            this.btnCreateUser.IconPadding = 10;
            this.btnCreateUser.IconRight = null;
            this.btnCreateUser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCreateUser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCreateUser.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCreateUser.IconSize = 25;
            this.btnCreateUser.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCreateUser.IdleBorderRadius = 0;
            this.btnCreateUser.IdleBorderThickness = 0;
            this.btnCreateUser.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCreateUser.IdleIconLeftImage = null;
            this.btnCreateUser.IdleIconRightImage = null;
            this.btnCreateUser.IndicateFocus = false;
            this.btnCreateUser.Location = new System.Drawing.Point(18, 429);
            this.btnCreateUser.Name = "btnCreateUser";
            this.btnCreateUser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCreateUser.OnDisabledState.BorderRadius = 1;
            this.btnCreateUser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateUser.OnDisabledState.BorderThickness = 1;
            this.btnCreateUser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCreateUser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCreateUser.OnDisabledState.IconLeftImage = null;
            this.btnCreateUser.OnDisabledState.IconRightImage = null;
            this.btnCreateUser.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCreateUser.onHoverState.BorderRadius = 1;
            this.btnCreateUser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateUser.onHoverState.BorderThickness = 1;
            this.btnCreateUser.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCreateUser.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCreateUser.onHoverState.IconLeftImage = null;
            this.btnCreateUser.onHoverState.IconRightImage = null;
            this.btnCreateUser.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCreateUser.OnIdleState.BorderRadius = 1;
            this.btnCreateUser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateUser.OnIdleState.BorderThickness = 1;
            this.btnCreateUser.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCreateUser.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCreateUser.OnIdleState.IconLeftImage = null;
            this.btnCreateUser.OnIdleState.IconRightImage = null;
            this.btnCreateUser.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCreateUser.OnPressedState.BorderRadius = 1;
            this.btnCreateUser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCreateUser.OnPressedState.BorderThickness = 1;
            this.btnCreateUser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCreateUser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCreateUser.OnPressedState.IconLeftImage = null;
            this.btnCreateUser.OnPressedState.IconRightImage = null;
            this.btnCreateUser.Size = new System.Drawing.Size(150, 39);
            this.btnCreateUser.TabIndex = 0;
            this.btnCreateUser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCreateUser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCreateUser.TextMarginLeft = 0;
            this.btnCreateUser.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCreateUser.UseDefaultRadiusAndThickness = true;
            this.btnCreateUser.Click += new System.EventHandler(this.btnCreateUser_Click);
            // 
            // btnOverview
            // 
            this.btnOverview.AllowAnimations = true;
            this.btnOverview.AllowMouseEffects = true;
            this.btnOverview.AllowToggling = false;
            this.btnOverview.AnimationSpeed = 200;
            this.btnOverview.AutoGenerateColors = false;
            this.btnOverview.AutoRoundBorders = false;
            this.btnOverview.AutoSizeLeftIcon = true;
            this.btnOverview.AutoSizeRightIcon = true;
            this.btnOverview.BackColor = System.Drawing.Color.Transparent;
            this.btnOverview.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnOverview.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOverview.BackgroundImage")));
            this.btnOverview.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOverview.ButtonText = "Overview";
            this.btnOverview.ButtonTextMarginLeft = 0;
            this.btnOverview.ColorContrastOnClick = 45;
            this.btnOverview.ColorContrastOnHover = 45;
            this.btnOverview.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnOverview.CustomizableEdges = borderEdges5;
            this.btnOverview.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOverview.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOverview.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnOverview.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnOverview.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOverview.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOverview.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnOverview.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnOverview.IconLeft")));
            this.btnOverview.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOverview.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOverview.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOverview.IconMarginLeft = 11;
            this.btnOverview.IconPadding = 6;
            this.btnOverview.IconRight = null;
            this.btnOverview.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOverview.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOverview.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOverview.IconSize = 25;
            this.btnOverview.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnOverview.IdleBorderRadius = 0;
            this.btnOverview.IdleBorderThickness = 0;
            this.btnOverview.IdleFillColor = System.Drawing.Color.Empty;
            this.btnOverview.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOverview.IdleIconLeftImage")));
            this.btnOverview.IdleIconRightImage = null;
            this.btnOverview.IndicateFocus = false;
            this.btnOverview.Location = new System.Drawing.Point(0, 283);
            this.btnOverview.Name = "btnOverview";
            this.btnOverview.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnOverview.OnDisabledState.BorderRadius = 1;
            this.btnOverview.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOverview.OnDisabledState.BorderThickness = 1;
            this.btnOverview.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnOverview.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnOverview.OnDisabledState.IconLeftImage = null;
            this.btnOverview.OnDisabledState.IconRightImage = null;
            this.btnOverview.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnOverview.onHoverState.BorderRadius = 1;
            this.btnOverview.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOverview.onHoverState.BorderThickness = 1;
            this.btnOverview.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnOverview.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnOverview.onHoverState.IconLeftImage = null;
            this.btnOverview.onHoverState.IconRightImage = null;
            this.btnOverview.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnOverview.OnIdleState.BorderRadius = 1;
            this.btnOverview.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOverview.OnIdleState.BorderThickness = 1;
            this.btnOverview.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnOverview.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnOverview.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOverview.OnIdleState.IconLeftImage")));
            this.btnOverview.OnIdleState.IconRightImage = null;
            this.btnOverview.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnOverview.OnPressedState.BorderRadius = 1;
            this.btnOverview.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOverview.OnPressedState.BorderThickness = 1;
            this.btnOverview.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnOverview.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnOverview.OnPressedState.IconLeftImage = null;
            this.btnOverview.OnPressedState.IconRightImage = null;
            this.btnOverview.Size = new System.Drawing.Size(165, 45);
            this.btnOverview.TabIndex = 21;
            this.btnOverview.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOverview.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOverview.TextMarginLeft = 0;
            this.btnOverview.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOverview.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Create Project";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges6;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeft = null;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = null;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 0;
            this.bunifuButton2.IdleBorderThickness = 0;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(18, 373);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton2.TabIndex = 0;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // btnGant
            // 
            this.btnGant.AllowAnimations = true;
            this.btnGant.AllowMouseEffects = true;
            this.btnGant.AllowToggling = false;
            this.btnGant.AnimationSpeed = 200;
            this.btnGant.AutoGenerateColors = false;
            this.btnGant.AutoRoundBorders = false;
            this.btnGant.AutoSizeLeftIcon = true;
            this.btnGant.AutoSizeRightIcon = true;
            this.btnGant.BackColor = System.Drawing.Color.Transparent;
            this.btnGant.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnGant.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGant.BackgroundImage")));
            this.btnGant.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGant.ButtonText = "Gant";
            this.btnGant.ButtonTextMarginLeft = 0;
            this.btnGant.ColorContrastOnClick = 45;
            this.btnGant.ColorContrastOnHover = 45;
            this.btnGant.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnGant.CustomizableEdges = borderEdges7;
            this.btnGant.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGant.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGant.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnGant.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnGant.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGant.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGant.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnGant.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnGant.IconLeft")));
            this.btnGant.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGant.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGant.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGant.IconMarginLeft = 11;
            this.btnGant.IconPadding = 6;
            this.btnGant.IconRight = null;
            this.btnGant.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGant.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGant.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGant.IconSize = 25;
            this.btnGant.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnGant.IdleBorderRadius = 0;
            this.btnGant.IdleBorderThickness = 0;
            this.btnGant.IdleFillColor = System.Drawing.Color.Empty;
            this.btnGant.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnGant.IdleIconLeftImage")));
            this.btnGant.IdleIconRightImage = null;
            this.btnGant.IndicateFocus = false;
            this.btnGant.Location = new System.Drawing.Point(0, 220);
            this.btnGant.Name = "btnGant";
            this.btnGant.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnGant.OnDisabledState.BorderRadius = 1;
            this.btnGant.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGant.OnDisabledState.BorderThickness = 1;
            this.btnGant.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnGant.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnGant.OnDisabledState.IconLeftImage = null;
            this.btnGant.OnDisabledState.IconRightImage = null;
            this.btnGant.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnGant.onHoverState.BorderRadius = 1;
            this.btnGant.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGant.onHoverState.BorderThickness = 1;
            this.btnGant.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnGant.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGant.onHoverState.IconLeftImage = null;
            this.btnGant.onHoverState.IconRightImage = null;
            this.btnGant.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnGant.OnIdleState.BorderRadius = 1;
            this.btnGant.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGant.OnIdleState.BorderThickness = 1;
            this.btnGant.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnGant.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnGant.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnGant.OnIdleState.IconLeftImage")));
            this.btnGant.OnIdleState.IconRightImage = null;
            this.btnGant.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnGant.OnPressedState.BorderRadius = 1;
            this.btnGant.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGant.OnPressedState.BorderThickness = 1;
            this.btnGant.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnGant.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnGant.OnPressedState.IconLeftImage = null;
            this.btnGant.OnPressedState.IconRightImage = null;
            this.btnGant.Size = new System.Drawing.Size(165, 45);
            this.btnGant.TabIndex = 21;
            this.btnGant.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGant.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGant.TextMarginLeft = 0;
            this.btnGant.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGant.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Project";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges8;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.bunifuButton1.IconLeft = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IconLeft")));
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 6;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IdleIconLeftImage")));
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(3, 97);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.bunifuButton1.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(165, 45);
            this.bunifuButton1.TabIndex = 21;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // btnTask
            // 
            this.btnTask.AllowAnimations = true;
            this.btnTask.AllowMouseEffects = true;
            this.btnTask.AllowToggling = false;
            this.btnTask.AnimationSpeed = 200;
            this.btnTask.AutoGenerateColors = false;
            this.btnTask.AutoRoundBorders = false;
            this.btnTask.AutoSizeLeftIcon = true;
            this.btnTask.AutoSizeRightIcon = true;
            this.btnTask.BackColor = System.Drawing.Color.Transparent;
            this.btnTask.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnTask.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTask.BackgroundImage")));
            this.btnTask.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.ButtonText = "Task";
            this.btnTask.ButtonTextMarginLeft = 0;
            this.btnTask.ColorContrastOnClick = 45;
            this.btnTask.ColorContrastOnHover = 45;
            this.btnTask.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnTask.CustomizableEdges = borderEdges9;
            this.btnTask.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTask.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTask.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnTask.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnTask.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTask.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTask.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTask.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnTask.IconLeft")));
            this.btnTask.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTask.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTask.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTask.IconMarginLeft = 11;
            this.btnTask.IconPadding = 6;
            this.btnTask.IconRight = null;
            this.btnTask.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTask.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTask.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTask.IconSize = 25;
            this.btnTask.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnTask.IdleBorderRadius = 0;
            this.btnTask.IdleBorderThickness = 0;
            this.btnTask.IdleFillColor = System.Drawing.Color.Empty;
            this.btnTask.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnTask.IdleIconLeftImage")));
            this.btnTask.IdleIconRightImage = null;
            this.btnTask.IndicateFocus = false;
            this.btnTask.Location = new System.Drawing.Point(0, 157);
            this.btnTask.Name = "btnTask";
            this.btnTask.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnTask.OnDisabledState.BorderRadius = 1;
            this.btnTask.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.OnDisabledState.BorderThickness = 1;
            this.btnTask.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnTask.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTask.OnDisabledState.IconLeftImage = null;
            this.btnTask.OnDisabledState.IconRightImage = null;
            this.btnTask.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnTask.onHoverState.BorderRadius = 1;
            this.btnTask.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.onHoverState.BorderThickness = 1;
            this.btnTask.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnTask.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnTask.onHoverState.IconLeftImage = null;
            this.btnTask.onHoverState.IconRightImage = null;
            this.btnTask.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnTask.OnIdleState.BorderRadius = 1;
            this.btnTask.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.OnIdleState.BorderThickness = 1;
            this.btnTask.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnTask.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTask.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnTask.OnIdleState.IconLeftImage")));
            this.btnTask.OnIdleState.IconRightImage = null;
            this.btnTask.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnTask.OnPressedState.BorderRadius = 1;
            this.btnTask.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTask.OnPressedState.BorderThickness = 1;
            this.btnTask.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.btnTask.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(116)))), ((int)(((byte)(134)))));
            this.btnTask.OnPressedState.IconLeftImage = null;
            this.btnTask.OnPressedState.IconRightImage = null;
            this.btnTask.Size = new System.Drawing.Size(165, 45);
            this.btnTask.TabIndex = 21;
            this.btnTask.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTask.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTask.TextMarginLeft = 0;
            this.btnTask.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTask.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuShadowPanel5
            // 
            this.bunifuShadowPanel5.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel5.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel5.BorderRadius = 0;
            this.bunifuShadowPanel5.BorderThickness = 0;
            this.bunifuShadowPanel5.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel5.Controls.Add(this.bunifuSeparator3);
            this.bunifuShadowPanel5.Controls.Add(this.bunifuSeparator6);
            this.bunifuShadowPanel5.Controls.Add(this.bunifuPictureBox2);
            this.bunifuShadowPanel5.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuShadowPanel5.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel5.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel5.Location = new System.Drawing.Point(0, 0);
            this.bunifuShadowPanel5.Name = "bunifuShadowPanel5";
            this.bunifuShadowPanel5.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel5.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel5.ShadowColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel5.ShadowDept = 2;
            this.bunifuShadowPanel5.ShadowDepth = 5;
            this.bunifuShadowPanel5.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel5.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel5.Size = new System.Drawing.Size(213, 63);
            this.bunifuShadowPanel5.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel5.TabIndex = 24;
            // 
            // bunifuSeparator6
            // 
            this.bunifuSeparator6.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator6.BackgroundImage")));
            this.bunifuSeparator6.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator6.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator6.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuSeparator6.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator6.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator6.LineThickness = 1;
            this.bunifuSeparator6.Location = new System.Drawing.Point(0, 53);
            this.bunifuSeparator6.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuSeparator6.Name = "bunifuSeparator6";
            this.bunifuSeparator6.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator6.Size = new System.Drawing.Size(213, 10);
            this.bunifuSeparator6.TabIndex = 19;
            // 
            // lbUserRole
            // 
            this.lbUserRole.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbUserRole.Location = new System.Drawing.Point(7, 33);
            this.lbUserRole.Name = "lbUserRole";
            this.lbUserRole.Size = new System.Drawing.Size(126, 18);
            this.lbUserRole.TabIndex = 27;
            this.lbUserRole.Text = "User Role";
            this.lbUserRole.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // bunifuSeparator7
            // 
            this.bunifuSeparator7.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator7.BackgroundImage")));
            this.bunifuSeparator7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator7.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator7.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuSeparator7.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator7.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator7.LineThickness = 1;
            this.bunifuSeparator7.Location = new System.Drawing.Point(0, 53);
            this.bunifuSeparator7.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuSeparator7.Name = "bunifuSeparator7";
            this.bunifuSeparator7.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator7.Size = new System.Drawing.Size(212, 10);
            this.bunifuSeparator7.TabIndex = 19;
            // 
            // bunifuIconButton1
            // 
            this.bunifuIconButton1.AllowAnimations = true;
            this.bunifuIconButton1.AllowBorderColorChanges = true;
            this.bunifuIconButton1.AllowMouseEffects = true;
            this.bunifuIconButton1.AnimationSpeed = 200;
            this.bunifuIconButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuIconButton1.BackgroundColor = System.Drawing.Color.DodgerBlue;
            this.bunifuIconButton1.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuIconButton1.BorderRadius = 1;
            this.bunifuIconButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.bunifuIconButton1.BorderThickness = 1;
            this.bunifuIconButton1.ColorContrastOnClick = 30;
            this.bunifuIconButton1.ColorContrastOnHover = 30;
            this.bunifuIconButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.bunifuIconButton1.CustomizableEdges = borderEdges10;
            this.bunifuIconButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuIconButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuIconButton1.Image")));
            this.bunifuIconButton1.ImageMargin = new System.Windows.Forms.Padding(0);
            this.bunifuIconButton1.Location = new System.Drawing.Point(144, 9);
            this.bunifuIconButton1.Name = "bunifuIconButton1";
            this.bunifuIconButton1.RoundBorders = true;
            this.bunifuIconButton1.ShowBorders = true;
            this.bunifuIconButton1.Size = new System.Drawing.Size(40, 40);
            this.bunifuIconButton1.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.bunifuIconButton1.TabIndex = 25;
            // 
            // lbUsername
            // 
            this.lbUsername.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbUsername.Location = new System.Drawing.Point(3, 9);
            this.lbUsername.Name = "lbUsername";
            this.lbUsername.Size = new System.Drawing.Size(130, 24);
            this.lbUsername.TabIndex = 27;
            this.lbUsername.Text = "User Name";
            this.lbUsername.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(213, 53);
            this.bunifuSeparator2.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(849, 10);
            this.bunifuSeparator2.TabIndex = 19;
            // 
            // bunifuShadowPanel6
            // 
            this.bunifuShadowPanel6.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel6.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel6.BorderRadius = 0;
            this.bunifuShadowPanel6.BorderThickness = 0;
            this.bunifuShadowPanel6.Controls.Add(this.lbUsername);
            this.bunifuShadowPanel6.Controls.Add(this.lbUserRole);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuSeparator7);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuIconButton1);
            this.bunifuShadowPanel6.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuShadowPanel6.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel6.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel6.Location = new System.Drawing.Point(1062, 0);
            this.bunifuShadowPanel6.Name = "bunifuShadowPanel6";
            this.bunifuShadowPanel6.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel6.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel6.ShadowColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel6.ShadowDept = 2;
            this.bunifuShadowPanel6.ShadowDepth = 5;
            this.bunifuShadowPanel6.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel6.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel6.Size = new System.Drawing.Size(212, 63);
            this.bunifuShadowPanel6.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel6.TabIndex = 24;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Round;
            this.bunifuSeparator1.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(203, 0);
            this.bunifuSeparator1.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.bunifuSeparator1.Size = new System.Drawing.Size(10, 755);
            this.bunifuSeparator1.TabIndex = 18;
            // 
            // panelCenterContent
            // 
            this.panelCenterContent.BackColor = System.Drawing.Color.Transparent;
            this.panelCenterContent.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.panelCenterContent.BorderRadius = 0;
            this.panelCenterContent.BorderThickness = 0;
            this.panelCenterContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelCenterContent.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.panelCenterContent.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.panelCenterContent.Location = new System.Drawing.Point(213, 63);
            this.panelCenterContent.Name = "panelCenterContent";
            this.panelCenterContent.PanelColor = System.Drawing.Color.White;
            this.panelCenterContent.PanelColor2 = System.Drawing.Color.White;
            this.panelCenterContent.ShadowColor = System.Drawing.Color.Transparent;
            this.panelCenterContent.ShadowDept = 2;
            this.panelCenterContent.ShadowDepth = 5;
            this.panelCenterContent.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.panelCenterContent.ShadowTopLeftVisible = false;
            this.panelCenterContent.Size = new System.Drawing.Size(1061, 755);
            this.panelCenterContent.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.panelCenterContent.TabIndex = 29;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 0;
            this.bunifuShadowPanel1.BorderThickness = 0;
            this.bunifuShadowPanel1.Controls.Add(this.bunifuShadowPanel7);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuSeparator1);
            this.bunifuShadowPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(0, 63);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(213, 755);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 27;
            // 
            // bunifuCircleProgress1
            // 
            this.bunifuCircleProgress1.Animated = false;
            this.bunifuCircleProgress1.AnimationInterval = 1;
            this.bunifuCircleProgress1.AnimationSpeed = 1;
            this.bunifuCircleProgress1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuCircleProgress1.CircleMargin = 10;
            this.bunifuCircleProgress1.Font = new System.Drawing.Font("Microsoft Sans Serif", 40F, System.Drawing.FontStyle.Bold);
            this.bunifuCircleProgress1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuCircleProgress1.IsPercentage = false;
            this.bunifuCircleProgress1.LineProgressThickness = 10;
            this.bunifuCircleProgress1.LineThickness = 10;
            this.bunifuCircleProgress1.Location = new System.Drawing.Point(0, 0);
            this.bunifuCircleProgress1.Name = "bunifuCircleProgress1";
            this.bunifuCircleProgress1.ProgressAnimationSpeed = 200;
            this.bunifuCircleProgress1.ProgressBackColor = System.Drawing.Color.Gainsboro;
            this.bunifuCircleProgress1.ProgressColor = System.Drawing.Color.DodgerBlue;
            this.bunifuCircleProgress1.ProgressColor2 = System.Drawing.Color.DodgerBlue;
            this.bunifuCircleProgress1.ProgressEndCap = Bunifu.UI.WinForms.BunifuCircleProgress.CapStyles.Round;
            this.bunifuCircleProgress1.ProgressFillStyle = Bunifu.UI.WinForms.BunifuCircleProgress.FillStyles.Solid;
            this.bunifuCircleProgress1.ProgressStartCap = Bunifu.UI.WinForms.BunifuCircleProgress.CapStyles.Round;
            this.bunifuCircleProgress1.SecondaryFont = new System.Drawing.Font("Microsoft Sans Serif", 16F);
            this.bunifuCircleProgress1.Size = new System.Drawing.Size(8, 8);
            this.bunifuCircleProgress1.SubScriptColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(166)))), ((int)(((byte)(166)))));
            this.bunifuCircleProgress1.SubScriptMargin = new System.Windows.Forms.Padding(5, -20, 0, 0);
            this.bunifuCircleProgress1.SubScriptText = ".00";
            this.bunifuCircleProgress1.SuperScriptColor = System.Drawing.Color.FromArgb(((int)(((byte)(166)))), ((int)(((byte)(166)))), ((int)(((byte)(166)))));
            this.bunifuCircleProgress1.SuperScriptMargin = new System.Windows.Forms.Padding(5, 20, 0, 0);
            this.bunifuCircleProgress1.SuperScriptText = "°C";
            this.bunifuCircleProgress1.TabIndex = 26;
            this.bunifuCircleProgress1.Text = "30";
            this.bunifuCircleProgress1.TextMargin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.bunifuCircleProgress1.Value = 30;
            this.bunifuCircleProgress1.ValueByTransition = 30;
            this.bunifuCircleProgress1.ValueMargin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.BorderRadius = 0;
            this.bunifuShadowPanel2.BorderThickness = 0;
            this.bunifuShadowPanel2.Controls.Add(this.bunifuSeparator2);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuShadowPanel6);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuShadowPanel5);
            this.bunifuShadowPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(0, 0);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 5;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(1274, 63);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 28;
            // 
            // btnListTask
            // 
            this.btnListTask.AllowAnimations = true;
            this.btnListTask.AllowMouseEffects = true;
            this.btnListTask.AllowToggling = false;
            this.btnListTask.AnimationSpeed = 200;
            this.btnListTask.AutoGenerateColors = false;
            this.btnListTask.AutoRoundBorders = false;
            this.btnListTask.AutoSizeLeftIcon = true;
            this.btnListTask.AutoSizeRightIcon = true;
            this.btnListTask.BackColor = System.Drawing.Color.Transparent;
            this.btnListTask.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnListTask.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnListTask.BackgroundImage")));
            this.btnListTask.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnListTask.ButtonText = "List task";
            this.btnListTask.ButtonTextMarginLeft = 0;
            this.btnListTask.ColorContrastOnClick = 45;
            this.btnListTask.ColorContrastOnHover = 45;
            this.btnListTask.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnListTask.CustomizableEdges = borderEdges1;
            this.btnListTask.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnListTask.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnListTask.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnListTask.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnListTask.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnListTask.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnListTask.ForeColor = System.Drawing.Color.White;
            this.btnListTask.IconLeft = null;
            this.btnListTask.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnListTask.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnListTask.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnListTask.IconMarginLeft = 11;
            this.btnListTask.IconPadding = 10;
            this.btnListTask.IconRight = null;
            this.btnListTask.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnListTask.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnListTask.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnListTask.IconSize = 25;
            this.btnListTask.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnListTask.IdleBorderRadius = 0;
            this.btnListTask.IdleBorderThickness = 0;
            this.btnListTask.IdleFillColor = System.Drawing.Color.Empty;
            this.btnListTask.IdleIconLeftImage = null;
            this.btnListTask.IdleIconRightImage = null;
            this.btnListTask.IndicateFocus = false;
            this.btnListTask.Location = new System.Drawing.Point(18, 549);
            this.btnListTask.Name = "btnListTask";
            this.btnListTask.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnListTask.OnDisabledState.BorderRadius = 1;
            this.btnListTask.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnListTask.OnDisabledState.BorderThickness = 1;
            this.btnListTask.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnListTask.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnListTask.OnDisabledState.IconLeftImage = null;
            this.btnListTask.OnDisabledState.IconRightImage = null;
            this.btnListTask.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnListTask.onHoverState.BorderRadius = 1;
            this.btnListTask.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnListTask.onHoverState.BorderThickness = 1;
            this.btnListTask.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnListTask.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnListTask.onHoverState.IconLeftImage = null;
            this.btnListTask.onHoverState.IconRightImage = null;
            this.btnListTask.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnListTask.OnIdleState.BorderRadius = 1;
            this.btnListTask.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnListTask.OnIdleState.BorderThickness = 1;
            this.btnListTask.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnListTask.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnListTask.OnIdleState.IconLeftImage = null;
            this.btnListTask.OnIdleState.IconRightImage = null;
            this.btnListTask.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnListTask.OnPressedState.BorderRadius = 1;
            this.btnListTask.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnListTask.OnPressedState.BorderThickness = 1;
            this.btnListTask.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnListTask.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnListTask.OnPressedState.IconLeftImage = null;
            this.btnListTask.OnPressedState.IconRightImage = null;
            this.btnListTask.Size = new System.Drawing.Size(150, 39);
            this.btnListTask.TabIndex = 0;
            this.btnListTask.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnListTask.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnListTask.TextMarginLeft = 0;
            this.btnListTask.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnListTask.UseDefaultRadiusAndThickness = true;
            this.btnListTask.Click += new System.EventHandler(this.btnListTask_Click);
            // 
            // frmAdminHome
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1274, 818);
            this.Controls.Add(this.panelCenterContent);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Controls.Add(this.bunifuCircleProgress1);
            this.Controls.Add(this.bunifuShadowPanel2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            this.Name = "frmAdminHome";
            this.Text = "frmAdminHome";
            this.Load += new System.EventHandler(this.frmAdminHome_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            this.bunifuShadowPanel7.ResumeLayout(false);
            this.bunifuShadowPanel5.ResumeLayout(false);
            this.bunifuShadowPanel5.PerformLayout();
            this.bunifuShadowPanel6.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator3;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOverview;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGant;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTask;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel5;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator6;
        private Bunifu.Framework.UI.BunifuCustomLabel lbUserRole;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton bunifuIconButton1;
        private Bunifu.Framework.UI.BunifuCustomLabel lbUsername;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel6;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuShadowPanel panelCenterContent;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuCircleProgress bunifuCircleProgress1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCreateUser;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCreateTask;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnListTask;
    }
}