namespace PresentationLayer
{
    partial class frmLogin
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmLogin));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges18 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties81 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties82 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties83 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties84 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties77 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties78 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties79 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties80 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties73 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties74 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties75 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties76 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges17 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.panelSignIn = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnLogin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tbPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnSignUpp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnShowPassword = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.panelSignUp = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnSignUpBack = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tbSignUpPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbSignUpEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbSignUpUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbSignUpFirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbSignUpLastName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnSignUp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuIconButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuPanel2.SuspendLayout();
            this.panelSignIn.SuspendLayout();
            this.panelSignUp.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(175, 251);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(120, 15);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Forgot your password?";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(175, 251);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(120, 15);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Forgot your password?";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.Click += new System.EventHandler(this.bunifuLabel1_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.Image = global::PresentationLayer.Properties.Resources.logo1;
            this.pictureBox1.Location = new System.Drawing.Point(127, 48);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(193, 187);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 4;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.pictureBox1);
            this.bunifuPanel2.Controls.Add(this.panelSignIn);
            this.bunifuPanel2.Controls.Add(this.panelSignUp);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel2.Location = new System.Drawing.Point(906, 0);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(431, 647);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // panelSignIn
            // 
            this.panelSignIn.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelSignIn.BackgroundColor = System.Drawing.Color.White;
            this.panelSignIn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelSignIn.BackgroundImage")));
            this.panelSignIn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelSignIn.BorderColor = System.Drawing.Color.White;
            this.panelSignIn.BorderRadius = 3;
            this.panelSignIn.BorderThickness = 0;
            this.panelSignIn.Controls.Add(this.bunifuLabel4);
            this.panelSignIn.Controls.Add(this.bunifuLabel3);
            this.panelSignIn.Controls.Add(this.btnShowPassword);
            this.panelSignIn.Controls.Add(this.btnSignUpp);
            this.panelSignIn.Controls.Add(this.tbUsername);
            this.panelSignIn.Controls.Add(this.tbPassword);
            this.panelSignIn.Controls.Add(this.btnLogin);
            this.panelSignIn.Location = new System.Drawing.Point(0, 258);
            this.panelSignIn.Name = "panelSignIn";
            this.panelSignIn.ShowBorders = true;
            this.panelSignIn.Size = new System.Drawing.Size(431, 389);
            this.panelSignIn.TabIndex = 5;
            // 
            // btnLogin
            // 
            this.btnLogin.AllowAnimations = true;
            this.btnLogin.AllowMouseEffects = true;
            this.btnLogin.AllowToggling = false;
            this.btnLogin.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnLogin.AnimationSpeed = 200;
            this.btnLogin.AutoGenerateColors = false;
            this.btnLogin.AutoRoundBorders = false;
            this.btnLogin.AutoSizeLeftIcon = true;
            this.btnLogin.AutoSizeRightIcon = true;
            this.btnLogin.BackColor = System.Drawing.Color.Transparent;
            this.btnLogin.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnLogin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogin.BackgroundImage")));
            this.btnLogin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.ButtonText = "Login";
            this.btnLogin.ButtonTextMarginLeft = 0;
            this.btnLogin.ColorContrastOnClick = 45;
            this.btnLogin.ColorContrastOnHover = 45;
            this.btnLogin.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.btnLogin.CustomizableEdges = borderEdges15;
            this.btnLogin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogin.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnLogin.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnLogin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogin.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnLogin.ForeColor = System.Drawing.Color.White;
            this.btnLogin.IconLeft = null;
            this.btnLogin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLogin.IconMarginLeft = 11;
            this.btnLogin.IconPadding = 10;
            this.btnLogin.IconRight = null;
            this.btnLogin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogin.IconSize = 25;
            this.btnLogin.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnLogin.IdleBorderRadius = 0;
            this.btnLogin.IdleBorderThickness = 0;
            this.btnLogin.IdleFillColor = System.Drawing.Color.Empty;
            this.btnLogin.IdleIconLeftImage = null;
            this.btnLogin.IdleIconRightImage = null;
            this.btnLogin.IndicateFocus = false;
            this.btnLogin.Location = new System.Drawing.Point(62, 207);
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogin.OnDisabledState.BorderRadius = 20;
            this.btnLogin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnDisabledState.BorderThickness = 1;
            this.btnLogin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogin.OnDisabledState.IconLeftImage = null;
            this.btnLogin.OnDisabledState.IconRightImage = null;
            this.btnLogin.onHoverState.BorderColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnLogin.onHoverState.BorderRadius = 20;
            this.btnLogin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.onHoverState.BorderThickness = 1;
            this.btnLogin.onHoverState.FillColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnLogin.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogin.onHoverState.IconLeftImage = null;
            this.btnLogin.onHoverState.IconRightImage = null;
            this.btnLogin.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLogin.OnIdleState.BorderRadius = 20;
            this.btnLogin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnIdleState.BorderThickness = 1;
            this.btnLogin.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLogin.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLogin.OnIdleState.IconLeftImage = null;
            this.btnLogin.OnIdleState.IconRightImage = null;
            this.btnLogin.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLogin.OnPressedState.BorderRadius = 20;
            this.btnLogin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnPressedState.BorderThickness = 1;
            this.btnLogin.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLogin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogin.OnPressedState.IconLeftImage = null;
            this.btnLogin.OnPressedState.IconRightImage = null;
            this.btnLogin.Size = new System.Drawing.Size(144, 40);
            this.btnLogin.TabIndex = 1;
            this.btnLogin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogin.TextMarginLeft = 0;
            this.btnLogin.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLogin.UseDefaultRadiusAndThickness = true;
            this.btnLogin.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // tbPassword
            // 
            this.tbPassword.AcceptsReturn = false;
            this.tbPassword.AcceptsTab = false;
            this.tbPassword.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tbPassword.AnimationSpeed = 200;
            this.tbPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPassword.AutoSizeHeight = true;
            this.tbPassword.BackColor = System.Drawing.Color.Transparent;
            this.tbPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPassword.BackgroundImage")));
            this.tbPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPassword.BorderRadius = 20;
            this.tbPassword.BorderThickness = 1;
            this.tbPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbPassword.DefaultText = "";
            this.tbPassword.FillColor = System.Drawing.Color.White;
            this.tbPassword.HideSelection = true;
            this.tbPassword.IconLeft = null;
            this.tbPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.IconPadding = 10;
            this.tbPassword.IconRight = null;
            this.tbPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.Lines = new string[0];
            this.tbPassword.Location = new System.Drawing.Point(50, 141);
            this.tbPassword.MaxLength = 32767;
            this.tbPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPassword.Modified = false;
            this.tbPassword.Multiline = false;
            this.tbPassword.Name = "tbPassword";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbPassword.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnIdleState = stateProperties64;
            this.tbPassword.Padding = new System.Windows.Forms.Padding(3);
            this.tbPassword.PasswordChar = '\0';
            this.tbPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPassword.PlaceholderText = "Enter password...";
            this.tbPassword.ReadOnly = false;
            this.tbPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPassword.SelectedText = "";
            this.tbPassword.SelectionLength = 0;
            this.tbPassword.SelectionStart = 0;
            this.tbPassword.ShortcutsEnabled = true;
            this.tbPassword.Size = new System.Drawing.Size(316, 39);
            this.tbPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbPassword.TabIndex = 0;
            this.tbPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPassword.TextMarginBottom = 0;
            this.tbPassword.TextMarginLeft = 3;
            this.tbPassword.TextMarginTop = 1;
            this.tbPassword.TextPlaceholder = "Enter password...";
            this.tbPassword.UseSystemPasswordChar = false;
            this.tbPassword.WordWrap = true;
            this.tbPassword.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // tbUsername
            // 
            this.tbUsername.AcceptsReturn = false;
            this.tbUsername.AcceptsTab = false;
            this.tbUsername.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tbUsername.AnimationSpeed = 200;
            this.tbUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbUsername.AutoSizeHeight = true;
            this.tbUsername.BackColor = System.Drawing.Color.Transparent;
            this.tbUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbUsername.BackgroundImage")));
            this.tbUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbUsername.BorderRadius = 20;
            this.tbUsername.BorderThickness = 1;
            this.tbUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbUsername.DefaultText = "";
            this.tbUsername.FillColor = System.Drawing.Color.White;
            this.tbUsername.HideSelection = true;
            this.tbUsername.IconLeft = null;
            this.tbUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.IconPadding = 10;
            this.tbUsername.IconRight = null;
            this.tbUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.Lines = new string[0];
            this.tbUsername.Location = new System.Drawing.Point(50, 83);
            this.tbUsername.MaxLength = 32767;
            this.tbUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbUsername.Modified = false;
            this.tbUsername.Multiline = false;
            this.tbUsername.Name = "tbUsername";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbUsername.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnIdleState = stateProperties60;
            this.tbUsername.Padding = new System.Windows.Forms.Padding(3);
            this.tbUsername.PasswordChar = '\0';
            this.tbUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbUsername.PlaceholderText = "Enter username...";
            this.tbUsername.ReadOnly = false;
            this.tbUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbUsername.SelectedText = "";
            this.tbUsername.SelectionLength = 0;
            this.tbUsername.SelectionStart = 0;
            this.tbUsername.ShortcutsEnabled = true;
            this.tbUsername.Size = new System.Drawing.Size(356, 39);
            this.tbUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbUsername.TabIndex = 0;
            this.tbUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbUsername.TextMarginBottom = 0;
            this.tbUsername.TextMarginLeft = 3;
            this.tbUsername.TextMarginTop = 1;
            this.tbUsername.TextPlaceholder = "Enter username...";
            this.tbUsername.UseSystemPasswordChar = false;
            this.tbUsername.WordWrap = true;
            this.tbUsername.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // btnSignUpp
            // 
            this.btnSignUpp.AllowAnimations = true;
            this.btnSignUpp.AllowMouseEffects = true;
            this.btnSignUpp.AllowToggling = false;
            this.btnSignUpp.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSignUpp.AnimationSpeed = 200;
            this.btnSignUpp.AutoGenerateColors = false;
            this.btnSignUpp.AutoRoundBorders = false;
            this.btnSignUpp.AutoSizeLeftIcon = true;
            this.btnSignUpp.AutoSizeRightIcon = true;
            this.btnSignUpp.BackColor = System.Drawing.Color.Transparent;
            this.btnSignUpp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSignUpp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSignUpp.BackgroundImage")));
            this.btnSignUpp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpp.ButtonText = "SignUp";
            this.btnSignUpp.ButtonTextMarginLeft = 0;
            this.btnSignUpp.ColorContrastOnClick = 45;
            this.btnSignUpp.ColorContrastOnHover = 45;
            this.btnSignUpp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnSignUpp.CustomizableEdges = borderEdges14;
            this.btnSignUpp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSignUpp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUpp.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSignUpp.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSignUpp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSignUpp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSignUpp.ForeColor = System.Drawing.Color.White;
            this.btnSignUpp.IconLeft = null;
            this.btnSignUpp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignUpp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUpp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSignUpp.IconMarginLeft = 11;
            this.btnSignUpp.IconPadding = 10;
            this.btnSignUpp.IconRight = null;
            this.btnSignUpp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignUpp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUpp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSignUpp.IconSize = 25;
            this.btnSignUpp.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSignUpp.IdleBorderRadius = 0;
            this.btnSignUpp.IdleBorderThickness = 0;
            this.btnSignUpp.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSignUpp.IdleIconLeftImage = null;
            this.btnSignUpp.IdleIconRightImage = null;
            this.btnSignUpp.IndicateFocus = false;
            this.btnSignUpp.Location = new System.Drawing.Point(259, 207);
            this.btnSignUpp.Name = "btnSignUpp";
            this.btnSignUpp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUpp.OnDisabledState.BorderRadius = 20;
            this.btnSignUpp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpp.OnDisabledState.BorderThickness = 1;
            this.btnSignUpp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignUpp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignUpp.OnDisabledState.IconLeftImage = null;
            this.btnSignUpp.OnDisabledState.IconRightImage = null;
            this.btnSignUpp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSignUpp.onHoverState.BorderRadius = 20;
            this.btnSignUpp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpp.onHoverState.BorderThickness = 1;
            this.btnSignUpp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSignUpp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSignUpp.onHoverState.IconLeftImage = null;
            this.btnSignUpp.onHoverState.IconRightImage = null;
            this.btnSignUpp.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUpp.OnIdleState.BorderRadius = 20;
            this.btnSignUpp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpp.OnIdleState.BorderThickness = 1;
            this.btnSignUpp.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUpp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSignUpp.OnIdleState.IconLeftImage = null;
            this.btnSignUpp.OnIdleState.IconRightImage = null;
            this.btnSignUpp.OnPressedState.BorderColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnSignUpp.OnPressedState.BorderRadius = 20;
            this.btnSignUpp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpp.OnPressedState.BorderThickness = 1;
            this.btnSignUpp.OnPressedState.FillColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnSignUpp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSignUpp.OnPressedState.IconLeftImage = null;
            this.btnSignUpp.OnPressedState.IconRightImage = null;
            this.btnSignUpp.Size = new System.Drawing.Size(144, 40);
            this.btnSignUpp.TabIndex = 1;
            this.btnSignUpp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSignUpp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSignUpp.TextMarginLeft = 0;
            this.btnSignUpp.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSignUpp.UseDefaultRadiusAndThickness = true;
            this.btnSignUpp.Click += new System.EventHandler(this.btnSignUpp_Click);
            // 
            // btnShowPassword
            // 
            this.btnShowPassword.AllowAnimations = true;
            this.btnShowPassword.AllowBorderColorChanges = true;
            this.btnShowPassword.AllowMouseEffects = true;
            this.btnShowPassword.AnimationSpeed = 200;
            this.btnShowPassword.BackColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BackgroundColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BorderColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BorderRadius = 1;
            this.btnShowPassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.btnShowPassword.BorderThickness = 0;
            this.btnShowPassword.ColorContrastOnClick = 30;
            this.btnShowPassword.ColorContrastOnHover = 30;
            this.btnShowPassword.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnShowPassword.CustomizableEdges = borderEdges13;
            this.btnShowPassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnShowPassword.Image = global::PresentationLayer.Properties.Resources.eye;
            this.btnShowPassword.ImageMargin = new System.Windows.Forms.Padding(0);
            this.btnShowPassword.Location = new System.Drawing.Point(372, 143);
            this.btnShowPassword.Name = "btnShowPassword";
            this.btnShowPassword.RoundBorders = true;
            this.btnShowPassword.ShowBorders = true;
            this.btnShowPassword.Size = new System.Drawing.Size(35, 35);
            this.btnShowPassword.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.btnShowPassword.TabIndex = 3;
            this.btnShowPassword.Click += new System.EventHandler(this.btnShowPassword_Click);
            // 
            // panelSignUp
            // 
            this.panelSignUp.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelSignUp.BackgroundColor = System.Drawing.Color.White;
            this.panelSignUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelSignUp.BackgroundImage")));
            this.panelSignUp.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelSignUp.BorderColor = System.Drawing.Color.White;
            this.panelSignUp.BorderRadius = 3;
            this.panelSignUp.BorderThickness = 0;
            this.panelSignUp.Controls.Add(this.bunifuLabel5);
            this.panelSignUp.Controls.Add(this.bunifuIconButton1);
            this.panelSignUp.Controls.Add(this.btnSignUp);
            this.panelSignUp.Controls.Add(this.tbSignUpLastName);
            this.panelSignUp.Controls.Add(this.tbSignUpFirstName);
            this.panelSignUp.Controls.Add(this.tbSignUpUsername);
            this.panelSignUp.Controls.Add(this.tbSignUpEmail);
            this.panelSignUp.Controls.Add(this.tbSignUpPassword);
            this.panelSignUp.Controls.Add(this.btnSignUpBack);
            this.panelSignUp.Location = new System.Drawing.Point(0, 255);
            this.panelSignUp.Name = "panelSignUp";
            this.panelSignUp.ShowBorders = true;
            this.panelSignUp.Size = new System.Drawing.Size(431, 389);
            this.panelSignUp.TabIndex = 7;
            // 
            // btnSignUpBack
            // 
            this.btnSignUpBack.AllowAnimations = true;
            this.btnSignUpBack.AllowMouseEffects = true;
            this.btnSignUpBack.AllowToggling = false;
            this.btnSignUpBack.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSignUpBack.AnimationSpeed = 200;
            this.btnSignUpBack.AutoGenerateColors = false;
            this.btnSignUpBack.AutoRoundBorders = false;
            this.btnSignUpBack.AutoSizeLeftIcon = true;
            this.btnSignUpBack.AutoSizeRightIcon = true;
            this.btnSignUpBack.BackColor = System.Drawing.Color.Transparent;
            this.btnSignUpBack.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSignUpBack.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSignUpBack.BackgroundImage")));
            this.btnSignUpBack.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.ButtonText = "<";
            this.btnSignUpBack.ButtonTextMarginLeft = 0;
            this.btnSignUpBack.ColorContrastOnClick = 45;
            this.btnSignUpBack.ColorContrastOnHover = 45;
            this.btnSignUpBack.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges18.BottomLeft = true;
            borderEdges18.BottomRight = true;
            borderEdges18.TopLeft = true;
            borderEdges18.TopRight = true;
            this.btnSignUpBack.CustomizableEdges = borderEdges18;
            this.btnSignUpBack.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSignUpBack.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUpBack.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSignUpBack.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSignUpBack.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSignUpBack.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSignUpBack.ForeColor = System.Drawing.Color.White;
            this.btnSignUpBack.IconLeft = null;
            this.btnSignUpBack.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignUpBack.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUpBack.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSignUpBack.IconMarginLeft = 11;
            this.btnSignUpBack.IconPadding = 10;
            this.btnSignUpBack.IconRight = null;
            this.btnSignUpBack.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignUpBack.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUpBack.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSignUpBack.IconSize = 25;
            this.btnSignUpBack.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSignUpBack.IdleBorderRadius = 0;
            this.btnSignUpBack.IdleBorderThickness = 0;
            this.btnSignUpBack.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSignUpBack.IdleIconLeftImage = null;
            this.btnSignUpBack.IdleIconRightImage = null;
            this.btnSignUpBack.IndicateFocus = false;
            this.btnSignUpBack.Location = new System.Drawing.Point(12, 12);
            this.btnSignUpBack.Name = "btnSignUpBack";
            this.btnSignUpBack.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUpBack.OnDisabledState.BorderRadius = 20;
            this.btnSignUpBack.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.OnDisabledState.BorderThickness = 1;
            this.btnSignUpBack.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignUpBack.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignUpBack.OnDisabledState.IconLeftImage = null;
            this.btnSignUpBack.OnDisabledState.IconRightImage = null;
            this.btnSignUpBack.onHoverState.BorderColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnSignUpBack.onHoverState.BorderRadius = 20;
            this.btnSignUpBack.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.onHoverState.BorderThickness = 1;
            this.btnSignUpBack.onHoverState.FillColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnSignUpBack.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSignUpBack.onHoverState.IconLeftImage = null;
            this.btnSignUpBack.onHoverState.IconRightImage = null;
            this.btnSignUpBack.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUpBack.OnIdleState.BorderRadius = 20;
            this.btnSignUpBack.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.OnIdleState.BorderThickness = 1;
            this.btnSignUpBack.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUpBack.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSignUpBack.OnIdleState.IconLeftImage = null;
            this.btnSignUpBack.OnIdleState.IconRightImage = null;
            this.btnSignUpBack.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUpBack.OnPressedState.BorderRadius = 20;
            this.btnSignUpBack.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.OnPressedState.BorderThickness = 1;
            this.btnSignUpBack.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUpBack.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSignUpBack.OnPressedState.IconLeftImage = null;
            this.btnSignUpBack.OnPressedState.IconRightImage = null;
            this.btnSignUpBack.Size = new System.Drawing.Size(47, 27);
            this.btnSignUpBack.TabIndex = 1;
            this.btnSignUpBack.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSignUpBack.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSignUpBack.TextMarginLeft = 0;
            this.btnSignUpBack.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSignUpBack.UseDefaultRadiusAndThickness = true;
            this.btnSignUpBack.Click += new System.EventHandler(this.btnSignUpBack_Click);
            // 
            // tbSignUpPassword
            // 
            this.tbSignUpPassword.AcceptsReturn = false;
            this.tbSignUpPassword.AcceptsTab = false;
            this.tbSignUpPassword.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tbSignUpPassword.AnimationSpeed = 200;
            this.tbSignUpPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpPassword.AutoSizeHeight = true;
            this.tbSignUpPassword.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpPassword.BackgroundImage")));
            this.tbSignUpPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSignUpPassword.BorderRadius = 20;
            this.tbSignUpPassword.BorderThickness = 1;
            this.tbSignUpPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSignUpPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpPassword.DefaultText = "";
            this.tbSignUpPassword.FillColor = System.Drawing.Color.White;
            this.tbSignUpPassword.HideSelection = true;
            this.tbSignUpPassword.IconLeft = null;
            this.tbSignUpPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpPassword.IconPadding = 10;
            this.tbSignUpPassword.IconRight = null;
            this.tbSignUpPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpPassword.Lines = new string[0];
            this.tbSignUpPassword.Location = new System.Drawing.Point(52, 200);
            this.tbSignUpPassword.MaxLength = 32767;
            this.tbSignUpPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpPassword.Modified = false;
            this.tbSignUpPassword.Multiline = false;
            this.tbSignUpPassword.Name = "tbSignUpPassword";
            stateProperties81.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties81.FillColor = System.Drawing.Color.Empty;
            stateProperties81.ForeColor = System.Drawing.Color.Empty;
            stateProperties81.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpPassword.OnActiveState = stateProperties81;
            stateProperties82.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties82.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties82.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties82.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpPassword.OnDisabledState = stateProperties82;
            stateProperties83.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties83.FillColor = System.Drawing.Color.Empty;
            stateProperties83.ForeColor = System.Drawing.Color.Empty;
            stateProperties83.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpPassword.OnHoverState = stateProperties83;
            stateProperties84.BorderColor = System.Drawing.Color.Silver;
            stateProperties84.FillColor = System.Drawing.Color.White;
            stateProperties84.ForeColor = System.Drawing.Color.Empty;
            stateProperties84.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpPassword.OnIdleState = stateProperties84;
            this.tbSignUpPassword.Padding = new System.Windows.Forms.Padding(3);
            this.tbSignUpPassword.PasswordChar = '\0';
            this.tbSignUpPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpPassword.PlaceholderText = "Enter password...";
            this.tbSignUpPassword.ReadOnly = false;
            this.tbSignUpPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpPassword.SelectedText = "";
            this.tbSignUpPassword.SelectionLength = 0;
            this.tbSignUpPassword.SelectionStart = 0;
            this.tbSignUpPassword.ShortcutsEnabled = true;
            this.tbSignUpPassword.Size = new System.Drawing.Size(316, 39);
            this.tbSignUpPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpPassword.TabIndex = 0;
            this.tbSignUpPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpPassword.TextMarginBottom = 0;
            this.tbSignUpPassword.TextMarginLeft = 3;
            this.tbSignUpPassword.TextMarginTop = 1;
            this.tbSignUpPassword.TextPlaceholder = "Enter password...";
            this.tbSignUpPassword.UseSystemPasswordChar = false;
            this.tbSignUpPassword.WordWrap = true;
            // 
            // tbSignUpEmail
            // 
            this.tbSignUpEmail.AcceptsReturn = false;
            this.tbSignUpEmail.AcceptsTab = false;
            this.tbSignUpEmail.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tbSignUpEmail.AnimationSpeed = 200;
            this.tbSignUpEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpEmail.AutoSizeHeight = true;
            this.tbSignUpEmail.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpEmail.BackgroundImage")));
            this.tbSignUpEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSignUpEmail.BorderRadius = 20;
            this.tbSignUpEmail.BorderThickness = 1;
            this.tbSignUpEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSignUpEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpEmail.DefaultText = "";
            this.tbSignUpEmail.FillColor = System.Drawing.Color.White;
            this.tbSignUpEmail.HideSelection = true;
            this.tbSignUpEmail.IconLeft = null;
            this.tbSignUpEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpEmail.IconPadding = 10;
            this.tbSignUpEmail.IconRight = null;
            this.tbSignUpEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpEmail.Lines = new string[0];
            this.tbSignUpEmail.Location = new System.Drawing.Point(52, 264);
            this.tbSignUpEmail.MaxLength = 32767;
            this.tbSignUpEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpEmail.Modified = false;
            this.tbSignUpEmail.Multiline = false;
            this.tbSignUpEmail.Name = "tbSignUpEmail";
            stateProperties77.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties77.FillColor = System.Drawing.Color.Empty;
            stateProperties77.ForeColor = System.Drawing.Color.Empty;
            stateProperties77.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpEmail.OnActiveState = stateProperties77;
            stateProperties78.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties78.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties78.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties78.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpEmail.OnDisabledState = stateProperties78;
            stateProperties79.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties79.FillColor = System.Drawing.Color.Empty;
            stateProperties79.ForeColor = System.Drawing.Color.Empty;
            stateProperties79.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpEmail.OnHoverState = stateProperties79;
            stateProperties80.BorderColor = System.Drawing.Color.Silver;
            stateProperties80.FillColor = System.Drawing.Color.White;
            stateProperties80.ForeColor = System.Drawing.Color.Empty;
            stateProperties80.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpEmail.OnIdleState = stateProperties80;
            this.tbSignUpEmail.Padding = new System.Windows.Forms.Padding(3);
            this.tbSignUpEmail.PasswordChar = '\0';
            this.tbSignUpEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpEmail.PlaceholderText = "Enter email...";
            this.tbSignUpEmail.ReadOnly = false;
            this.tbSignUpEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpEmail.SelectedText = "";
            this.tbSignUpEmail.SelectionLength = 0;
            this.tbSignUpEmail.SelectionStart = 0;
            this.tbSignUpEmail.ShortcutsEnabled = true;
            this.tbSignUpEmail.Size = new System.Drawing.Size(356, 39);
            this.tbSignUpEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpEmail.TabIndex = 0;
            this.tbSignUpEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpEmail.TextMarginBottom = 0;
            this.tbSignUpEmail.TextMarginLeft = 3;
            this.tbSignUpEmail.TextMarginTop = 1;
            this.tbSignUpEmail.TextPlaceholder = "Enter email...";
            this.tbSignUpEmail.UseSystemPasswordChar = false;
            this.tbSignUpEmail.WordWrap = true;
            // 
            // tbSignUpUsername
            // 
            this.tbSignUpUsername.AcceptsReturn = false;
            this.tbSignUpUsername.AcceptsTab = false;
            this.tbSignUpUsername.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tbSignUpUsername.AnimationSpeed = 200;
            this.tbSignUpUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpUsername.AutoSizeHeight = true;
            this.tbSignUpUsername.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpUsername.BackgroundImage")));
            this.tbSignUpUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSignUpUsername.BorderRadius = 20;
            this.tbSignUpUsername.BorderThickness = 1;
            this.tbSignUpUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSignUpUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpUsername.DefaultText = "";
            this.tbSignUpUsername.FillColor = System.Drawing.Color.White;
            this.tbSignUpUsername.HideSelection = true;
            this.tbSignUpUsername.IconLeft = null;
            this.tbSignUpUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpUsername.IconPadding = 10;
            this.tbSignUpUsername.IconRight = null;
            this.tbSignUpUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpUsername.Lines = new string[0];
            this.tbSignUpUsername.Location = new System.Drawing.Point(52, 142);
            this.tbSignUpUsername.MaxLength = 32767;
            this.tbSignUpUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpUsername.Modified = false;
            this.tbSignUpUsername.Multiline = false;
            this.tbSignUpUsername.Name = "tbSignUpUsername";
            stateProperties73.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties73.FillColor = System.Drawing.Color.Empty;
            stateProperties73.ForeColor = System.Drawing.Color.Empty;
            stateProperties73.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpUsername.OnActiveState = stateProperties73;
            stateProperties74.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties74.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties74.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties74.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpUsername.OnDisabledState = stateProperties74;
            stateProperties75.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties75.FillColor = System.Drawing.Color.Empty;
            stateProperties75.ForeColor = System.Drawing.Color.Empty;
            stateProperties75.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpUsername.OnHoverState = stateProperties75;
            stateProperties76.BorderColor = System.Drawing.Color.Silver;
            stateProperties76.FillColor = System.Drawing.Color.White;
            stateProperties76.ForeColor = System.Drawing.Color.Empty;
            stateProperties76.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpUsername.OnIdleState = stateProperties76;
            this.tbSignUpUsername.Padding = new System.Windows.Forms.Padding(3);
            this.tbSignUpUsername.PasswordChar = '\0';
            this.tbSignUpUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpUsername.PlaceholderText = "Enter username...";
            this.tbSignUpUsername.ReadOnly = false;
            this.tbSignUpUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpUsername.SelectedText = "";
            this.tbSignUpUsername.SelectionLength = 0;
            this.tbSignUpUsername.SelectionStart = 0;
            this.tbSignUpUsername.ShortcutsEnabled = true;
            this.tbSignUpUsername.Size = new System.Drawing.Size(356, 39);
            this.tbSignUpUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpUsername.TabIndex = 0;
            this.tbSignUpUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpUsername.TextMarginBottom = 0;
            this.tbSignUpUsername.TextMarginLeft = 3;
            this.tbSignUpUsername.TextMarginTop = 1;
            this.tbSignUpUsername.TextPlaceholder = "Enter username...";
            this.tbSignUpUsername.UseSystemPasswordChar = false;
            this.tbSignUpUsername.WordWrap = true;
            // 
            // tbSignUpFirstName
            // 
            this.tbSignUpFirstName.AcceptsReturn = false;
            this.tbSignUpFirstName.AcceptsTab = false;
            this.tbSignUpFirstName.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tbSignUpFirstName.AnimationSpeed = 200;
            this.tbSignUpFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpFirstName.AutoSizeHeight = true;
            this.tbSignUpFirstName.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpFirstName.BackgroundImage")));
            this.tbSignUpFirstName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpFirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpFirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpFirstName.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSignUpFirstName.BorderRadius = 20;
            this.tbSignUpFirstName.BorderThickness = 1;
            this.tbSignUpFirstName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSignUpFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpFirstName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpFirstName.DefaultText = "";
            this.tbSignUpFirstName.FillColor = System.Drawing.Color.White;
            this.tbSignUpFirstName.HideSelection = true;
            this.tbSignUpFirstName.IconLeft = null;
            this.tbSignUpFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpFirstName.IconPadding = 10;
            this.tbSignUpFirstName.IconRight = null;
            this.tbSignUpFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpFirstName.Lines = new string[0];
            this.tbSignUpFirstName.Location = new System.Drawing.Point(52, 86);
            this.tbSignUpFirstName.MaxLength = 32767;
            this.tbSignUpFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpFirstName.Modified = false;
            this.tbSignUpFirstName.Multiline = false;
            this.tbSignUpFirstName.Name = "tbSignUpFirstName";
            stateProperties69.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpFirstName.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties70.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties70.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpFirstName.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpFirstName.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Silver;
            stateProperties72.FillColor = System.Drawing.Color.White;
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpFirstName.OnIdleState = stateProperties72;
            this.tbSignUpFirstName.Padding = new System.Windows.Forms.Padding(3);
            this.tbSignUpFirstName.PasswordChar = '\0';
            this.tbSignUpFirstName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpFirstName.PlaceholderText = "Enter First Name...";
            this.tbSignUpFirstName.ReadOnly = false;
            this.tbSignUpFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpFirstName.SelectedText = "";
            this.tbSignUpFirstName.SelectionLength = 0;
            this.tbSignUpFirstName.SelectionStart = 0;
            this.tbSignUpFirstName.ShortcutsEnabled = true;
            this.tbSignUpFirstName.Size = new System.Drawing.Size(176, 39);
            this.tbSignUpFirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpFirstName.TabIndex = 0;
            this.tbSignUpFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpFirstName.TextMarginBottom = 0;
            this.tbSignUpFirstName.TextMarginLeft = 3;
            this.tbSignUpFirstName.TextMarginTop = 1;
            this.tbSignUpFirstName.TextPlaceholder = "Enter First Name...";
            this.tbSignUpFirstName.UseSystemPasswordChar = false;
            this.tbSignUpFirstName.WordWrap = true;
            // 
            // tbSignUpLastName
            // 
            this.tbSignUpLastName.AcceptsReturn = false;
            this.tbSignUpLastName.AcceptsTab = false;
            this.tbSignUpLastName.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tbSignUpLastName.AnimationSpeed = 200;
            this.tbSignUpLastName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpLastName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpLastName.AutoSizeHeight = true;
            this.tbSignUpLastName.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpLastName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpLastName.BackgroundImage")));
            this.tbSignUpLastName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpLastName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpLastName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpLastName.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSignUpLastName.BorderRadius = 20;
            this.tbSignUpLastName.BorderThickness = 1;
            this.tbSignUpLastName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpLastName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSignUpLastName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpLastName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpLastName.DefaultText = "";
            this.tbSignUpLastName.FillColor = System.Drawing.Color.White;
            this.tbSignUpLastName.HideSelection = true;
            this.tbSignUpLastName.IconLeft = null;
            this.tbSignUpLastName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpLastName.IconPadding = 10;
            this.tbSignUpLastName.IconRight = null;
            this.tbSignUpLastName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpLastName.Lines = new string[0];
            this.tbSignUpLastName.Location = new System.Drawing.Point(234, 86);
            this.tbSignUpLastName.MaxLength = 32767;
            this.tbSignUpLastName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpLastName.Modified = false;
            this.tbSignUpLastName.Multiline = false;
            this.tbSignUpLastName.Name = "tbSignUpLastName";
            stateProperties65.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpLastName.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties66.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties66.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpLastName.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpLastName.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.Color.Silver;
            stateProperties68.FillColor = System.Drawing.Color.White;
            stateProperties68.ForeColor = System.Drawing.Color.Empty;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpLastName.OnIdleState = stateProperties68;
            this.tbSignUpLastName.Padding = new System.Windows.Forms.Padding(3);
            this.tbSignUpLastName.PasswordChar = '\0';
            this.tbSignUpLastName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpLastName.PlaceholderText = "Enter Last Name...";
            this.tbSignUpLastName.ReadOnly = false;
            this.tbSignUpLastName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpLastName.SelectedText = "";
            this.tbSignUpLastName.SelectionLength = 0;
            this.tbSignUpLastName.SelectionStart = 0;
            this.tbSignUpLastName.ShortcutsEnabled = true;
            this.tbSignUpLastName.Size = new System.Drawing.Size(174, 39);
            this.tbSignUpLastName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpLastName.TabIndex = 0;
            this.tbSignUpLastName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpLastName.TextMarginBottom = 0;
            this.tbSignUpLastName.TextMarginLeft = 3;
            this.tbSignUpLastName.TextMarginTop = 1;
            this.tbSignUpLastName.TextPlaceholder = "Enter Last Name...";
            this.tbSignUpLastName.UseSystemPasswordChar = false;
            this.tbSignUpLastName.WordWrap = true;
            // 
            // btnSignUp
            // 
            this.btnSignUp.AllowAnimations = true;
            this.btnSignUp.AllowMouseEffects = true;
            this.btnSignUp.AllowToggling = false;
            this.btnSignUp.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSignUp.AnimationSpeed = 200;
            this.btnSignUp.AutoGenerateColors = false;
            this.btnSignUp.AutoRoundBorders = false;
            this.btnSignUp.AutoSizeLeftIcon = true;
            this.btnSignUp.AutoSizeRightIcon = true;
            this.btnSignUp.BackColor = System.Drawing.Color.Transparent;
            this.btnSignUp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSignUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSignUp.BackgroundImage")));
            this.btnSignUp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.ButtonText = "SignUp";
            this.btnSignUp.ButtonTextMarginLeft = 0;
            this.btnSignUp.ColorContrastOnClick = 45;
            this.btnSignUp.ColorContrastOnHover = 45;
            this.btnSignUp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges17.BottomLeft = true;
            borderEdges17.BottomRight = true;
            borderEdges17.TopLeft = true;
            borderEdges17.TopRight = true;
            this.btnSignUp.CustomizableEdges = borderEdges17;
            this.btnSignUp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSignUp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUp.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSignUp.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSignUp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSignUp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSignUp.ForeColor = System.Drawing.Color.White;
            this.btnSignUp.IconLeft = null;
            this.btnSignUp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignUp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSignUp.IconMarginLeft = 11;
            this.btnSignUp.IconPadding = 10;
            this.btnSignUp.IconRight = null;
            this.btnSignUp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignUp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSignUp.IconSize = 25;
            this.btnSignUp.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSignUp.IdleBorderRadius = 0;
            this.btnSignUp.IdleBorderThickness = 0;
            this.btnSignUp.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSignUp.IdleIconLeftImage = null;
            this.btnSignUp.IdleIconRightImage = null;
            this.btnSignUp.IndicateFocus = false;
            this.btnSignUp.Location = new System.Drawing.Point(264, 333);
            this.btnSignUp.Name = "btnSignUp";
            this.btnSignUp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUp.OnDisabledState.BorderRadius = 20;
            this.btnSignUp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnDisabledState.BorderThickness = 1;
            this.btnSignUp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignUp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignUp.OnDisabledState.IconLeftImage = null;
            this.btnSignUp.OnDisabledState.IconRightImage = null;
            this.btnSignUp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSignUp.onHoverState.BorderRadius = 20;
            this.btnSignUp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.onHoverState.BorderThickness = 1;
            this.btnSignUp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSignUp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSignUp.onHoverState.IconLeftImage = null;
            this.btnSignUp.onHoverState.IconRightImage = null;
            this.btnSignUp.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUp.OnIdleState.BorderRadius = 20;
            this.btnSignUp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnIdleState.BorderThickness = 1;
            this.btnSignUp.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSignUp.OnIdleState.IconLeftImage = null;
            this.btnSignUp.OnIdleState.IconRightImage = null;
            this.btnSignUp.OnPressedState.BorderColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnSignUp.OnPressedState.BorderRadius = 20;
            this.btnSignUp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnPressedState.BorderThickness = 1;
            this.btnSignUp.OnPressedState.FillColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnSignUp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSignUp.OnPressedState.IconLeftImage = null;
            this.btnSignUp.OnPressedState.IconRightImage = null;
            this.btnSignUp.Size = new System.Drawing.Size(144, 40);
            this.btnSignUp.TabIndex = 1;
            this.btnSignUp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSignUp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSignUp.TextMarginLeft = 0;
            this.btnSignUp.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSignUp.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuIconButton1
            // 
            this.bunifuIconButton1.AllowAnimations = true;
            this.bunifuIconButton1.AllowBorderColorChanges = true;
            this.bunifuIconButton1.AllowMouseEffects = true;
            this.bunifuIconButton1.AnimationSpeed = 200;
            this.bunifuIconButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuIconButton1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuIconButton1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuIconButton1.BorderRadius = 1;
            this.bunifuIconButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.bunifuIconButton1.BorderThickness = 0;
            this.bunifuIconButton1.ColorContrastOnClick = 30;
            this.bunifuIconButton1.ColorContrastOnHover = 30;
            this.bunifuIconButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges16.BottomLeft = true;
            borderEdges16.BottomRight = true;
            borderEdges16.TopLeft = true;
            borderEdges16.TopRight = true;
            this.bunifuIconButton1.CustomizableEdges = borderEdges16;
            this.bunifuIconButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuIconButton1.Image = global::PresentationLayer.Properties.Resources.eye;
            this.bunifuIconButton1.ImageMargin = new System.Windows.Forms.Padding(0);
            this.bunifuIconButton1.Location = new System.Drawing.Point(374, 202);
            this.bunifuIconButton1.Name = "bunifuIconButton1";
            this.bunifuIconButton1.RoundBorders = true;
            this.bunifuIconButton1.ShowBorders = true;
            this.bunifuIconButton1.Size = new System.Drawing.Size(35, 35);
            this.bunifuIconButton1.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.bunifuIconButton1.TabIndex = 3;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.SystemColors.ActiveCaption;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(906, 647);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(173, 286);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(121, 15);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Forgot Your Password?";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 20.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(186, 0);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(86, 45);
            this.bunifuLabel4.TabIndex = 4;
            this.bunifuLabel4.Text = "Login";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 20.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.Location = new System.Drawing.Point(174, 3);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(121, 45);
            this.bunifuLabel5.TabIndex = 4;
            this.bunifuLabel5.Text = "Sign Up";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // frmLogin
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1337, 647);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "frmLogin";
            this.Text = "Login";
            this.Load += new System.EventHandler(this.FrmLogin_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuPanel2.ResumeLayout(false);
            this.panelSignIn.ResumeLayout(false);
            this.panelSignIn.PerformLayout();
            this.panelSignUp.ResumeLayout(false);
            this.panelSignUp.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuPanel panelSignIn;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnShowPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSignUpp;
        private Bunifu.UI.WinForms.BunifuTextBox tbUsername;
        private Bunifu.UI.WinForms.BunifuTextBox tbPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogin;
        private Bunifu.UI.WinForms.BunifuPanel panelSignUp;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton bunifuIconButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSignUp;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpLastName;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpFirstName;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpUsername;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpEmail;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSignUpBack;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
    }
}