//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Action { get; set; }
        public string Module { get; set; }
        public string Description { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
