//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNotification
    {
        public int EmailID { get; set; }
        public int UserID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual User User { get; set; }
    }
}
