//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FileType { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public int UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
