//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int HistoryID { get; set; }
        public int TaskID { get; set; }
        public string FieldChanged { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public int ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Task Task { get; set; }
    }
}
