//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHelpRequest
    {
        public int RequestID { get; set; }
        public int TaskID { get; set; }
        public int RequestedBy { get; set; }
        public int RequestedTo { get; set; }
        public string RequestMessage { get; set; }
        public Nullable<bool> IsResolved { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Task Task { get; set; }
    }
}
