namespace PresentationLayer.CustomControls
{
    partial class ctrlUserInfo
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ctrlUserInfo));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btCreate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tbFirstname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbLastname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pbAvatar = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.tbEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnShowPassword = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.flowLayoutPanel2 = new System.Windows.Forms.FlowLayoutPanel();
            this.tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbAvatar)).BeginInit();
            this.flowLayoutPanel1.SuspendLayout();
            this.flowLayoutPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.AutoSize = false;
            this.bunifuLabel3.AutoSizeHeightOnly = true;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(314, 180);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(10);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(158, 38);
            this.bunifuLabel3.TabIndex = 1;
            this.bunifuLabel3.Text = "Last Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.AutoSize = false;
            this.bunifuLabel8.AutoSizeHeightOnly = true;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.Location = new System.Drawing.Point(10, 10);
            this.bunifuLabel8.Margin = new System.Windows.Forms.Padding(10);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(151, 38);
            this.bunifuLabel8.TabIndex = 1;
            this.bunifuLabel8.Text = "Username";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.AutoSize = false;
            this.bunifuLabel9.AutoSizeHeightOnly = true;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel9.Location = new System.Drawing.Point(314, 420);
            this.bunifuLabel9.Margin = new System.Windows.Forms.Padding(10);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(145, 38);
            this.bunifuLabel9.TabIndex = 1;
            this.bunifuLabel9.Text = "Password";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.AutoSize = false;
            this.bunifuLabel7.AutoSizeHeightOnly = true;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(10, 300);
            this.bunifuLabel7.Margin = new System.Windows.Forms.Padding(10);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(121, 38);
            this.bunifuLabel7.TabIndex = 1;
            this.bunifuLabel7.Text = "Address";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbUsername
            // 
            this.tbUsername.AcceptsReturn = false;
            this.tbUsername.AcceptsTab = false;
            this.tbUsername.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.tbUsername.AnimationSpeed = 200;
            this.tbUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbUsername.AutoSizeHeight = true;
            this.tbUsername.BackColor = System.Drawing.Color.Transparent;
            this.tbUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbUsername.BackgroundImage")));
            this.tbUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbUsername.BorderRadius = 35;
            this.tbUsername.BorderThickness = 1;
            this.tbUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbUsername.DefaultText = "username1";
            this.tbUsername.Enabled = false;
            this.tbUsername.FillColor = System.Drawing.Color.White;
            this.tbUsername.HideSelection = true;
            this.tbUsername.IconLeft = null;
            this.tbUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.IconPadding = 10;
            this.tbUsername.IconRight = null;
            this.tbUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.Lines = new string[] {
        "username1"};
            this.tbUsername.Location = new System.Drawing.Point(10, 93);
            this.tbUsername.Margin = new System.Windows.Forms.Padding(10);
            this.tbUsername.MaxLength = 32767;
            this.tbUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbUsername.Modified = false;
            this.tbUsername.Multiline = false;
            this.tbUsername.Name = "tbUsername";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbUsername.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnIdleState = stateProperties4;
            this.tbUsername.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbUsername.PasswordChar = '\0';
            this.tbUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbUsername.PlaceholderText = "Enter last nane";
            this.tbUsername.ReadOnly = false;
            this.tbUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbUsername.SelectedText = "";
            this.tbUsername.SelectionLength = 0;
            this.tbUsername.SelectionStart = 0;
            this.tbUsername.ShortcutsEnabled = true;
            this.tbUsername.Size = new System.Drawing.Size(284, 42);
            this.tbUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbUsername.TabIndex = 0;
            this.tbUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbUsername.TextMarginBottom = 0;
            this.tbUsername.TextMarginLeft = 3;
            this.tbUsername.TextMarginTop = 1;
            this.tbUsername.TextPlaceholder = "Enter last nane";
            this.tbUsername.UseSystemPasswordChar = false;
            this.tbUsername.WordWrap = true;
            // 
            // tbPassword
            // 
            this.tbPassword.AcceptsReturn = false;
            this.tbPassword.AcceptsTab = false;
            this.tbPassword.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.tbPassword.AnimationSpeed = 200;
            this.tbPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPassword.AutoSizeHeight = true;
            this.tbPassword.BackColor = System.Drawing.Color.Transparent;
            this.tbPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPassword.BackgroundImage")));
            this.tbPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPassword.BorderRadius = 35;
            this.tbPassword.BorderThickness = 1;
            this.tbPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbPassword.DefaultText = "";
            this.tbPassword.FillColor = System.Drawing.Color.White;
            this.tbPassword.HideSelection = true;
            this.tbPassword.IconLeft = null;
            this.tbPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.IconPadding = 10;
            this.tbPassword.IconRight = null;
            this.tbPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.Lines = new string[0];
            this.tbPassword.Location = new System.Drawing.Point(10, 10);
            this.tbPassword.Margin = new System.Windows.Forms.Padding(10);
            this.tbPassword.MaxLength = 32767;
            this.tbPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPassword.Modified = false;
            this.tbPassword.Multiline = false;
            this.tbPassword.Name = "tbPassword";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbPassword.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnIdleState = stateProperties8;
            this.tbPassword.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbPassword.PasswordChar = '\0';
            this.tbPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPassword.PlaceholderText = "Enter last nane";
            this.tbPassword.ReadOnly = false;
            this.tbPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPassword.SelectedText = "";
            this.tbPassword.SelectionLength = 0;
            this.tbPassword.SelectionStart = 0;
            this.tbPassword.ShortcutsEnabled = true;
            this.tbPassword.Size = new System.Drawing.Size(211, 42);
            this.tbPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbPassword.TabIndex = 0;
            this.tbPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPassword.TextMarginBottom = 0;
            this.tbPassword.TextMarginLeft = 3;
            this.tbPassword.TextMarginTop = 1;
            this.tbPassword.TextPlaceholder = "Enter last nane";
            this.tbPassword.UseSystemPasswordChar = false;
            this.tbPassword.WordWrap = true;
            // 
            // btCancel
            // 
            this.btCancel.AllowAnimations = true;
            this.btCancel.AllowMouseEffects = true;
            this.btCancel.AllowToggling = false;
            this.btCancel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btCancel.AnimationSpeed = 200;
            this.btCancel.AutoGenerateColors = false;
            this.btCancel.AutoRoundBorders = false;
            this.btCancel.AutoSizeLeftIcon = true;
            this.btCancel.AutoSizeRightIcon = true;
            this.btCancel.BackColor = System.Drawing.Color.Transparent;
            this.btCancel.BackColor1 = System.Drawing.Color.Gainsboro;
            this.btCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btCancel.BackgroundImage")));
            this.btCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.ButtonText = "Cancel";
            this.btCancel.ButtonTextMarginLeft = 0;
            this.btCancel.ColorContrastOnClick = 45;
            this.btCancel.ColorContrastOnHover = 45;
            this.btCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btCancel.CustomizableEdges = borderEdges1;
            this.btCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btCancel.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btCancel.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btCancel.IconMarginLeft = 11;
            this.btCancel.IconPadding = 10;
            this.btCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btCancel.IconSize = 25;
            this.btCancel.IdleBorderColor = System.Drawing.Color.Gainsboro;
            this.btCancel.IdleBorderRadius = 40;
            this.btCancel.IdleBorderThickness = 1;
            this.btCancel.IdleFillColor = System.Drawing.Color.Gainsboro;
            this.btCancel.IdleIconLeftImage = null;
            this.btCancel.IdleIconRightImage = null;
            this.btCancel.IndicateFocus = false;
            this.btCancel.Location = new System.Drawing.Point(10, 10);
            this.btCancel.Margin = new System.Windows.Forms.Padding(10);
            this.btCancel.Name = "btCancel";
            this.btCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCancel.OnDisabledState.BorderRadius = 40;
            this.btCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.OnDisabledState.BorderThickness = 1;
            this.btCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btCancel.OnDisabledState.IconLeftImage = null;
            this.btCancel.OnDisabledState.IconRightImage = null;
            this.btCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btCancel.onHoverState.BorderRadius = 40;
            this.btCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.onHoverState.BorderThickness = 1;
            this.btCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btCancel.onHoverState.IconLeftImage = null;
            this.btCancel.onHoverState.IconRightImage = null;
            this.btCancel.OnIdleState.BorderColor = System.Drawing.Color.Gainsboro;
            this.btCancel.OnIdleState.BorderRadius = 40;
            this.btCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.OnIdleState.BorderThickness = 1;
            this.btCancel.OnIdleState.FillColor = System.Drawing.Color.Gainsboro;
            this.btCancel.OnIdleState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btCancel.OnIdleState.IconLeftImage = null;
            this.btCancel.OnIdleState.IconRightImage = null;
            this.btCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btCancel.OnPressedState.BorderRadius = 40;
            this.btCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCancel.OnPressedState.BorderThickness = 1;
            this.btCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btCancel.OnPressedState.IconLeftImage = null;
            this.btCancel.OnPressedState.IconRightImage = null;
            this.btCancel.Size = new System.Drawing.Size(114, 48);
            this.btCancel.TabIndex = 11;
            this.btCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btCancel.TextMarginLeft = 0;
            this.btCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btCancel.UseDefaultRadiusAndThickness = true;
            this.btCancel.Click += new System.EventHandler(this.btCancel_Click);
            // 
            // btCreate
            // 
            this.btCreate.AllowAnimations = true;
            this.btCreate.AllowMouseEffects = true;
            this.btCreate.AllowToggling = false;
            this.btCreate.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btCreate.AnimationSpeed = 200;
            this.btCreate.AutoGenerateColors = false;
            this.btCreate.AutoRoundBorders = false;
            this.btCreate.AutoSizeLeftIcon = true;
            this.btCreate.AutoSizeRightIcon = true;
            this.btCreate.BackColor = System.Drawing.Color.Transparent;
            this.btCreate.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btCreate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btCreate.BackgroundImage")));
            this.btCreate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.ButtonText = "Save";
            this.btCreate.ButtonTextMarginLeft = 0;
            this.btCreate.ColorContrastOnClick = 45;
            this.btCreate.ColorContrastOnHover = 45;
            this.btCreate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btCreate.CustomizableEdges = borderEdges2;
            this.btCreate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btCreate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCreate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btCreate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btCreate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btCreate.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btCreate.ForeColor = System.Drawing.Color.White;
            this.btCreate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btCreate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btCreate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btCreate.IconMarginLeft = 11;
            this.btCreate.IconPadding = 10;
            this.btCreate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btCreate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btCreate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btCreate.IconSize = 25;
            this.btCreate.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btCreate.IdleBorderRadius = 40;
            this.btCreate.IdleBorderThickness = 1;
            this.btCreate.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btCreate.IdleIconLeftImage = null;
            this.btCreate.IdleIconRightImage = null;
            this.btCreate.IndicateFocus = false;
            this.btCreate.Location = new System.Drawing.Point(144, 13);
            this.btCreate.Margin = new System.Windows.Forms.Padding(10);
            this.btCreate.Name = "btCreate";
            this.btCreate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCreate.OnDisabledState.BorderRadius = 40;
            this.btCreate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.OnDisabledState.BorderThickness = 1;
            this.btCreate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btCreate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btCreate.OnDisabledState.IconLeftImage = null;
            this.btCreate.OnDisabledState.IconRightImage = null;
            this.btCreate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btCreate.onHoverState.BorderRadius = 40;
            this.btCreate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.onHoverState.BorderThickness = 1;
            this.btCreate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btCreate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btCreate.onHoverState.IconLeftImage = null;
            this.btCreate.onHoverState.IconRightImage = null;
            this.btCreate.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btCreate.OnIdleState.BorderRadius = 40;
            this.btCreate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.OnIdleState.BorderThickness = 1;
            this.btCreate.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btCreate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btCreate.OnIdleState.IconLeftImage = null;
            this.btCreate.OnIdleState.IconRightImage = null;
            this.btCreate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btCreate.OnPressedState.BorderRadius = 40;
            this.btCreate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreate.OnPressedState.BorderThickness = 1;
            this.btCreate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btCreate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btCreate.OnPressedState.IconLeftImage = null;
            this.btCreate.OnPressedState.IconRightImage = null;
            this.btCreate.Size = new System.Drawing.Size(112, 42);
            this.btCreate.TabIndex = 12;
            this.btCreate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btCreate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btCreate.TextMarginLeft = 0;
            this.btCreate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btCreate.UseDefaultRadiusAndThickness = true;
            this.btCreate.Click += new System.EventHandler(this.btCreate_Click);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.AutoSize = false;
            this.bunifuLabel6.AutoSizeHeightOnly = true;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(314, 300);
            this.bunifuLabel6.Margin = new System.Windows.Forms.Padding(10);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(81, 38);
            this.bunifuLabel6.TabIndex = 1;
            this.bunifuLabel6.Text = "Email";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.AutoSize = false;
            this.bunifuLabel4.AutoSizeHeightOnly = true;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(10, 420);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(10);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(154, 38);
            this.bunifuLabel4.TabIndex = 1;
            this.bunifuLabel4.Text = "Phone No.";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.AutoSizeHeightOnly = true;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(10, 180);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(10);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(160, 38);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "First Name";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbPhone
            // 
            this.tbPhone.AcceptsReturn = false;
            this.tbPhone.AcceptsTab = false;
            this.tbPhone.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.tbPhone.AnimationSpeed = 200;
            this.tbPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPhone.AutoSizeHeight = true;
            this.tbPhone.BackColor = System.Drawing.Color.Transparent;
            this.tbPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPhone.BackgroundImage")));
            this.tbPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPhone.BorderRadius = 35;
            this.tbPhone.BorderThickness = 1;
            this.tbPhone.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbPhone.DefaultText = "";
            this.tbPhone.FillColor = System.Drawing.Color.White;
            this.tbPhone.HideSelection = true;
            this.tbPhone.IconLeft = null;
            this.tbPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.IconPadding = 10;
            this.tbPhone.IconRight = null;
            this.tbPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.Lines = new string[0];
            this.tbPhone.Location = new System.Drawing.Point(10, 480);
            this.tbPhone.Margin = new System.Windows.Forms.Padding(10);
            this.tbPhone.MaxLength = 32767;
            this.tbPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPhone.Modified = false;
            this.tbPhone.Multiline = false;
            this.tbPhone.Name = "tbPhone";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbPhone.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnIdleState = stateProperties12;
            this.tbPhone.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbPhone.PasswordChar = '\0';
            this.tbPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPhone.PlaceholderText = "Enter first nane";
            this.tbPhone.ReadOnly = false;
            this.tbPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPhone.SelectedText = "";
            this.tbPhone.SelectionLength = 0;
            this.tbPhone.SelectionStart = 0;
            this.tbPhone.ShortcutsEnabled = true;
            this.tbPhone.Size = new System.Drawing.Size(284, 42);
            this.tbPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbPhone.TabIndex = 0;
            this.tbPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPhone.TextMarginBottom = 0;
            this.tbPhone.TextMarginLeft = 3;
            this.tbPhone.TextMarginTop = 1;
            this.tbPhone.TextPlaceholder = "Enter first nane";
            this.tbPhone.UseSystemPasswordChar = false;
            this.tbPhone.WordWrap = true;
            // 
            // tbAddress
            // 
            this.tbAddress.AcceptsReturn = false;
            this.tbAddress.AcceptsTab = false;
            this.tbAddress.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.tbAddress.AnimationSpeed = 200;
            this.tbAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAddress.AutoSizeHeight = true;
            this.tbAddress.BackColor = System.Drawing.Color.Transparent;
            this.tbAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAddress.BackgroundImage")));
            this.tbAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAddress.BorderRadius = 35;
            this.tbAddress.BorderThickness = 1;
            this.tbAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbAddress.DefaultText = "";
            this.tbAddress.FillColor = System.Drawing.Color.White;
            this.tbAddress.HideSelection = true;
            this.tbAddress.IconLeft = null;
            this.tbAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.IconPadding = 10;
            this.tbAddress.IconRight = null;
            this.tbAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.Lines = new string[0];
            this.tbAddress.Location = new System.Drawing.Point(10, 358);
            this.tbAddress.Margin = new System.Windows.Forms.Padding(10);
            this.tbAddress.MaxLength = 32767;
            this.tbAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAddress.Modified = false;
            this.tbAddress.Multiline = false;
            this.tbAddress.Name = "tbAddress";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAddress.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnIdleState = stateProperties16;
            this.tbAddress.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbAddress.PasswordChar = '\0';
            this.tbAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAddress.PlaceholderText = "Enter first nane";
            this.tbAddress.ReadOnly = false;
            this.tbAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAddress.SelectedText = "";
            this.tbAddress.SelectionLength = 0;
            this.tbAddress.SelectionStart = 0;
            this.tbAddress.ShortcutsEnabled = true;
            this.tbAddress.Size = new System.Drawing.Size(284, 42);
            this.tbAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAddress.TabIndex = 0;
            this.tbAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAddress.TextMarginBottom = 0;
            this.tbAddress.TextMarginLeft = 3;
            this.tbAddress.TextMarginTop = 1;
            this.tbAddress.TextPlaceholder = "Enter first nane";
            this.tbAddress.UseSystemPasswordChar = false;
            this.tbAddress.WordWrap = true;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel3, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel1, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.tbFirstname, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.tbLastname, 1, 3);
            this.tableLayoutPanel1.Controls.Add(this.tbAddress, 0, 5);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel7, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.tbUsername, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel8, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.pbAvatar, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel6, 1, 4);
            this.tableLayoutPanel1.Controls.Add(this.tbEmail, 1, 5);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel4, 0, 6);
            this.tableLayoutPanel1.Controls.Add(this.tbPhone, 0, 7);
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel9, 1, 6);
            this.tableLayoutPanel1.Controls.Add(this.flowLayoutPanel1, 1, 8);
            this.tableLayoutPanel1.Controls.Add(this.flowLayoutPanel2, 1, 7);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 10;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(963, 615);
            this.tableLayoutPanel1.TabIndex = 17;
            // 
            // tbFirstname
            // 
            this.tbFirstname.AcceptsReturn = false;
            this.tbFirstname.AcceptsTab = false;
            this.tbFirstname.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.tbFirstname.AnimationSpeed = 200;
            this.tbFirstname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbFirstname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbFirstname.AutoSizeHeight = true;
            this.tbFirstname.BackColor = System.Drawing.Color.Transparent;
            this.tbFirstname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbFirstname.BackgroundImage")));
            this.tbFirstname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbFirstname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbFirstname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbFirstname.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbFirstname.BorderRadius = 35;
            this.tbFirstname.BorderThickness = 1;
            this.tbFirstname.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbFirstname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbFirstname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbFirstname.DefaultText = "";
            this.tbFirstname.FillColor = System.Drawing.Color.White;
            this.tbFirstname.HideSelection = true;
            this.tbFirstname.IconLeft = null;
            this.tbFirstname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.IconPadding = 10;
            this.tbFirstname.IconRight = null;
            this.tbFirstname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstname.Lines = new string[0];
            this.tbFirstname.Location = new System.Drawing.Point(10, 238);
            this.tbFirstname.Margin = new System.Windows.Forms.Padding(10);
            this.tbFirstname.MaxLength = 32767;
            this.tbFirstname.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbFirstname.Modified = false;
            this.tbFirstname.Multiline = false;
            this.tbFirstname.Name = "tbFirstname";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbFirstname.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstname.OnIdleState = stateProperties20;
            this.tbFirstname.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbFirstname.PasswordChar = '\0';
            this.tbFirstname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbFirstname.PlaceholderText = "Enter first nane";
            this.tbFirstname.ReadOnly = false;
            this.tbFirstname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbFirstname.SelectedText = "";
            this.tbFirstname.SelectionLength = 0;
            this.tbFirstname.SelectionStart = 0;
            this.tbFirstname.ShortcutsEnabled = true;
            this.tbFirstname.Size = new System.Drawing.Size(284, 42);
            this.tbFirstname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbFirstname.TabIndex = 0;
            this.tbFirstname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbFirstname.TextMarginBottom = 0;
            this.tbFirstname.TextMarginLeft = 3;
            this.tbFirstname.TextMarginTop = 1;
            this.tbFirstname.TextPlaceholder = "Enter first nane";
            this.tbFirstname.UseSystemPasswordChar = false;
            this.tbFirstname.WordWrap = true;
            // 
            // tbLastname
            // 
            this.tbLastname.AcceptsReturn = false;
            this.tbLastname.AcceptsTab = false;
            this.tbLastname.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.tbLastname.AnimationSpeed = 200;
            this.tbLastname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbLastname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbLastname.AutoSizeHeight = true;
            this.tbLastname.BackColor = System.Drawing.Color.Transparent;
            this.tbLastname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbLastname.BackgroundImage")));
            this.tbLastname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbLastname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbLastname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbLastname.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbLastname.BorderRadius = 35;
            this.tbLastname.BorderThickness = 1;
            this.tbLastname.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbLastname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbLastname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbLastname.DefaultText = "";
            this.tbLastname.FillColor = System.Drawing.Color.White;
            this.tbLastname.HideSelection = true;
            this.tbLastname.IconLeft = null;
            this.tbLastname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.IconPadding = 10;
            this.tbLastname.IconRight = null;
            this.tbLastname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastname.Lines = new string[0];
            this.tbLastname.Location = new System.Drawing.Point(314, 238);
            this.tbLastname.Margin = new System.Windows.Forms.Padding(10);
            this.tbLastname.MaxLength = 32767;
            this.tbLastname.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbLastname.Modified = false;
            this.tbLastname.Multiline = false;
            this.tbLastname.Name = "tbLastname";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbLastname.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastname.OnIdleState = stateProperties24;
            this.tbLastname.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbLastname.PasswordChar = '\0';
            this.tbLastname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbLastname.PlaceholderText = "Enter last nane";
            this.tbLastname.ReadOnly = false;
            this.tbLastname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbLastname.SelectedText = "";
            this.tbLastname.SelectionLength = 0;
            this.tbLastname.SelectionStart = 0;
            this.tbLastname.ShortcutsEnabled = true;
            this.tbLastname.Size = new System.Drawing.Size(284, 42);
            this.tbLastname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbLastname.TabIndex = 0;
            this.tbLastname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbLastname.TextMarginBottom = 0;
            this.tbLastname.TextMarginLeft = 3;
            this.tbLastname.TextMarginTop = 1;
            this.tbLastname.TextPlaceholder = "Enter last nane";
            this.tbLastname.UseSystemPasswordChar = false;
            this.tbLastname.WordWrap = true;
            // 
            // pbAvatar
            // 
            this.pbAvatar.AllowFocused = false;
            this.pbAvatar.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.pbAvatar.AutoSizeHeight = false;
            this.pbAvatar.BorderRadius = 75;
            this.pbAvatar.Image = ((System.Drawing.Image)(resources.GetObject("pbAvatar.Image")));
            this.pbAvatar.IsCircle = true;
            this.pbAvatar.Location = new System.Drawing.Point(314, 10);
            this.pbAvatar.Margin = new System.Windows.Forms.Padding(10);
            this.pbAvatar.Name = "pbAvatar";
            this.tableLayoutPanel1.SetRowSpan(this.pbAvatar, 2);
            this.pbAvatar.Size = new System.Drawing.Size(150, 150);
            this.pbAvatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbAvatar.TabIndex = 4;
            this.pbAvatar.TabStop = false;
            this.pbAvatar.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // tbEmail
            // 
            this.tbEmail.AcceptsReturn = false;
            this.tbEmail.AcceptsTab = false;
            this.tbEmail.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.tbEmail.AnimationSpeed = 200;
            this.tbEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbEmail.AutoSizeHeight = true;
            this.tbEmail.BackColor = System.Drawing.Color.Transparent;
            this.tbEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbEmail.BackgroundImage")));
            this.tbEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbEmail.BorderRadius = 35;
            this.tbEmail.BorderThickness = 1;
            this.tbEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbEmail.DefaultText = "";
            this.tbEmail.FillColor = System.Drawing.Color.White;
            this.tbEmail.HideSelection = true;
            this.tbEmail.IconLeft = null;
            this.tbEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.IconPadding = 10;
            this.tbEmail.IconRight = null;
            this.tbEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.Lines = new string[0];
            this.tbEmail.Location = new System.Drawing.Point(314, 358);
            this.tbEmail.Margin = new System.Windows.Forms.Padding(10);
            this.tbEmail.MaxLength = 32767;
            this.tbEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbEmail.Modified = false;
            this.tbEmail.Multiline = false;
            this.tbEmail.Name = "tbEmail";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbEmail.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnIdleState = stateProperties28;
            this.tbEmail.Padding = new System.Windows.Forms.Padding(6, 4, 6, 4);
            this.tbEmail.PasswordChar = '\0';
            this.tbEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbEmail.PlaceholderText = "Enter email";
            this.tbEmail.ReadOnly = false;
            this.tbEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbEmail.SelectedText = "";
            this.tbEmail.SelectionLength = 0;
            this.tbEmail.SelectionStart = 0;
            this.tbEmail.ShortcutsEnabled = true;
            this.tbEmail.Size = new System.Drawing.Size(284, 42);
            this.tbEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbEmail.TabIndex = 0;
            this.tbEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbEmail.TextMarginBottom = 0;
            this.tbEmail.TextMarginLeft = 3;
            this.tbEmail.TextMarginTop = 1;
            this.tbEmail.TextPlaceholder = "Enter email";
            this.tbEmail.UseSystemPasswordChar = false;
            this.tbEmail.WordWrap = true;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.flowLayoutPanel1.Controls.Add(this.btCancel);
            this.flowLayoutPanel1.Controls.Add(this.btCreate);
            this.flowLayoutPanel1.Location = new System.Drawing.Point(307, 537);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(291, 75);
            this.flowLayoutPanel1.TabIndex = 13;
            // 
            // btnShowPassword
            // 
            this.btnShowPassword.AllowAnimations = true;
            this.btnShowPassword.AllowBorderColorChanges = true;
            this.btnShowPassword.AllowMouseEffects = true;
            this.btnShowPassword.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.btnShowPassword.AnimationSpeed = 200;
            this.btnShowPassword.BackColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BackgroundColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BorderColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BorderRadius = 1;
            this.btnShowPassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.btnShowPassword.BorderThickness = 0;
            this.btnShowPassword.ColorContrastOnClick = 30;
            this.btnShowPassword.ColorContrastOnHover = 30;
            this.btnShowPassword.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnShowPassword.CustomizableEdges = borderEdges3;
            this.btnShowPassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnShowPassword.Image = global::PresentationLayer.Properties.Resources.eye;
            this.btnShowPassword.ImageMargin = new System.Windows.Forms.Padding(0);
            this.btnShowPassword.Location = new System.Drawing.Point(241, 13);
            this.btnShowPassword.Margin = new System.Windows.Forms.Padding(10);
            this.btnShowPassword.Name = "btnShowPassword";
            this.btnShowPassword.RoundBorders = true;
            this.btnShowPassword.ShowBorders = true;
            this.btnShowPassword.Size = new System.Drawing.Size(35, 35);
            this.btnShowPassword.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.btnShowPassword.TabIndex = 14;
            this.btnShowPassword.Click += new System.EventHandler(this.btnShowPassword_Click);
            // 
            // flowLayoutPanel2
            // 
            this.flowLayoutPanel2.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.flowLayoutPanel2.Controls.Add(this.tbPassword);
            this.flowLayoutPanel2.Controls.Add(this.btnShowPassword);
            this.flowLayoutPanel2.Location = new System.Drawing.Point(307, 471);
            this.flowLayoutPanel2.Name = "flowLayoutPanel2";
            this.flowLayoutPanel2.Size = new System.Drawing.Size(291, 60);
            this.flowLayoutPanel2.TabIndex = 14;
            // 
            // ctrlUserInfo
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.tableLayoutPanel1);
            this.Name = "ctrlUserInfo";
            this.Size = new System.Drawing.Size(963, 615);
            this.Load += new System.EventHandler(this.ctrlUserInfo_Load);
            this.tableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbAvatar)).EndInit();
            this.flowLayoutPanel1.ResumeLayout(false);
            this.flowLayoutPanel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox tbUsername;
        private Bunifu.UI.WinForms.BunifuTextBox tbPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btCreate;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox tbPhone;
        private Bunifu.UI.WinForms.BunifuTextBox tbAddress;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox tbFirstname;
        private Bunifu.UI.WinForms.BunifuTextBox tbLastname;
        private Bunifu.UI.WinForms.BunifuPictureBox pbAvatar;
        private Bunifu.UI.WinForms.BunifuTextBox tbEmail;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnShowPassword;
    }
}
