namespace PresentationLayer.CustomControls
{
    partial class ctrlSignUpForm
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ctrlSignUpForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnShowPassword = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.btnSignUp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tbSignUpLastName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbSignUpFirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbSignUpUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbSignUpEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbSignUpPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnSignUpBack = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.tableLayoutPanel1.SuspendLayout();
            this.flowLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.AutoSize = false;
            this.tableLayoutPanel1.SetColumnSpan(this.bunifuLabel5, 2);
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 20.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.Location = new System.Drawing.Point(172, 9);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(107, 37);
            this.bunifuLabel5.TabIndex = 17;
            this.bunifuLabel5.Text = "Sign Up";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnShowPassword
            // 
            this.btnShowPassword.AllowAnimations = true;
            this.btnShowPassword.AllowBorderColorChanges = true;
            this.btnShowPassword.AllowMouseEffects = true;
            this.btnShowPassword.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.btnShowPassword.AnimationSpeed = 200;
            this.btnShowPassword.BackColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BackgroundColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BorderColor = System.Drawing.Color.Transparent;
            this.btnShowPassword.BorderRadius = 1;
            this.btnShowPassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.btnShowPassword.BorderThickness = 0;
            this.btnShowPassword.ColorContrastOnClick = 30;
            this.btnShowPassword.ColorContrastOnHover = 30;
            this.btnShowPassword.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnShowPassword.CustomizableEdges = borderEdges3;
            this.btnShowPassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnShowPassword.Image = global::PresentationLayer.Properties.Resources.eye;
            this.btnShowPassword.ImageMargin = new System.Windows.Forms.Padding(0);
            this.btnShowPassword.Location = new System.Drawing.Point(342, 2);
            this.btnShowPassword.Margin = new System.Windows.Forms.Padding(0);
            this.btnShowPassword.Name = "btnShowPassword";
            this.btnShowPassword.RoundBorders = true;
            this.btnShowPassword.ShowBorders = true;
            this.btnShowPassword.Size = new System.Drawing.Size(35, 35);
            this.btnShowPassword.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.btnShowPassword.TabIndex = 16;
            this.btnShowPassword.Click += new System.EventHandler(this.btnShowPassword_Click);
            // 
            // btnSignUp
            // 
            this.btnSignUp.AllowAnimations = true;
            this.btnSignUp.AllowMouseEffects = true;
            this.btnSignUp.AllowToggling = false;
            this.btnSignUp.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnSignUp.AnimationSpeed = 200;
            this.btnSignUp.AutoGenerateColors = false;
            this.btnSignUp.AutoRoundBorders = false;
            this.btnSignUp.AutoSizeLeftIcon = true;
            this.btnSignUp.AutoSizeRightIcon = true;
            this.btnSignUp.BackColor = System.Drawing.Color.Transparent;
            this.btnSignUp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSignUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSignUp.BackgroundImage")));
            this.btnSignUp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.ButtonText = "SignUp";
            this.btnSignUp.ButtonTextMarginLeft = 0;
            this.btnSignUp.ColorContrastOnClick = 45;
            this.btnSignUp.ColorContrastOnHover = 45;
            this.tableLayoutPanel1.SetColumnSpan(this.btnSignUp, 2);
            this.btnSignUp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSignUp.CustomizableEdges = borderEdges1;
            this.btnSignUp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSignUp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUp.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSignUp.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSignUp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSignUp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSignUp.ForeColor = System.Drawing.Color.White;
            this.btnSignUp.IconLeft = null;
            this.btnSignUp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignUp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSignUp.IconMarginLeft = 11;
            this.btnSignUp.IconPadding = 10;
            this.btnSignUp.IconRight = null;
            this.btnSignUp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignUp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSignUp.IconSize = 25;
            this.btnSignUp.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSignUp.IdleBorderRadius = 0;
            this.btnSignUp.IdleBorderThickness = 0;
            this.btnSignUp.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSignUp.IdleIconLeftImage = null;
            this.btnSignUp.IdleIconRightImage = null;
            this.btnSignUp.IndicateFocus = false;
            this.btnSignUp.Location = new System.Drawing.Point(174, 288);
            this.btnSignUp.Name = "btnSignUp";
            this.btnSignUp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUp.OnDisabledState.BorderRadius = 20;
            this.btnSignUp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnDisabledState.BorderThickness = 1;
            this.btnSignUp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignUp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignUp.OnDisabledState.IconLeftImage = null;
            this.btnSignUp.OnDisabledState.IconRightImage = null;
            this.btnSignUp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSignUp.onHoverState.BorderRadius = 20;
            this.btnSignUp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.onHoverState.BorderThickness = 1;
            this.btnSignUp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSignUp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSignUp.onHoverState.IconLeftImage = null;
            this.btnSignUp.onHoverState.IconRightImage = null;
            this.btnSignUp.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUp.OnIdleState.BorderRadius = 20;
            this.btnSignUp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnIdleState.BorderThickness = 1;
            this.btnSignUp.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSignUp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSignUp.OnIdleState.IconLeftImage = null;
            this.btnSignUp.OnIdleState.IconRightImage = null;
            this.btnSignUp.OnPressedState.BorderColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnSignUp.OnPressedState.BorderRadius = 20;
            this.btnSignUp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnPressedState.BorderThickness = 1;
            this.btnSignUp.OnPressedState.FillColor = System.Drawing.SystemColors.MenuHighlight;
            this.btnSignUp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSignUp.OnPressedState.IconLeftImage = null;
            this.btnSignUp.OnPressedState.IconRightImage = null;
            this.btnSignUp.Size = new System.Drawing.Size(103, 29);
            this.btnSignUp.TabIndex = 14;
            this.btnSignUp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSignUp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSignUp.TextMarginLeft = 0;
            this.btnSignUp.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSignUp.UseDefaultRadiusAndThickness = true;
            this.btnSignUp.Click += new System.EventHandler(this.btnSignUp_Click);
            // 
            // tbSignUpLastName
            // 
            this.tbSignUpLastName.AcceptsReturn = false;
            this.tbSignUpLastName.AcceptsTab = false;
            this.tbSignUpLastName.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.tbSignUpLastName.AnimationSpeed = 200;
            this.tbSignUpLastName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpLastName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpLastName.AutoSizeHeight = true;
            this.tbSignUpLastName.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpLastName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpLastName.BackgroundImage")));
            this.tbSignUpLastName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpLastName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpLastName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpLastName.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbSignUpLastName.BorderRadius = 20;
            this.tbSignUpLastName.BorderThickness = 1;
            this.tbSignUpLastName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpLastName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSignUpLastName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpLastName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpLastName.DefaultText = "";
            this.tbSignUpLastName.FillColor = System.Drawing.Color.White;
            this.tbSignUpLastName.HideSelection = true;
            this.tbSignUpLastName.IconLeft = null;
            this.tbSignUpLastName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpLastName.IconPadding = 10;
            this.tbSignUpLastName.IconRight = null;
            this.tbSignUpLastName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpLastName.Lines = new string[0];
            this.tbSignUpLastName.Location = new System.Drawing.Point(229, 63);
            this.tbSignUpLastName.MaxLength = 32767;
            this.tbSignUpLastName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpLastName.Modified = false;
            this.tbSignUpLastName.Multiline = false;
            this.tbSignUpLastName.Name = "tbSignUpLastName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpLastName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpLastName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpLastName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.DimGray;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpLastName.OnIdleState = stateProperties4;
            this.tbSignUpLastName.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tbSignUpLastName.PasswordChar = '\0';
            this.tbSignUpLastName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpLastName.PlaceholderText = "Enter Last Name...";
            this.tbSignUpLastName.ReadOnly = false;
            this.tbSignUpLastName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpLastName.SelectedText = "";
            this.tbSignUpLastName.SelectionLength = 0;
            this.tbSignUpLastName.SelectionStart = 0;
            this.tbSignUpLastName.ShortcutsEnabled = true;
            this.tbSignUpLastName.Size = new System.Drawing.Size(192, 39);
            this.tbSignUpLastName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpLastName.TabIndex = 9;
            this.tbSignUpLastName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpLastName.TextMarginBottom = 0;
            this.tbSignUpLastName.TextMarginLeft = 3;
            this.tbSignUpLastName.TextMarginTop = 1;
            this.tbSignUpLastName.TextPlaceholder = "Enter Last Name...";
            this.tbSignUpLastName.UseSystemPasswordChar = false;
            this.tbSignUpLastName.WordWrap = true;
            // 
            // tbSignUpFirstName
            // 
            this.tbSignUpFirstName.AcceptsReturn = false;
            this.tbSignUpFirstName.AcceptsTab = false;
            this.tbSignUpFirstName.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.tbSignUpFirstName.AnimationSpeed = 200;
            this.tbSignUpFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpFirstName.AutoSizeHeight = true;
            this.tbSignUpFirstName.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpFirstName.BackgroundImage")));
            this.tbSignUpFirstName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpFirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpFirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpFirstName.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbSignUpFirstName.BorderRadius = 20;
            this.tbSignUpFirstName.BorderThickness = 1;
            this.tbSignUpFirstName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSignUpFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpFirstName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpFirstName.DefaultText = "";
            this.tbSignUpFirstName.FillColor = System.Drawing.Color.White;
            this.tbSignUpFirstName.HideSelection = true;
            this.tbSignUpFirstName.IconLeft = null;
            this.tbSignUpFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpFirstName.IconPadding = 10;
            this.tbSignUpFirstName.IconRight = null;
            this.tbSignUpFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpFirstName.Lines = new string[0];
            this.tbSignUpFirstName.Location = new System.Drawing.Point(31, 63);
            this.tbSignUpFirstName.MaxLength = 32767;
            this.tbSignUpFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpFirstName.Modified = false;
            this.tbSignUpFirstName.Multiline = false;
            this.tbSignUpFirstName.Name = "tbSignUpFirstName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpFirstName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpFirstName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpFirstName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.DimGray;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpFirstName.OnIdleState = stateProperties8;
            this.tbSignUpFirstName.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tbSignUpFirstName.PasswordChar = '\0';
            this.tbSignUpFirstName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpFirstName.PlaceholderText = "Enter First Name...";
            this.tbSignUpFirstName.ReadOnly = false;
            this.tbSignUpFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpFirstName.SelectedText = "";
            this.tbSignUpFirstName.SelectionLength = 0;
            this.tbSignUpFirstName.SelectionStart = 0;
            this.tbSignUpFirstName.ShortcutsEnabled = true;
            this.tbSignUpFirstName.Size = new System.Drawing.Size(192, 39);
            this.tbSignUpFirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpFirstName.TabIndex = 10;
            this.tbSignUpFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpFirstName.TextMarginBottom = 0;
            this.tbSignUpFirstName.TextMarginLeft = 3;
            this.tbSignUpFirstName.TextMarginTop = 1;
            this.tbSignUpFirstName.TextPlaceholder = "Enter First Name...";
            this.tbSignUpFirstName.UseSystemPasswordChar = false;
            this.tbSignUpFirstName.WordWrap = true;
            // 
            // tbSignUpUsername
            // 
            this.tbSignUpUsername.AcceptsReturn = false;
            this.tbSignUpUsername.AcceptsTab = false;
            this.tbSignUpUsername.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbSignUpUsername.AnimationSpeed = 200;
            this.tbSignUpUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpUsername.AutoSizeHeight = true;
            this.tbSignUpUsername.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpUsername.BackgroundImage")));
            this.tbSignUpUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpUsername.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbSignUpUsername.BorderRadius = 20;
            this.tbSignUpUsername.BorderThickness = 1;
            this.tbSignUpUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.tbSignUpUsername, 2);
            this.tbSignUpUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpUsername.DefaultText = "";
            this.tbSignUpUsername.FillColor = System.Drawing.Color.White;
            this.tbSignUpUsername.HideSelection = true;
            this.tbSignUpUsername.IconLeft = null;
            this.tbSignUpUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpUsername.IconPadding = 10;
            this.tbSignUpUsername.IconRight = null;
            this.tbSignUpUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpUsername.Lines = new string[0];
            this.tbSignUpUsername.Location = new System.Drawing.Point(30, 118);
            this.tbSignUpUsername.MaxLength = 32767;
            this.tbSignUpUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpUsername.Modified = false;
            this.tbSignUpUsername.Multiline = false;
            this.tbSignUpUsername.Name = "tbSignUpUsername";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpUsername.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpUsername.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpUsername.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.DimGray;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpUsername.OnIdleState = stateProperties12;
            this.tbSignUpUsername.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tbSignUpUsername.PasswordChar = '\0';
            this.tbSignUpUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpUsername.PlaceholderText = "Enter username...";
            this.tbSignUpUsername.ReadOnly = false;
            this.tbSignUpUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpUsername.SelectedText = "";
            this.tbSignUpUsername.SelectionLength = 0;
            this.tbSignUpUsername.SelectionStart = 0;
            this.tbSignUpUsername.ShortcutsEnabled = true;
            this.tbSignUpUsername.Size = new System.Drawing.Size(392, 39);
            this.tbSignUpUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpUsername.TabIndex = 11;
            this.tbSignUpUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpUsername.TextMarginBottom = 0;
            this.tbSignUpUsername.TextMarginLeft = 3;
            this.tbSignUpUsername.TextMarginTop = 1;
            this.tbSignUpUsername.TextPlaceholder = "Enter username...";
            this.tbSignUpUsername.UseSystemPasswordChar = false;
            this.tbSignUpUsername.WordWrap = true;
            // 
            // tbSignUpEmail
            // 
            this.tbSignUpEmail.AcceptsReturn = false;
            this.tbSignUpEmail.AcceptsTab = false;
            this.tbSignUpEmail.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tbSignUpEmail.AnimationSpeed = 200;
            this.tbSignUpEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpEmail.AutoSizeHeight = true;
            this.tbSignUpEmail.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpEmail.BackgroundImage")));
            this.tbSignUpEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpEmail.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbSignUpEmail.BorderRadius = 20;
            this.tbSignUpEmail.BorderThickness = 1;
            this.tbSignUpEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.tbSignUpEmail, 2);
            this.tbSignUpEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpEmail.DefaultText = "";
            this.tbSignUpEmail.FillColor = System.Drawing.Color.White;
            this.tbSignUpEmail.HideSelection = true;
            this.tbSignUpEmail.IconLeft = null;
            this.tbSignUpEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpEmail.IconPadding = 10;
            this.tbSignUpEmail.IconRight = null;
            this.tbSignUpEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpEmail.Lines = new string[0];
            this.tbSignUpEmail.Location = new System.Drawing.Point(30, 228);
            this.tbSignUpEmail.MaxLength = 32767;
            this.tbSignUpEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpEmail.Modified = false;
            this.tbSignUpEmail.Multiline = false;
            this.tbSignUpEmail.Name = "tbSignUpEmail";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpEmail.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpEmail.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpEmail.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.DimGray;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpEmail.OnIdleState = stateProperties16;
            this.tbSignUpEmail.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tbSignUpEmail.PasswordChar = '\0';
            this.tbSignUpEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpEmail.PlaceholderText = "Enter email...";
            this.tbSignUpEmail.ReadOnly = false;
            this.tbSignUpEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpEmail.SelectedText = "";
            this.tbSignUpEmail.SelectionLength = 0;
            this.tbSignUpEmail.SelectionStart = 0;
            this.tbSignUpEmail.ShortcutsEnabled = true;
            this.tbSignUpEmail.Size = new System.Drawing.Size(392, 39);
            this.tbSignUpEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpEmail.TabIndex = 12;
            this.tbSignUpEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpEmail.TextMarginBottom = 0;
            this.tbSignUpEmail.TextMarginLeft = 3;
            this.tbSignUpEmail.TextMarginTop = 1;
            this.tbSignUpEmail.TextPlaceholder = "Enter email...";
            this.tbSignUpEmail.UseSystemPasswordChar = false;
            this.tbSignUpEmail.WordWrap = true;
            // 
            // tbSignUpPassword
            // 
            this.tbSignUpPassword.AcceptsReturn = false;
            this.tbSignUpPassword.AcceptsTab = false;
            this.tbSignUpPassword.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.tbSignUpPassword.AnimationSpeed = 200;
            this.tbSignUpPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSignUpPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSignUpPassword.AutoSizeHeight = true;
            this.tbSignUpPassword.BackColor = System.Drawing.Color.Transparent;
            this.tbSignUpPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSignUpPassword.BackgroundImage")));
            this.tbSignUpPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSignUpPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSignUpPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSignUpPassword.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbSignUpPassword.BorderRadius = 20;
            this.tbSignUpPassword.BorderThickness = 1;
            this.tbSignUpPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSignUpPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSignUpPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSignUpPassword.DefaultText = "";
            this.tbSignUpPassword.FillColor = System.Drawing.Color.White;
            this.tbSignUpPassword.HideSelection = true;
            this.tbSignUpPassword.IconLeft = null;
            this.tbSignUpPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpPassword.IconPadding = 10;
            this.tbSignUpPassword.IconRight = null;
            this.tbSignUpPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSignUpPassword.Lines = new string[0];
            this.tbSignUpPassword.Location = new System.Drawing.Point(0, 0);
            this.tbSignUpPassword.Margin = new System.Windows.Forms.Padding(0);
            this.tbSignUpPassword.MaxLength = 32767;
            this.tbSignUpPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSignUpPassword.Modified = false;
            this.tbSignUpPassword.Multiline = false;
            this.tbSignUpPassword.Name = "tbSignUpPassword";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpPassword.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSignUpPassword.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpPassword.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.DimGray;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSignUpPassword.OnIdleState = stateProperties20;
            this.tbSignUpPassword.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tbSignUpPassword.PasswordChar = '\0';
            this.tbSignUpPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSignUpPassword.PlaceholderText = "Enter password...";
            this.tbSignUpPassword.ReadOnly = false;
            this.tbSignUpPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSignUpPassword.SelectedText = "";
            this.tbSignUpPassword.SelectionLength = 0;
            this.tbSignUpPassword.SelectionStart = 0;
            this.tbSignUpPassword.ShortcutsEnabled = true;
            this.tbSignUpPassword.Size = new System.Drawing.Size(342, 39);
            this.tbSignUpPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSignUpPassword.TabIndex = 13;
            this.tbSignUpPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSignUpPassword.TextMarginBottom = 0;
            this.tbSignUpPassword.TextMarginLeft = 3;
            this.tbSignUpPassword.TextMarginTop = 1;
            this.tbSignUpPassword.TextPlaceholder = "Enter password...";
            this.tbSignUpPassword.UseSystemPasswordChar = false;
            this.tbSignUpPassword.WordWrap = true;
            // 
            // btnSignUpBack
            // 
            this.btnSignUpBack.AllowAnimations = true;
            this.btnSignUpBack.AllowMouseEffects = true;
            this.btnSignUpBack.AllowToggling = false;
            this.btnSignUpBack.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnSignUpBack.AnimationSpeed = 200;
            this.btnSignUpBack.AutoGenerateColors = false;
            this.btnSignUpBack.AutoRoundBorders = false;
            this.btnSignUpBack.AutoSizeLeftIcon = true;
            this.btnSignUpBack.AutoSizeRightIcon = true;
            this.btnSignUpBack.BackColor = System.Drawing.Color.Transparent;
            this.btnSignUpBack.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSignUpBack.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSignUpBack.BackgroundImage")));
            this.btnSignUpBack.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.ButtonText = "<";
            this.btnSignUpBack.ButtonTextMarginLeft = 0;
            this.btnSignUpBack.ColorContrastOnClick = 45;
            this.btnSignUpBack.ColorContrastOnHover = 45;
            this.btnSignUpBack.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSignUpBack.CustomizableEdges = borderEdges2;
            this.btnSignUpBack.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSignUpBack.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUpBack.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSignUpBack.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSignUpBack.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSignUpBack.Font = new System.Drawing.Font("Symbol", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.btnSignUpBack.ForeColor = System.Drawing.Color.DarkGray;
            this.btnSignUpBack.IconLeft = null;
            this.btnSignUpBack.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignUpBack.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUpBack.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSignUpBack.IconMarginLeft = 11;
            this.btnSignUpBack.IconPadding = 10;
            this.btnSignUpBack.IconRight = null;
            this.btnSignUpBack.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignUpBack.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUpBack.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSignUpBack.IconSize = 25;
            this.btnSignUpBack.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSignUpBack.IdleBorderRadius = 0;
            this.btnSignUpBack.IdleBorderThickness = 0;
            this.btnSignUpBack.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSignUpBack.IdleIconLeftImage = null;
            this.btnSignUpBack.IdleIconRightImage = null;
            this.btnSignUpBack.IndicateFocus = false;
            this.btnSignUpBack.Location = new System.Drawing.Point(3, 10);
            this.btnSignUpBack.Name = "btnSignUpBack";
            this.btnSignUpBack.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUpBack.OnDisabledState.BorderRadius = 20;
            this.btnSignUpBack.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.OnDisabledState.BorderThickness = 1;
            this.btnSignUpBack.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignUpBack.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignUpBack.OnDisabledState.IconLeftImage = null;
            this.btnSignUpBack.OnDisabledState.IconRightImage = null;
            this.btnSignUpBack.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSignUpBack.onHoverState.BorderRadius = 20;
            this.btnSignUpBack.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.onHoverState.BorderThickness = 1;
            this.btnSignUpBack.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btnSignUpBack.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnSignUpBack.onHoverState.IconLeftImage = null;
            this.btnSignUpBack.onHoverState.IconRightImage = null;
            this.btnSignUpBack.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSignUpBack.OnIdleState.BorderRadius = 20;
            this.btnSignUpBack.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.OnIdleState.BorderThickness = 1;
            this.btnSignUpBack.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnSignUpBack.OnIdleState.ForeColor = System.Drawing.Color.DarkGray;
            this.btnSignUpBack.OnIdleState.IconLeftImage = null;
            this.btnSignUpBack.OnIdleState.IconRightImage = null;
            this.btnSignUpBack.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSignUpBack.OnPressedState.BorderRadius = 20;
            this.btnSignUpBack.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUpBack.OnPressedState.BorderThickness = 1;
            this.btnSignUpBack.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnSignUpBack.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnSignUpBack.OnPressedState.IconLeftImage = null;
            this.btnSignUpBack.OnPressedState.IconRightImage = null;
            this.btnSignUpBack.Size = new System.Drawing.Size(21, 35);
            this.btnSignUpBack.TabIndex = 15;
            this.btnSignUpBack.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSignUpBack.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSignUpBack.TextMarginLeft = 0;
            this.btnSignUpBack.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSignUpBack.UseDefaultRadiusAndThickness = true;
            this.btnSignUpBack.Click += new System.EventHandler(this.btnSignUpBack_Click);
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tableLayoutPanel1.BackgroundImage")));
            this.tableLayoutPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tableLayoutPanel1.ColumnCount = 4;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 49.45597F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 49.45599F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1.088032F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Controls.Add(this.bunifuLabel5, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.tbSignUpLastName, 2, 1);
            this.tableLayoutPanel1.Controls.Add(this.btnSignUp, 1, 5);
            this.tableLayoutPanel1.Controls.Add(this.tbSignUpFirstName, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.tbSignUpUsername, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.tbSignUpEmail, 1, 4);
            this.tableLayoutPanel1.Controls.Add(this.btnSignUpBack, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.flowLayoutPanel1, 1, 3);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 7;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(430, 390);
            this.tableLayoutPanel1.TabIndex = 18;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tableLayoutPanel1.SetColumnSpan(this.flowLayoutPanel1, 2);
            this.flowLayoutPanel1.Controls.Add(this.tbSignUpPassword);
            this.flowLayoutPanel1.Controls.Add(this.btnShowPassword);
            this.flowLayoutPanel1.Location = new System.Drawing.Point(30, 168);
            this.flowLayoutPanel1.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(392, 49);
            this.flowLayoutPanel1.TabIndex = 18;
            this.flowLayoutPanel1.WrapContents = false;
            // 
            // ctrlSignUpForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.tableLayoutPanel1);
            this.DoubleBuffered = true;
            this.Name = "ctrlSignUpForm";
            this.Size = new System.Drawing.Size(430, 390);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.flowLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnShowPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSignUp;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpLastName;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpFirstName;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpUsername;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpEmail;
        private Bunifu.UI.WinForms.BunifuTextBox tbSignUpPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSignUpBack;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
    }
}
